#!/usr/bin/env python3
"""Differential harness: Abande vs the AbstractPlay `gameslib` oracle.

MANUAL / ONE-TIME.  Not run by the test suite (it needs node + a gameslib
checkout).  `selftest.py` carries the pure-stdlib anchors.

gameslib (https://github.com/AbstractPlay/gameslib, MIT) is a runnable,
rule-ENFORCING reference implementation of Abande.  It is used here strictly
as an ORACLE: no code is copied from it.

Method: the oracle plays random games and dumps, at EVERY ply, its board, its
hands, the side to move and its full (deduplicated, sorted) legal-move list;
this script replays the identical move sequence through our engine and
compares

  * the board contents cell-by-cell (which also proves the coordinate
    mapping is right -- a wrong mapping shows up as a board mismatch, so the
    move-set comparison cannot pass vacuously),
  * hands and side to move,
  * the legal-move SET (AP's algebraic notation mapped into ours -- never a
    raw string comparison),
  * at the end: terminality, both scores and the winner.

COVERAGE WARNING: uniform-random Abande is placement-heavy (a typical position
offers ~30 entries against ~3 captures), so a plain random run barely touches
tall stacks, the height cap or the band-splitting veto -- exactly the rules most
likely to be wrong.  `--bias` therefore runs several batches with different
probabilities of preferring a stack move; the default sweep is 0 / 0.5 / 0.9.
Judge a run by the POSITION COUNT it prints, and always include a biased batch.

Usage:
    AP_GAMESLIB=/path/to/ap_gameslib python3 _diff_ap.py [--games N] [--seed S]
                                                        [--board square|hex|both]
                                                        [--bias 0,0.5,0.9]
    ... --write-harness      (re)write the TypeScript recorder and exit

Requires `npx ts-node` inside the gameslib checkout.
"""

from __future__ import annotations

import argparse
import json
import os
import subprocess
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[2]))
from agp.loader import load_from_dir                       # noqa: E402

HARNESS = "abande_diff_rec.ts"

HARNESS_SRC = r'''// AUTO-GENERATED by engine/games/abande/_diff_ap.py -- oracle recorder.
import { GameFactory } from "./src/games";

const variant = process.argv[2] || "square";
const ngames = parseInt(process.argv[3] || "20", 10);
const seed0 = parseInt(process.argv[4] || "1", 10);
// Probability of preferring a STACK MOVE when one is available.  Uniform-random
// Abande is placement-heavy (a typical position offers ~30 entries and ~3
// captures), so a 0-bias run barely exercises tall stacks, the height cap or the
// band-splitting veto -- the parts most likely to be wrong.  Run several biases.
const capBias = parseFloat(process.argv[5] || "0");

let s = seed0 >>> 0;
function rnd(): number { s = (s * 1664525 + 1013904223) >>> 0; return s / 4294967296; }

const variants = variant === "square" ? undefined : [variant];

for (let gi = 0; gi < ngames; gi++) {
    const g: any = GameFactory("abande", undefined, variants);
    const plies: any[] = [];
    let n = 0;
    while (!g.gameover && n < 500) {
        const ms: string[] = g.moves();
        const board: any = {};
        for (const [k, v] of g.board.entries()) board[k] = v;
        const rec: any = {
            currplayer: g.currplayer,
            pieces: [...g.pieces],
            board,
            moves: [...new Set(ms)].sort(),
        };
        plies.push(rec);
        if (!ms || ms.length === 0) { rec.stuck = true; break; }
        // NB: short-circuit on capBias === 0 so an unbiased run consumes exactly
        // one rnd() per ply and reproduces the original move sequences.
        const caps = ms.filter((m) => m.indexOf("-") >= 0);
        const pool = (capBias > 0 && caps.length > 0 && rnd() < capBias) ? caps : ms;
        const mv = pool[Math.floor(rnd() * pool.length)];
        g.move(mv);
        rec.chosen = mv;
        n++;
    }
    const board: any = {};
    for (const [k, v] of g.board.entries()) board[k] = v;
    console.log(JSON.stringify({
        game: gi, variant, plies, nplies: n,
        gameover: g.gameover, winner: g.winner,
        scores: [g.getPlayerScore(1), g.getPlayerScore(2)],
        finalboard: board, finalpieces: [...g.pieces],
    }));
}
'''


# --- AP algebraic <-> our cell ids ---------------------------------------
def ap2cell(kind, name):
    """AP algebraic cell name -> our (a,b) cell tuple."""
    letter = ord(name[0]) - ord("a")
    num = int(name[1:])
    if kind == "square":
        return (letter, num - 1)                # 'a1' == (0,0)
    r = 3 - letter                              # hex row 'a' is the bottom row
    qmin = max(-3, -3 - r)
    return (qmin + num - 1, r)


def ap_move(kind, m):
    """AP move string -> our move string."""
    if m == "pass":
        return "pass"
    if "-" in m:
        a, b = m.split("-")
        pa, pb = ap2cell(kind, a), ap2cell(kind, b)
        return f"{pa[0]},{pa[1]}>{pb[0]},{pb[1]}"
    p = ap2cell(kind, m)
    return f"P@{p[0]},{p[1]}"


def ap_board(kind, board):
    return {ap2cell(kind, k): tuple(o - 1 for o in v) for k, v in board.items()}


def run(gameslib, variant, ngames, seed, bias=0.0):
    cmd = ["npx", "ts-node", "--transpileOnly",
           "--compilerOptions", '{"module":"commonjs"}',
           HARNESS, variant, str(ngames), str(seed), str(bias)]
    out = subprocess.run(cmd, cwd=gameslib, capture_output=True, text=True)
    if out.returncode != 0:
        print(out.stderr[-4000:], file=sys.stderr)
        raise SystemExit(f"oracle run failed ({out.returncode})")
    for line in out.stdout.splitlines():
        line = line.strip()
        if line.startswith("{"):
            yield json.loads(line)


def compare(g, rec, report):
    kind = rec["variant"]
    state = g.initial_state({"board": kind})
    for i, ply in enumerate(rec["plies"]):
        where = f"game {rec['game']} ({kind}) ply {i}"
        # side to move / hands
        if state.to_move != ply["currplayer"] - 1:
            report(f"{where}: to_move {state.to_move} vs AP {ply['currplayer'] - 1}")
            return
        if list(state.hands) != ply["pieces"]:
            report(f"{where}: hands {state.hands} vs AP {ply['pieces']}")
            return
        # board (also validates the coordinate mapping)
        if state.board != ap_board(kind, ply["board"]):
            report(f"{where}: BOARD mismatch\n  ours {sorted(state.board.items())}"
                   f"\n  AP   {sorted(ap_board(kind, ply['board']).items())}")
            return
        # move sets
        ours = set(g.legal_moves(state))
        theirs = {ap_move(kind, m) for m in ply["moves"]}
        if ours != theirs:
            report(f"{where}: move-set mismatch\n"
                   f"  only ours: {sorted(ours - theirs)}\n"
                   f"  only AP:   {sorted(theirs - ours)}")
            return
        if g.is_terminal(state) != (i == len(rec["plies"]) - 1 and rec["gameover"]):
            pass  # terminality is checked at the end
        if "chosen" not in ply:
            break
        state = g.apply_move(state, ap_move(kind, ply["chosen"]))
    # terminal state
    if g.is_terminal(state) != rec["gameover"]:
        report(f"game {rec['game']} ({kind}): terminal {g.is_terminal(state)} "
               f"vs AP {rec['gameover']}")
        return
    if state.board != ap_board(kind, rec["finalboard"]):
        report(f"game {rec['game']} ({kind}): final board mismatch")
        return
    ours_scores = list(g.scores(state))
    if ours_scores != rec["scores"]:
        report(f"game {rec['game']} ({kind}): scores {ours_scores} vs AP {rec['scores']}")
        return
    ap_winner = rec["winner"]
    ret = g.returns(state)
    if len(ap_winner) == 2:
        exp = [0.0, 0.0]
    elif ap_winner == [1]:
        exp = [1.0, -1.0]
    else:
        exp = [-1.0, 1.0]
    if ret != exp:
        report(f"game {rec['game']} ({kind}): returns {ret} vs AP winner {ap_winner}")


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--games", type=int, default=200)
    ap.add_argument("--seed", type=int, default=1)
    ap.add_argument("--board", default="both", choices=["square", "hex", "both"])
    ap.add_argument("--bias", default="0,0.5,0.9",
                    help="comma-separated stack-move preference probabilities; "
                         "each is run as its own batch (0 = uniform random)")
    ap.add_argument("--write-harness", action="store_true")
    args = ap.parse_args()

    gameslib = Path(os.environ.get("AP_GAMESLIB", "")).expanduser()
    if not gameslib.is_dir():
        raise SystemExit("set AP_GAMESLIB to a gameslib checkout (with node_modules)")
    (gameslib / HARNESS).write_text(HARNESS_SRC)
    if args.write_harness:
        print(f"wrote {gameslib / HARNESS}")
        return

    _man, g = load_from_dir(Path(__file__).resolve().parent)
    variants = ["square", "hex"] if args.board == "both" else [args.board]

    biases = [float(b) for b in args.bias.split(",")]
    bad = []
    plies = 0
    games = 0
    for v in variants:
        for i, bias in enumerate(biases):
            for rec in run(gameslib, v, args.games, args.seed + 1000 * i, bias):
                games += 1
                plies += len(rec["plies"])
                compare(g, rec, bad.append)
    print(f"compared {games} games / {plies} positions "
          f"across {variants} at biases {biases}")
    if bad:
        print(f"MISMATCHES: {len(bad)}")
        for b in bad[:10]:
            print(" -", b)
        raise SystemExit(1)
    print("no mismatches")


if __name__ == "__main__":
    main()
