"""One-time differential: blokus_trigon legal_moves vs Pentobi's `all_legal`.

Pentobi (Enzenberger, GPL) is the reference Blokus engine and is AUTHORITATIVE
for Trigon's geometry — `libpentobi_base/TrigonGeometry.cpp` is where the board,
the up/down point types and the edge/corner neighbour lists come from. We drive
`pentobi-gtp` in lockstep with our engine down random lines and compare the two
legal-move sets as sets of covered CELL-SETS — so the check is anchor-agnostic
and survives any change to our move-string convention.

This is the check that really proves the TRIANGULAR ROTATION MATHS. A 60-degree
rotation is not an integer map on (c, r), so our pieces are generated by
transforming each triangle's three lattice VERTICES (where D6 is an integer
matrix) and reading the triangle back. A subtly wrong transform would still give
22 connected pieces and would still validate — but it would disagree with Pentobi
here, in a specific size bucket.

MANUAL / ONE-TIME — deliberately NOT a `selftest.py` (the suite globs only that
name, and selftests must be pure-stdlib with no external binaries). The Pentobi
opening count is frozen into `selftest.py` as the standing anchor: 2478 moves,
split {1: 6, 2: 18, 3: 54, 4: 168, 5: 540, 6: 1692}.

Needs a local Pentobi build, which this repo does not vendor:

    git clone --depth 1 https://github.com/enz/pentobi.git
    cd pentobi && cmake -B build -DPENTOBI_BUILD_GTP=ON -DPENTOBI_BUILD_GUI=OFF \
        -DCMAKE_BUILD_TYPE=Release && cmake --build build -j
    PENTOBI_GTP=$PWD/build/pentobi_gtp/pentobi-gtp python3 _diff_pentobi.py

(`pip install cmake` if cmake is absent; the GTP target needs no Qt.)

GTP notes: the variant is `set_game blokus trigon` (the FULL name — `trigon`
alone is not parsed, see Variant.cpp `parse_variant`); the four colours are named
`1`/`2`/`3`/`4`; and `all_legal` returns a MULTI-LINE response terminated by a
blank line, so reading a single line silently under-reports it. Cell names are
Pentobi's bijective base-26 column letter + a 1-based row counted from the BOTTOM
(`get_letter_coord` / `StdStringRep::write`, which prints `height - y`), e.g.
`r15` is our (17, 14) and column 34 is `ai`.

Last run: legal-move sets identical to Pentobi across 405 positions spanning six
full random 4-player games (to ply 64-71, every one played out to a terminal
position), including the 2478-move opening for all four colours; `final_score`
agreed 6/6 including the +15/+5 bonuses.
"""
import os
import random
import shutil
import subprocess
import sys

from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[2]))  # -> engine/
import games.blokus_trigon.game as G  # noqa: E402

# Point PENTOBI_GTP at your build; falls back to one on PATH.
GTP = os.environ.get("PENTOBI_GTP") or shutil.which("pentobi-gtp") or "pentobi-gtp"
COLORS = ("1", "2", "3", "4")


def to_pent(cells):
    """our (c, r) [row 0 = bottom] -> pentobi 'r15', sorted and comma-joined."""
    return ",".join(sorted(f"{G._coord_name(c)}{r + 1}" for c, r in cells))


class Pentobi:
    def __init__(self):
        if not (Path(GTP).exists() or shutil.which(GTP)):
            raise SystemExit(f"pentobi-gtp not found at {GTP!r} — see the module "
                             f"docstring for build steps, then set $PENTOBI_GTP.")
        self.p = subprocess.Popen([GTP], stdin=subprocess.PIPE, stdout=subprocess.PIPE,
                                  stderr=subprocess.DEVNULL, text=True, bufsize=1)
        self.cmd("set_game blokus trigon")

    def cmd(self, c):
        self.p.stdin.write(c + "\n")
        self.p.stdin.flush()
        out = []
        while True:
            line = self.p.stdout.readline()
            if line == "":
                raise RuntimeError("pentobi died")
            if line.strip() == "" and out:
                break
            if line.startswith("?"):
                raise RuntimeError(f"pentobi error on {c!r}: {line}")
            out.append(line.rstrip("\n"))
        return " ".join(out).lstrip("= ").strip()

    def legal(self, color):
        r = self.cmd(f"all_legal {color}")
        return {frozenset(m.split(",")) for m in r.split()} if r else set()


def ours(state, seat=None):
    g = G.BlokusTrigon()
    moves = g.legal_moves(state) if seat is None else list(g._gen(state, seat))
    return {frozenset(to_pent(G._cells_of(G.MOVE_MASK[m])).split(",")) for m in moves}


def main(trials=6, depth=100, seed=7):
    rng = random.Random(seed)
    g = G.BlokusTrigon()
    total_pos = 0
    scored = 0

    # The opening, for every colour: the standing 2478 anchor.
    pent = Pentobi()
    s0 = g.initial_state()
    for seat in range(4):
        theirs = pent.legal(COLORS[seat])
        mine = ours(s0, seat)
        if mine != theirs:
            print(f"MISMATCH opening seat {seat}: ours={len(mine)} pentobi={len(theirs)}")
            return 1
        assert len(mine) == 2478, len(mine)
        total_pos += 1
    pent.cmd("quit")
    print(f"  opening: all 4 colours agree at {len(mine)} moves")

    for t in range(trials):
        pent = Pentobi()
        s = g.initial_state()
        ply = 0
        for ply in range(depth):
            if g.is_terminal(s):
                break
            seat = g.current_player(s)
            mine = ours(s)
            theirs = pent.legal(COLORS[seat])
            total_pos += 1
            if mine != theirs:
                print(f"MISMATCH trial {t} ply {ply} seat {seat}")
                print(f"  ours={len(mine)} pentobi={len(theirs)}")
                only_us = list(mine - theirs)[:3]
                only_them = list(theirs - mine)[:3]
                print(f"  only ours   : {[sorted(x) for x in only_us]}")
                print(f"  only pentobi: {[sorted(x) for x in only_them]}")
                return 1
            mv = rng.choice(g.legal_moves(s))
            pent.cmd(f"play {COLORS[seat]} {to_pent(G._cells_of(G.MOVE_MASK[mv]))}")
            s = g.apply_move(s, mv)

        # Scoring cross-check. Pentobi's `final_score` prints get_points(c) for
        # each colour: triangles PLACED plus the bonuses. The rulebook (and our
        # `score`) instead counts -1 per REMAINING triangle plus the same
        # bonuses, so the two differ by exactly the 110 triangles in a full set:
        #     ours(c) = placed - 110 + bonus = pentobi_points(c) - 110
        # An equivalent ordering, but this pins the +15/+5 bonuses and the
        # per-piece triangle counts, which `all_legal` never touches.
        pts = [float(x) for x in pent.cmd("final_score").split()]
        assert len(pts) == 4, pts
        mine_sc = [g.score(s, i) for i in range(4)]
        want = [int(x) - G.TOTAL_TRIANGLES for x in pts]
        if mine_sc != want:
            print(f"SCORE MISMATCH trial {t}: ours={mine_sc} pentobi-110={want}")
            return 1
        scored += 1

        pent.cmd("quit")
        print(f"  trial {t}: OK through ply {ply}, final score {mine_sc} agrees")
    print(f"DIFFERENTIAL OK — {total_pos} positions, legal-move sets identical; "
          f"final_score agreed {scored}/{trials} including the bonuses")
    return 0


if __name__ == "__main__":
    sys.exit(main())
