"""Blokus Trigon — the polyiamond Blokus (Bernard Tavitian; Sekkoia 2006 / Mattel).

Four players each hold the same 22 pieces: every FREE polyiamond of size 1..6
(1+1+1+3+4+12). Rotations AND reflections are both allowed, which is exactly why
the count is 22 (the one-sided count would be 1+1+1+4+6+19 = 32).

Rules as implemented (Mattel R1985 "Blokus Trigon" rulebook, R1985-0920.pdf):

* "a board with 486 spaces" — a hexagon of side 9 on a triangular lattice
  (6 x 9^2 = 486 unit triangles).
* "88 pieces in four different colors (22 pieces of each color). Each of the 22
  pieces is a different shape. There are: 1 piece with one triangle, 1 piece with
  two triangles, 1 piece with three triangles, 3 pieces with four triangles,
  4 pieces with five triangles and 12 pieces with six triangles."
* "The first piece played by each player must cover one of the starting points
  indicated by the triangle symbol." There are SIX start points and they are
  SHARED — any colour may open on any of them (unlike classic Blokus, where each
  colour owns one corner). The rulebook's three-player variant makes this
  explicit: "There are 6 starting points and 3 players so one starting point
  should be left unoccupied between each player's starting point."
* "Each new piece must touch at least one other piece of the same color but
  without contact between two sides."
* "There are no restrictions on how many pieces of different colors may be in
  contact with each other."
* "The game ends for a player when he/she is blocked and can no longer put down
  any pieces... However, a player MUST play if it is possible to play. The game
  ends when all players are blocked from laying down any more of their pieces."
  Passing is implicit here (see `apply_move`).
* Scoring: "1 unit triangle = -1 point"; "+15 points if all his/her pieces have
  been placed on the board plus 5 additional bonus points if the last piece
  placed on the board was the smallest piece (one triangle)".
* Ties: the rulebook says only "the player with the highest score is the winner"
  and is SILENT on ties. A tie for first is an honest DRAW (see rules.md).

Moves use the palette primitive: ``"KEY:o@c,r"`` — piece KEY, orientation index
o into ``ORIENTS[KEY]``, anchored at cell ``c,r``. The anchor is the piece's
bottom-most then left-most covered triangle, so every orientation contains
``[0, 0]`` and the anchor is always a cell the piece covers.

THE LATTICE
-----------
Cells are indexed ``(c, r)``: ``r`` is the row (0 = BOTTOM, as everywhere on this
platform) and ``c`` steps by HALF a triangle-width, so consecutive ``c`` in a row
alternate between up- and down-pointing triangles. Our convention is

    (c, r) points UP  <=>  (c + r) is ODD

which is Pentobi's ``TrigonGeometry::get_point_type() == 0`` re-expressed in our
bottom-up rows (Pentobi's y runs TOP-DOWN, so r = height - 1 - y = 17 - y, and
odd `height` flips the parity of the sum). Per SPEC the engine is free to pick
either parity so long as the board geometry and the `parity` array agree.

Edge neighbours (3 per triangle) and corner neighbours (9 per triangle) are
Pentobi's ``get_adj_coord`` / ``get_diag_coord`` translated into our rows; those
two lists ARE the Blokus rule ("touch at the corners, never along an edge").
`selftest.py` re-derives both from first principles via an independent vertex
model, so they are not taken on trust.

Rotation by 60 degrees is NOT an integer map on (c, r). Pieces are therefore
generated by mapping each triangle to its three LATTICE VERTICES, transforming
those (the vertex lattice is a plain 2-D lattice on which the 12 symmetries of
D6 are integer matrices), and reading the triangle back. See `_verts`.
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import Iterator, Optional

from agp.game import Game

SZ = 9                       # hexagon side, in triangles (the standard board)
W, H = SZ * 4 - 1, SZ * 2    # 35 x 18 lattice rows/columns
N_CELLS = W * H              # bitboard span (486 of these are on-board)
NUM_PLAYERS = 4


def _onboard(c: int, r: int) -> bool:
    """Pentobi TrigonGeometry::init_is_onboard, with our bottom-up rows.

    Carves the hexagon: each row away from the middle loses one cell at each
    end, giving 19, 21, ... 35, 35, ... 21, 19 = 486 cells.
    """
    y = H - 1 - r                       # -> Pentobi's top-down y
    if not (0 <= c < W and 0 <= y < H):
        return False
    dy = min(y, H - y - 1)
    min_x = SZ - dy - 1
    return min_x <= c <= W - min_x - 1


def _up(c: int, r: int) -> bool:
    """True if triangle (c, r) points UP (its horizontal edge is at the bottom)."""
    return (c + r) % 2 == 1


ON_CELLS = tuple((c, r) for r in range(H) for c in range(W) if _onboard(c, r))

# Start points — Pentobi StartingPoints::init, BoardType::trigon, mapped through
# r = 17 - y. All six are COLORLESS in Pentobi, i.e. shared by every colour.
START = ((9, 6), (9, 11), (17, 3), (17, 14), (25, 6), (25, 11))


# --------------------------------------------------------------------------
# Lattice adjacency (Pentobi get_adj_coord / get_diag_coord, our rows).
# --------------------------------------------------------------------------

# Edge neighbours: both types have (c-1, r) and (c+1, r); the third is the cell
# across the horizontal edge — BELOW an up-triangle, ABOVE a down-triangle.
_ADJ_UP = ((-1, 0), (1, 0), (0, -1))
_ADJ_DOWN = ((-1, 0), (1, 0), (0, 1))

# Corner neighbours: the 9 cells sharing exactly ONE vertex with this triangle
# (3 vertices x 3 non-edge-sharing cells each).
_DIAG_UP = ((-2, 0), (2, 0), (-1, 1), (1, 1), (1, -1), (-1, -1), (0, 1), (-2, -1), (2, -1))
_DIAG_DOWN = ((-2, 0), (2, 0), (-1, -1), (1, -1), (1, 1), (-1, 1), (0, -1), (-2, 1), (2, 1))


def _adj(c: int, r: int):
    return [(c + dc, r + dr) for dc, dr in (_ADJ_UP if _up(c, r) else _ADJ_DOWN)]


# --------------------------------------------------------------------------
# Piece set: generated programmatically on the vertex lattice, then named.
# --------------------------------------------------------------------------
#
# A triangle's three vertices live on the ordinary 2-D lattice spanned by
# e1 = (1, 0) and e2 = (1/2, sqrt3/2); vertex (i, j) is the point i*e1 + j*e2.
# On that lattice every symmetry of the triangular grid is an integer matrix:
#   rotate 60 degrees:  (i, j) -> (-j, i + j)
#   reflect:            (i, j) -> (i + j, -j)
# so the 12 elements of D6 are exact integer maps — which a rotation on (c, r)
# is NOT. We therefore rotate VERTICES and read the triangle back.

def _verts(c: int, r: int) -> frozenset:
    """The three lattice vertices of triangle (c, r)."""
    if _up(c, r):
        return frozenset({((c - r - 1) // 2, r), ((c - r + 1) // 2, r),
                          ((c - r - 1) // 2, r + 1)})
    return frozenset({((c - r - 2) // 2, r + 1), ((c - r) // 2, r + 1),
                      ((c - r) // 2, r)})


def _from_verts(vs) -> tuple:
    """Inverse of `_verts`: the triangle with these three vertices.

    An up-triangle has TWO vertices on its lower row and one above; a
    down-triangle has one below and two above — which is what tells them apart.
    """
    rmin = min(j for _, j in vs)
    low = sorted(i for i, j in vs if j == rmin)
    if len(low) == 2:                       # up-pointing
        return (2 * low[0] + rmin + 1, rmin)
    return (2 * low[0] + rmin, rmin)        # down-pointing


def _rot60(v):
    i, j = v
    return (-j, i + j)


def _mirror(v):
    i, j = v
    return (i + j, -j)


def _make_transform(flip: bool, k: int):
    def f(v):
        if flip:
            v = _mirror(v)
        for _ in range(k):
            v = _rot60(v)
        return v
    return f


# The 12 symmetries of the triangular lattice (D6): 6 rotations x optional flip.
TRANSFORMS = tuple(_make_transform(flip, k) for flip in (False, True) for k in range(6))


def _apply(cells, t):
    return [_from_verts(frozenset(t(v) for v in _verts(c, r))) for c, r in cells]


def _normalize(cells) -> tuple:
    """Translate so the tile's ANCHOR sits at (0, 0); returns (offsets, parity).

    The anchor is the tile's **bottom-most, then left-most covered cell**, so
    every orientation contains (0, 0) and the anchor is always a triangle the
    tile actually covers (SPEC's anchor contract). `dr` is therefore always >= 0
    while `dc` may be NEGATIVE.

    `parity` is 0 if the anchor points UP, 1 if it points DOWN — SPEC's
    `palette.parity`. It is NOT redundant: on a triangular lattice a translation
    by an odd (dc + dr) swaps up- and down-triangles, so the offsets alone do not
    determine the shape. (offsets, parity) together do, and the pair is a
    canonical representative under the parity-PRESERVING translations — the only
    ones that are actual translations of the plane.
    """
    ar, ac = min((r, c) for c, r in cells)          # bottom-most, then left-most
    offs = tuple(sorted((c - ac, r - ar) for c, r in cells))
    return (offs, 0 if _up(ac, ar) else 1)


def _orients(cells) -> list:
    """All distinct rotations+reflections, each as (offsets, parity)."""
    out, seen = [], set()
    for t in TRANSFORMS:
        n = _normalize(_apply(cells, t))
        if n not in seen:
            seen.add(n)
            out.append(n)
    return out


def _canonical(cells) -> tuple:
    """Free-polyiamond identity: the lexicographically smallest orientation."""
    return min(_orients(cells))


def _denorm(n) -> list:
    """A concrete placement of a normalised (offsets, parity), for re-analysis."""
    offs, p = n
    c0, r0 = (1, 0) if p == 0 else (0, 0)           # an anchor of the right parity
    return [(c0 + dc, r0 + dr) for dc, dr in offs]


def _free_polyiamonds(n: int) -> set:
    """All free polyiamonds of size n, as canonical forms (grown from one cell)."""
    cur = {((1, 0),)}
    for _ in range(n - 1):
        nxt = set()
        for sh in cur:
            for (c, r) in sh:
                for p in _adj(c, r):
                    if p not in sh:
                        nxt.add(tuple(sorted(sh + (p,))))
        cur = nxt
    return {_canonical(list(sh)) for sh in cur}


# The 22 Blokus Trigon pieces. Shapes and names are Pentobi's
# `create_pieces_trigon()` (libpentobi_base/BoardConst.cpp) — Pentobi is the
# reference Blokus engine, and its names follow the "Trigon book" notation from
# the Blokus forums. Its PiecePoints are in Pentobi's (x, y) with y top-down and
# up-triangles at even (x + y); mapping (x, y) -> (c, r) = (x, 1 - y) lands them
# in our indexing with up/down preserved (any ODD constant works: it flips the
# row order and re-parities the sum, which cancel).
_PENTOBI_POINTS = {
    "I6": [(1, -1), (2, -1), (0, 0), (1, 0), (-1, 1), (0, 1)],
    "L6": [(1, -1), (2, -1), (0, 0), (1, 0), (0, 1), (1, 1)],
    "V": [(-2, -1), (-1, -1), (-1, 0), (0, 0), (1, 0), (2, 0)],
    "S": [(-1, -1), (0, -1), (-1, 0), (0, 0), (-1, 1), (0, 1)],
    "P6": [(1, -1), (0, 0), (1, 0), (2, 0), (-1, 1), (0, 1)],
    "F": [(0, 0), (1, 0), (0, 1), (1, 1), (2, 1), (1, 2)],
    "W": [(1, -1), (-1, 0), (0, 0), (1, 0), (2, 0), (3, 0)],
    "A6": [(1, -1), (0, 0), (1, 0), (2, 0), (0, 1), (2, 1)],
    "G": [(1, -1), (0, 0), (1, 0), (0, 1), (1, 1), (2, 1)],
    "Y": [(-1, -1), (-1, 0), (0, 0), (1, 0), (-1, 1), (0, 1)],
    "X": [(-1, 0), (0, 0), (1, 0), (-1, 1), (0, 1), (1, 1)],
    "O": [(-1, -1), (0, -1), (1, -1), (-1, 0), (0, 0), (1, 0)],
    "I5": [(1, -1), (0, 0), (1, 0), (-1, 1), (0, 1)],
    "L5": [(1, -1), (0, 0), (1, 0), (0, 1), (1, 1)],
    "C5": [(0, 0), (1, 0), (0, 1), (1, 1), (2, 1)],
    "P5": [(1, -1), (0, 0), (1, 0), (2, 0), (0, 1)],
    "I4": [(0, 0), (1, 0), (-1, 1), (0, 1)],
    "C4": [(0, 0), (1, 0), (0, 1), (1, 1)],
    "A4": [(1, -1), (0, 0), (1, 0), (2, 0)],
    "I3": [(1, -1), (0, 0), (1, 0)],
    "2": [(0, 0), (1, 0)],
    "1": [(0, 0)],
}
_NAMED = {k: _canonical([(x, 1 - y) for x, y in pts])
          for k, pts in _PENTOBI_POINTS.items()}

# Verify the named set IS exactly the free polyiamonds of size 1..6. This checks
# the naming table against generation (no typos, no duplicates, none missing) AND
# — because a wrong rotation/reflection map would merge or split classes — that
# the D6 action on the vertex lattice is right.
_GENERATED = set()
for _n in range(1, 7):
    _GENERATED |= _free_polyiamonds(_n)
if set(_NAMED.values()) != _GENERATED:
    raise AssertionError("piece table is not the free polyiamonds of size 1..6")
if len(_NAMED) != 22:
    raise AssertionError(f"expected 22 pieces, got {len(_NAMED)}")

PIECES = tuple(_NAMED)                                    # stable key order
_ORIENT_DATA = {k: _orients(_denorm(v)) for k, v in _NAMED.items()}
ORIENTS = {k: [[list(o) for o in offs] for offs, _ in v] for k, v in _ORIENT_DATA.items()}
PARITY = {k: [p for _, p in v] for k, v in _ORIENT_DATA.items()}
SIZES = {k: len(_NAMED[k][0]) for k in PIECES}
MONOMINO = "1"
TOTAL_TRIANGLES = sum(SIZES.values())                      # 110 per colour


# --------------------------------------------------------------------------
# Bitboards. Bit index of (c, r) is r * W + c.
# --------------------------------------------------------------------------

def _bit(c: int, r: int) -> int:
    return 1 << (r * W + c)


FULL = (1 << N_CELLS) - 1
ON_BOARD = 0
for _c, _r in ON_CELLS:
    ON_BOARD |= _bit(_c, _r)

UP_MASK = 0
for _c, _r in ON_CELLS:
    if _up(_c, _r):
        UP_MASK |= _bit(_c, _r)
DOWN_MASK = ON_BOARD & ~UP_MASK

# Column masks, so a horizontal shift cannot wrap into the next row.
_COL_GE = [0] * (W + 1)      # cells with c >= k
_COL_LE = [0] * (W + 1)      # cells with c <= k
for _k in range(W + 1):
    _ge = _le = 0
    for _r in range(H):
        for _c in range(W):
            _b = 1 << (_r * W + _c)
            if _c >= _k:
                _ge |= _b
            if _c <= _k:
                _le |= _b
    _COL_GE[_k], _COL_LE[_k] = _ge, _le


def _shift(bb: int, dc: int, dr: int) -> int:
    """Translate a bitboard by (dc, dr), dropping anything that leaves the grid.

    Columns are masked BEFORE the shift so a bit can never wrap into an adjacent
    row; rows then fall off either end of the integer or are cut by ON_BOARD.
    """
    if dc > 0:
        bb &= _COL_LE[W - 1 - dc]
    elif dc < 0:
        bb &= _COL_GE[-dc]
    n = dr * W + dc
    return (bb << n) if n >= 0 else (bb >> -n)


def _edge_zone(own: int) -> int:
    """Cells sharing an EDGE with `own` (where same-colour contact is banned)."""
    return (_shift(own, 1, 0) | _shift(own, -1, 0)
            | _shift(own & UP_MASK, 0, -1) | _shift(own & DOWN_MASK, 0, 1)) & ON_BOARD


def _corner_zone(own: int) -> int:
    """Cells sharing exactly a CORNER with `own` (where a legal touch happens)."""
    out = 0
    up, down = own & UP_MASK, own & DOWN_MASK
    for dc, dr in _DIAG_UP:
        out |= _shift(up, dc, dr)
    for dc, dr in _DIAG_DOWN:
        out |= _shift(down, dc, dr)
    return out & ON_BOARD


START_MASK = 0
for _c, _r in START:
    if not _onboard(_c, _r):
        raise AssertionError(f"start point off board: {_c},{_r}")
    START_MASK |= _bit(_c, _r)


def _build_placements():
    """Every (orientation, anchor) that fits on the board, as (mask, move-string).

    Precomputed once at import (~32k placements), so move generation is two
    integer ops per candidate. The anchor's parity must match the orientation's:
    only parity-preserving translations are real translations of the plane, so an
    anchor of the wrong parity is never generated (SPEC).
    """
    out = {}
    lookup = {}
    on = set(ON_CELLS)
    for key in PIECES:
        entries = []
        for oi, (offs, p) in enumerate(_ORIENT_DATA[key]):
            for (ac, ar) in ON_CELLS:
                if (0 if _up(ac, ar) else 1) != p:
                    continue
                cells = [(ac + dc, ar + dr) for dc, dr in offs]
                if not all(x in on for x in cells):
                    continue
                mask = 0
                for c, r in cells:
                    mask |= _bit(c, r)
                mv = f"{key}:{oi}@{ac},{ar}"
                entries.append((mask, mv))
                lookup[mv] = mask
        out[key] = tuple(entries)
    return out, lookup


PLACEMENTS, MOVE_MASK = _build_placements()


def _cells_of(mask: int):
    return [(i % W, i // W) for i in range(N_CELLS) if mask >> i & 1]


# --------------------------------------------------------------------------
# State
# --------------------------------------------------------------------------

@dataclass
class BState:
    occ: tuple = (0, 0, 0, 0)                             # per-seat occupancy
    hands: tuple = (PIECES, PIECES, PIECES, PIECES)      # per-seat remaining keys
    to_move: int = 0
    last: tuple = ()                                     # cells of the last placement
    last_key: tuple = (None, None, None, None)           # each seat's latest piece


class BlokusTrigon(Game):
    name = "Blokus Trigon"

    @property
    def num_players(self) -> int:
        return NUM_PLAYERS

    def initial_state(self, options=None, rng=None) -> BState:
        return BState()

    def current_player(self, s: BState) -> int:
        return s.to_move

    # -- move generation ---------------------------------------------------

    def _gen(self, s: BState, seat: int) -> Iterator[str]:
        own = s.occ[seat]
        both = s.occ[0] | s.occ[1] | s.occ[2] | s.occ[3]
        if own == 0:
            # First piece: must cover one of the SIX shared start points. No
            # corner rule applies (nothing of your colour to touch yet). A start
            # point already taken by another colour is simply occupied, so the
            # overlap test retires it — exactly the rulebook's behaviour.
            for key in s.hands[seat]:
                for mask, mv in PLACEMENTS[key]:
                    if not (mask & both) and (mask & START_MASK):
                        yield mv
        else:
            forbidden = both | _edge_zone(own)
            corners = _corner_zone(own)
            for key in s.hands[seat]:
                for mask, mv in PLACEMENTS[key]:
                    if not (mask & forbidden) and (mask & corners):
                        yield mv

    def _any_moves(self, s: BState, seat: int) -> bool:
        for _ in self._gen(s, seat):
            return True
        return False

    def legal_moves(self, s: BState) -> list[str]:
        return list(self._gen(s, s.to_move))

    def apply_move(self, s: BState, move: str, rng=None) -> BState:
        seat = s.to_move
        mask = MOVE_MASK.get(move)
        if mask is None:
            raise ValueError(f"malformed move: {move}")
        key = move.split(":", 1)[0]
        if key not in s.hands[seat]:
            raise ValueError(f"piece already used: {move}")
        own = s.occ[seat]
        both = s.occ[0] | s.occ[1] | s.occ[2] | s.occ[3]
        if mask & both:
            raise ValueError(f"overlapping placement: {move}")
        if own == 0:
            if not (mask & START_MASK):
                raise ValueError(f"first piece must cover a start point: {move}")
        else:
            if mask & _edge_zone(own):
                raise ValueError(f"edge contact with own colour: {move}")
            if not (mask & _corner_zone(own)):
                raise ValueError(f"no corner contact with own colour: {move}")

        occ = list(s.occ)
        occ[seat] |= mask
        hands = list(s.hands)
        hands[seat] = tuple(k for k in hands[seat] if k != key)
        last_key = list(s.last_key)
        last_key[seat] = key
        ns = BState(occ=tuple(occ), hands=tuple(hands), to_move=seat,
                    last=tuple(_cells_of(mask)), last_key=tuple(last_key))

        # Advance to the next seat that can place. "A player MUST play if it is
        # possible to play"; a blocked player "can no longer put down any pieces"
        # and is skipped — modelled implicitly, so legal_moves is never empty on
        # a non-terminal state (per SPEC). Being blocked is in fact permanent (a
        # seat's options only shrink while it adds nothing of its own), but we
        # re-check every seat rather than relying on that.
        for step in range(1, NUM_PLAYERS + 1):
            nxt = (seat + step) % NUM_PLAYERS
            if self._any_moves(ns, nxt):
                ns.to_move = nxt
                break
        else:
            ns.to_move = seat          # nobody can move: the game is over
        return ns

    # -- terminal / scoring ------------------------------------------------

    def is_terminal(self, s: BState) -> bool:
        # Computed from the position (not stored as an event), so hand-built
        # blocked positions are correctly terminal too.
        return not any(self._any_moves(s, seat) for seat in range(NUM_PLAYERS))

    def score(self, s: BState, seat: int) -> int:
        """Rulebook scoring: -1 per remaining unit triangle; +15 for placing all
        22 pieces; +5 more if the last piece placed was the single triangle."""
        hand = s.hands[seat]
        pts = -sum(SIZES[k] for k in hand)
        if not hand:
            pts += 15
            if s.last_key[seat] == MONOMINO:
                pts += 5
        return pts

    def returns(self, s: BState) -> list[float]:
        if not self.is_terminal(s):
            return [0.0] * NUM_PLAYERS
        sc = [self.score(s, i) for i in range(NUM_PLAYERS)]
        best = max(sc)
        winners = [i for i, v in enumerate(sc) if v == best]
        # +1 to the sole leader, -1 to everyone else; a tie for first is an
        # honest DRAW (the rulebook is silent on ties) — see rules.md.
        if len(winners) == 1:
            return [1.0 if i == winners[0] else -1.0 for i in range(NUM_PLAYERS)]
        return [0.0] * NUM_PLAYERS

    def heuristic(self, s: BState) -> list[float]:
        """Per-seat score margin vs the best rival, squashed.

        MUST return one payoff PER SEAT, in the same convention as `returns`:
        `MCTSBot._rollout` hands this straight to back-propagation, which indexes
        it as `payoffs[p]`. A bare float raises `TypeError: 'float' object is not
        subscriptable` — and unlike Duo the cutoff really bites here, since a
        Trigon game runs well past the default `max_rollout=50` plies.
        """
        sc = [self.score(s, i) for i in range(NUM_PLAYERS)]
        out = []
        for i in range(NUM_PLAYERS):
            rival = max(sc[j] for j in range(NUM_PLAYERS) if j != i)
            out.append(max(-1.0, min(1.0, (sc[i] - rival) / 30.0)))
        return out

    # -- serialization -----------------------------------------------------

    def serialize(self, s: BState) -> dict:
        return {
            "occ": [str(x) for x in s.occ],
            "hands": [list(h) for h in s.hands],
            "to_move": s.to_move,
            "last": [f"{c},{r}" for c, r in s.last],
            "last_key": list(s.last_key),
        }

    def deserialize(self, d: dict) -> BState:
        cell = lambda t: tuple(int(x) for x in t.split(","))  # noqa: E731
        return BState(
            occ=tuple(int(x) for x in d["occ"]),
            hands=tuple(tuple(h) for h in d["hands"]),
            to_move=d["to_move"],
            last=tuple(cell(x) for x in d.get("last", [])),
            last_key=tuple(d.get("last_key", [None] * NUM_PLAYERS)),
        )

    def describe_move(self, s: BState, move: str) -> str:
        key, rest = move.split(":", 1)
        c, r = (int(x) for x in rest.split("@", 1)[1].split(","))
        return f"{key}@{_coord_name(c)}{r + 1}"

    # -- rendering ---------------------------------------------------------

    def render(self, s: BState, perspective=None) -> dict:
        pieces = []
        for seat in range(NUM_PLAYERS):
            for c, r in _cells_of(s.occ[seat]):
                pieces.append({"cell": f"{c},{r}", "owner": seat, "shape": "fill"})

        palette = {}
        for seat in range(NUM_PLAYERS):
            palette[str(seat)] = [
                {"key": k, "label": f"{k} ({SIZES[k]})", "orients": ORIENTS[k],
                 "grid": "tri", "parity": PARITY[k]}
                for k in s.hands[seat]
            ]

        # Base shading by triangle orientation (the default polygons parity is a
        # 3-colouring meant for hexes and reads as noise here), with the six
        # shared start points marked while they are still uncovered.
        both = s.occ[0] | s.occ[1] | s.occ[2] | s.occ[3]
        tints = {}
        for c, r in ON_CELLS:
            tints[f"{c},{r}"] = "#2f2a23" if _up(c, r) else "#272219"
        for c, r in START:
            if not (_bit(c, r) & both):
                tints[f"{c},{r}"] = "#c8b88a"

        sc = [self.score(s, i) for i in range(NUM_PLAYERS)]
        if self.is_terminal(s):
            best = max(sc)
            winners = [i for i, v in enumerate(sc) if v == best]
            head = (f"Player {winners[0] + 1} wins" if len(winners) == 1
                    else "Draw — " + ", ".join(f"P{i + 1}" for i in winners) + " tie")
            caption = head + " — final " + ", ".join(
                f"P{i + 1} {sc[i]:+d}" for i in range(NUM_PLAYERS))
        else:
            caption = f"Player {s.to_move + 1} to move — " + ", ".join(
                f"P{i + 1} {sc[i]:+d} ({len(s.hands[i])})" for i in range(NUM_PLAYERS))

        return {
            "board": {"type": "polygons", "cells": _BOARD_CELLS, "tints": tints},
            "pieces": pieces,
            "highlights": [{"cell": f"{c},{r}", "kind": "last-move"} for c, r in s.last],
            "palette": palette,
            "caption": caption,
        }


def _coord_name(c: int) -> str:
    """Pentobi's bijective base-26 column name (0->a, 25->z, 26->aa, 34->ai)."""
    out = ""
    i = c
    while True:
        out = chr(ord("a") + i % 26) + out
        i //= 26
        if i == 0:
            break
        i -= 1
    return out


# --------------------------------------------------------------------------
# Board polygons (built once). `points` are SVG pixels, y DOWN — the renderer
# uses a polygons board's points as-is — so row r (0 = bottom) is drawn at the
# bottom. `cells` MUST be a LIST of {id, points} with numeric "c,r" ids.
# --------------------------------------------------------------------------

_TW = 34.0                      # triangle width (base), in px
_TH = _TW * 0.8660254037844386  # height = sqrt(3)/2 * width (equilateral)


def _poly(c: int, r: int):
    x0, x1 = c / 2.0 * _TW, (c / 2.0 + 1.0) * _TW
    xm = (c / 2.0 + 0.5) * _TW
    y_top = (H - 1 - r) * _TH               # screen y of this row's top edge
    y_bot = (H - r) * _TH
    if _up(c, r):
        return [[round(x0, 2), round(y_bot, 2)], [round(x1, 2), round(y_bot, 2)],
                [round(xm, 2), round(y_top, 2)]]
    return [[round(x0, 2), round(y_top, 2)], [round(x1, 2), round(y_top, 2)],
            [round(xm, 2), round(y_bot, 2)]]


_BOARD_CELLS = [{"id": f"{c},{r}", "points": _poly(c, r)} for c, r in ON_CELLS]
