#!/usr/bin/env python3
"""Differential harness: this package vs. the AbstractPlay `gameslib` oracle.

MANUAL / ONE-TIME — this is NOT part of the test suite (it needs node + a
checkout of https://github.com/AbstractPlay/gameslib, which is MIT-licensed and
used here purely as a rule-enforcing oracle; no code from it was copied).

Usage:
    AP_GAMESLIB=/path/to/gameslib python3 _diff_ap.py --games 200 --seed 1
    AP_GAMESLIB=... python3 _diff_ap.py --config 6/short --games 200

It writes a small TypeScript driver (`terrace_oracle.ts`) into the gameslib
checkout, runs it under ts-node as a line-oriented JSON co-process, and plays
random games in LOCKSTEP through both implementations.  At **every** ply it
compares, in a coordinate system it converts explicitly:

  * the full set of legal moves as (from-cell, to-cell) pairs — NOT raw move
    strings, so the comparison survives either side's notation,
  * the whole board: owner, size and royal flag of every occupied square,
  * the side to move,
  * terminality and the winner.

Coordinate mapping (proved on every run by ``check_mapping``, which is always
on): AbstractPlay uses algebraic `a1`..`h8`; we use `"c,r"` with c = file - 'a'
and r = rank - 1, so cell index i = r*n + c.  The guard checks three
independent, ASYMMETRIC facts — the elevation table, the whole opening array
(owner/size/royal, which the 180-degree-rotational board symmetry would NOT
preserve under a transposed or flipped mapping), and a hand-picked move whose
effect pins the diagonal-down capture direction.

Two *expected* divergences are counted separately rather than reported as bugs:

  ap-eog-order  AbstractPlay checks "the player to move has no legal move =>
                draw" BEFORE it checks whether the previous player just won, so
                a T that reaches its corner (or a T capture) on the very ply
                that strands the opponent is scored 0-0 there.  This package
                puts the decisive result first.  See rules.md.
  house-rule    Our no-capture draw (QUIET_LIMIT plies); Terrace as published
                has no such rule, so AbstractPlay simply plays on.
"""

from __future__ import annotations

import argparse
import json
import os
import random
import re
import subprocess
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[2]))
from agp.loader import load_from_dir  # noqa: E402

HERE = Path(__file__).resolve().parent

DRIVER = r'''// AUTO-GENERATED by engine/games/terrace/_diff_ap.py -- do not edit.
// Line-oriented JSON oracle driver for AbstractPlay's Terrace implementation.
import * as readline from "readline";
import { TerraceGame } from "./src/games/terrace";

let variants: string[] = [];
let g = new TerraceGame(undefined, variants);

function snapshot() {
    const moves: [string, string][] = [];
    for (const m of g.moves()) {
        const mm = /^([1-4])([a-h][1-8])([-x*])([a-h][1-8])$/.exec(m);
        if (mm === null) { throw new Error("unparsed move: " + m); }
        moves.push([mm[2], mm[4]]);
    }
    const board: [string, number, number, number][] =
        [...g.board.entries()].map(e =>
            [e[0], e[1].owner, e[1].size, e[1].royal ? 1 : 0] as
            [string, number, number, number]);
    board.sort();
    moves.sort();
    return {
        board,
        toMove: g.currplayer,
        moves,
        nmoves: g.moves().length,
        gameover: g.gameover,
        winner: [...g.winner],
        heightmap: g.heightmap,
        size: g.boardSize,
    };
}

const rl = readline.createInterface({ input: process.stdin });
rl.on("line", (line: string) => {
    line = line.trim();
    if (line.length === 0) { return; }
    const req = JSON.parse(line);
    try {
        if (req.cmd === "reset") {
            if (req.variants !== undefined) { variants = req.variants as string[]; }
            g = new TerraceGame(undefined, variants);
        }
        else if (req.cmd === "move") { g.move(req.m); }
        else if (req.cmd === "quit") { process.exit(0); }
        process.stdout.write(JSON.stringify({ ok: true, ...snapshot() }) + "\n");
    } catch (e) {
        process.stdout.write(JSON.stringify({ ok: false, error: (e as Error).message }) + "\n");
    }
});
'''

MOVE_RE = re.compile(r"^([1-4])([a-h][1-8])([-x*])([a-h][1-8])$")


class Oracle:
    def __init__(self, root: Path):
        (root / "terrace_oracle.ts").write_text(DRIVER)
        self.p = subprocess.Popen(
            ["npx", "ts-node", "--transpileOnly",
             "--compilerOptions", '{"module":"commonjs"}', "terrace_oracle.ts"],
            cwd=str(root), stdin=subprocess.PIPE, stdout=subprocess.PIPE, text=True)

    def send(self, **req) -> dict:
        self.p.stdin.write(json.dumps(req) + "\n")
        self.p.stdin.flush()
        line = self.p.stdout.readline()
        if not line:
            raise RuntimeError("oracle died")
        d = json.loads(line)
        if not d.get("ok"):
            raise RuntimeError("oracle error: " + d.get("error", "?"))
        return d

    def close(self):
        try:
            self.p.stdin.write('{"cmd":"quit"}\n')
            self.p.stdin.flush()
        except Exception:
            pass
        self.p.wait(timeout=10)


def alg(i: int, n: int) -> str:
    return f"{chr(ord('a') + i % n)}{i // n + 1}"


def unalg(a: str, n: int) -> str:
    """'c1' -> our cell id '2,0'."""
    return f"{ord(a[0]) - ord('a')},{int(a[1:]) - 1}"


def our_moves(g, s) -> set:
    """Our legal moves as a set of (from-alg, to-alg) pairs."""
    n = s.size
    out = set()
    for m in g.legal_moves(s):
        frm, to = m.split(">")
        fc, fr = (int(x) for x in frm.split(","))
        tc, tr = (int(x) for x in to.split(","))
        out.add((alg(fr * n + fc, n), alg(tr * n + tc, n)))
    return out


def our_board(s) -> list:
    n = s.size
    G = sys.modules[type(s).__module__]
    out = []
    for i, code in enumerate(s.board):
        if code:
            o, sz, roy = G.dec(code)
            out.append([alg(i, n), o + 1, sz, 1 if roy else 0])
    out.sort()
    return out


def variants_for(n: int, setup: str, capture: str) -> list:
    v = []
    if n == 8:
        v.append("board-8")
    if setup == "long":
        v.append("long")
    if capture == "rank":
        v.append("assassination")
    return v


def check_mapping(g, opts, orc, n):
    """Guard against a vacuous differential.  Always on: a systematically
    mirrored coordinate conversion would make both sides agree with each other
    about the wrong board and the whole run would pass for the wrong reason."""
    G = sys.modules[type(g).__module__]
    d = orc.send(cmd="reset", variants=variants_for(n, opts["setup"], opts["capture"]))
    assert d["size"] == n, (d["size"], n)

    # (1) the elevation table.  AP indexes heightmap[row][col] with row 0 = the
    # TOP rank, so heightmap[row][col] must equal our elevation(col, n-1-row).
    for row in range(n):
        for col in range(n):
            ours = G.elevation(col, n - 1 - row, n)
            assert d["heightmap"][row][col] == ours, (row, col, ours)

    # (2) the whole opening array, owner/size/royal.  This is the asymmetric
    # part: the board's geometry is invariant under transpose and under a
    # 180-degree turn, but the ARMY is not (seat 0's T sits on a1 in the long
    # setup, and the size pattern runs 1,1,2,2,3,3,4,4 west to east).
    s = g.initial_state(opts)
    assert our_board(s) == d["board"], (our_board(s)[:6], d["board"][:6])

    # (3) a hand-picked move that pins the DIAGONAL-DOWN capture direction and
    # the file/rank axes at once.
    if n == 8 and opts["setup"] == "long" and opts["capture"] == "standard":
        # b2 (a size-4 piece on level 2) cannibalises seat 0's own T on a1
        # (level 1, diagonally down) -- so seat 0 immediately loses.
        assert ("b2", "a1") in our_moves(g, s)
        d2 = orc.send(cmd="move", m="4b2*a1")
        s2 = g.apply_move(s, "1,1>0,0")
        assert our_board(s2) == d2["board"], (our_board(s2)[:6], d2["board"][:6])
        assert d2["gameover"] and d2["winner"] == [2], d2["winner"]
        assert g.is_terminal(s2) and g.returns(s2) == [-1.0, 1.0], g.returns(s2)
        # ...and a same-level slide that runs west then north along a terrace,
        # which no transposed mapping could reproduce.
        assert ("c1", "a3") in our_moves(g, s)
        assert "2,0>0,2" in g.legal_moves(s)
    print(f"coordinate mapping OK ({n}x{n} {opts['setup']}/{opts['capture']}): "
          "elevation table, full opening army and a diagonal-down "
          "self-capture all agree")
    orc.send(cmd="reset", variants=variants_for(n, opts["setup"], opts["capture"]))


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--games", type=int, default=200)
    ap.add_argument("--seed", type=int, default=1)
    ap.add_argument("--max-plies", type=int, default=400)
    ap.add_argument("--config", default="8/long/standard",
                    help="board/setup/capture, e.g. 6/short/rank")
    ap.add_argument("--gameslib", default=os.environ.get("AP_GAMESLIB", ""))
    args = ap.parse_args()
    if not args.gameslib:
        sys.exit("set AP_GAMESLIB (or --gameslib) to a gameslib checkout")

    parts = (args.config.split("/") + ["long", "standard"])[:3]
    n = int(parts[0])
    opts = {"board": n, "setup": parts[1], "capture": parts[2]}

    _man, g = load_from_dir(HERE)
    orc = Oracle(Path(args.gameslib))
    rng = random.Random(args.seed)
    positions = mismatches = plies_total = 0
    known = {"ap-eog-order": 0, "house-rule": 0}
    results = {"0": 0, "1": 0, "draw": 0}
    ap_variants = variants_for(n, opts["setup"], opts["capture"])

    try:
        check_mapping(g, opts, orc, n)
        for gi in range(args.games):
            s = g.initial_state(opts)
            d = orc.send(cmd="reset", variants=ap_variants)
            while True:
                positions += 1
                om, am = our_moves(g, s), {tuple(x) for x in d["moves"]}
                probs = []
                if len(am) != d["nmoves"]:
                    probs.append(f"AP emitted duplicate moves ({d['nmoves']} "
                                 f"-> {len(am)} distinct)")
                if our_board(s) != d["board"]:
                    probs.append(f"board: {our_board(s)} vs {d['board']}")
                if s.to_move + 1 != d["toMove"]:
                    probs.append(f"to move: {s.to_move + 1} vs {d['toMove']}")
                if g.is_terminal(s) != d["gameover"]:
                    # The two known, documented divergences.
                    if g.is_terminal(s) and not d["gameover"] and s.end == "quiet":
                        known["house-rule"] += 1
                        break
                    if (not g.is_terminal(s)) and d["gameover"] \
                            and d["winner"] == [1, 2]:
                        known["ap-eog-order"] += 1
                        break
                    probs.append(f"gameover: {g.is_terminal(s)} vs {d['gameover']}")
                elif om != am:
                    probs.append(f"moves: only-ours {sorted(om - am)} "
                                 f"only-AP {sorted(am - om)}")
                if g.is_terminal(s) and d["gameover"] and not probs:
                    r = g.returns(s)
                    win = {(1.0, -1.0): [1], (-1.0, 1.0): [2],
                           (0.0, 0.0): [1, 2]}[tuple(r)]
                    if win != d["winner"]:
                        # AP's draw-first end-of-game order, seen from the other
                        # side: it calls a decisive position a draw.
                        if d["winner"] == [1, 2] and win != [1, 2]:
                            known["ap-eog-order"] += 1
                            break
                        probs.append(f"winner: {win} vs {d['winner']} "
                                     f"(end={s.end})")
                if probs:
                    mismatches += 1
                    print(f"MISMATCH game {gi} ply {s.ply}: " + "; ".join(probs),
                          file=sys.stderr)
                    print("  ours:", json.dumps(g.serialize(s)), file=sys.stderr)
                    break
                if g.is_terminal(s):
                    r = g.returns(s)
                    results["0" if r[0] > 0 else "1" if r[1] > 0 else "draw"] += 1
                    break
                if s.ply >= args.max_plies:
                    break
                m = rng.choice(g.legal_moves(s))
                frm, to = m.split(">")
                fc, fr = (int(x) for x in frm.split(","))
                tc, tr = (int(x) for x in to.split(","))
                G = sys.modules[type(s).__module__]
                sz = G.size_of(s.board[fr * n + fc])
                victim = s.board[tr * n + tc]
                sep = "-" if not victim else (
                    "*" if G.owner_of(victim) == s.to_move else "x")
                d = orc.send(cmd="move",
                             m=f"{sz}{alg(fr * n + fc, n)}{sep}{alg(tr * n + tc, n)}")
                s = g.apply_move(s, m)
                plies_total += 1
            if (gi + 1) % 25 == 0:
                print(f"  {gi + 1} games, {positions} positions, "
                      f"{mismatches} mismatches", file=sys.stderr)
    finally:
        orc.close()

    print(f"config={args.config} games={args.games} positions={positions} "
          f"plies={plies_total} mismatches={mismatches} known={known} "
          f"results={results}")
    return 1 if mismatches else 0


if __name__ == "__main__":
    sys.exit(main())
