"""Starweb, by Christian Freeling (2017).

A connection / scoring game played on a "web" board: a hexagon-of-hexes of side
7 (a hexhex-7, 127 cells) with a triangular CHUNK of 15 cells grown outward from
the middle of each of the six sides, giving a six-fold-symmetric "cloud/flower"
of 217 cells. The shape has 18 special STAR cells (Freeling calls them
"corners"): 12 OUTWARD corners (the convex tips of the six bumps) and 6 INWARD
corners (the concave notches between adjacent bumps). Intrinsically, a star is
exactly a cell with 3 on-board neighbours (outward) or 5 (inward); every other
cell has 4 or 6.

PLAY.  Black and White alternately place one stone of their colour on any empty
cell. Stones never move and are never captured. A player may PASS without losing
the right to move next turn. The game ends when both players pass in succession
(or, as a hard safety net, when the board fills).

SCORING.  Like-coloured connected stones form a group. A group that contains n
stars is worth the "triangular" score Sigma(n) = n*(n+1)/2 = 1+2+...+n. So a
group with 1 star scores 1, with 2 stars 3, with 3 stars 6, with 4 stars 10, and
so on. A group with 0 stars scores nothing (but is still useful for cutting the
opponent's groups). A player's total is the sum over their groups.

WIN.  Highest total wins. Starweb is DRAWLESS: on an equal score the player who
placed the SECOND stone (player index 1, White here) wins. The pie / swap rule
(offered to the second player on their first turn via the action ``"swap"``)
balances the first move; it is enabled by the ``pie`` option (default on).

Coordinates are axial (q, r); the third cube coordinate is s = -q - r. Adjacency
is the six hex neighbours.

Source: https://mindsports.nl/index.php/arena/starweb/738-starweb-rules
The board geometry (217 cells, 18 stars) was reconstructed from the official
board diagram and verified cell-for-cell (see selftest.py).
"""

from __future__ import annotations

from dataclasses import dataclass, field
from functools import lru_cache
from typing import Optional

from agp.game import Game

BLACK, WHITE = 0, 1  # player 0 places first; player 1 placed the "second stone"

# The six axial hex directions.
_DIRS = [(1, 0), (-1, 0), (0, 1), (0, -1), (1, -1), (-1, 1)]


def _s(q: int, r: int) -> int:
    return -q - r


@lru_cache(maxsize=None)
def _cells() -> tuple:
    """All 217 on-board axial cells of the Starweb web.

    A hexhex-7 base (max(|q|,|r|,|s|) <= 6, 127 cells) plus six triangular chunks
    of 15 cells (rows of width 6, 5, 4 at distances 7, 8, 9 from centre), one per
    side, generated by 60-degree rotation of the +q chunk.
    """
    base = set()
    for q in range(-6, 7):
        for r in range(-6, 7):
            if max(abs(q), abs(r), abs(_s(q, r))) <= 6:
                base.add((q, r))

    # +q chunk: outward rows q = 7, 8, 9 with widths 6, 5, 4, anchored at r = -6.
    chunk = set()
    for k in (1, 2, 3):
        q = 6 + k
        width = 7 - k
        for r in range(-6, -6 + width):
            chunk.add((q, r))

    def rot(q, r):  # 60-degree rotation about the centre, in axial coords
        return (-r, q + r)

    add = set()
    cur = chunk
    for _ in range(6):
        add |= cur
        cur = {rot(q, r) for (q, r) in cur}

    return tuple(sorted(base | add))


@lru_cache(maxsize=None)
def _cell_set() -> frozenset:
    return frozenset(_cells())


@lru_cache(maxsize=None)
def _stars() -> frozenset:
    """The 18 star cells: those with exactly 3 (outward) or 5 (inward) on-board
    neighbours. Every non-star cell has 4 or 6 on-board neighbours."""
    on = _cell_set()
    out = set()
    for (q, r) in on:
        nb = sum(1 for dq, dr in _DIRS if (q + dq, r + dr) in on)
        if nb == 3 or nb == 5:
            out.add((q, r))
    return frozenset(out)


def _cell(t: str) -> tuple[int, int]:
    q, r = t.split(",")
    return int(q), int(r)


@dataclass
class StarwebState:
    board: dict = field(default_factory=dict)   # (q, r) -> 0/1
    to_move: int = BLACK
    passes: int = 0                              # consecutive passes
    ply: int = 0
    last: Optional[tuple] = None                 # last placed cell
    winner: Optional[int] = None                 # set at game end
    over: bool = False
    pie: bool = True


def _groups(board: dict, player: int) -> list[set]:
    """All connected components of ``player``'s stones."""
    out, seen = [], set()
    for cell, p in board.items():
        if p != player or cell in seen:
            continue
        comp, stack = {cell}, [cell]
        seen.add(cell)
        while stack:
            cq, cr = stack.pop()
            for dq, dr in _DIRS:
                nb = (cq + dq, cr + dr)
                if nb not in seen and board.get(nb) == player:
                    seen.add(nb)
                    comp.add(nb)
                    stack.append(nb)
        out.append(comp)
    return out


def _score(board: dict, player: int) -> int:
    """Sum over ``player``'s groups of the triangular value of the stars each
    group contains: Sigma(n) = n*(n+1)//2 for a group holding n stars."""
    stars = _stars()
    total = 0
    for g in _groups(board, player):
        n = len(g & stars)
        total += n * (n + 1) // 2
    return total


class Starweb(Game):
    uid = "starweb"
    name = "Starweb"

    @property
    def num_players(self) -> int:
        return 2

    def initial_state(self, options=None, rng=None) -> StarwebState:
        opts = options or {}
        pie = bool(opts.get("pie", True))
        return StarwebState(pie=pie)

    def current_player(self, s: StarwebState) -> int:
        return s.to_move

    def legal_moves(self, s: StarwebState) -> list[str]:
        if self.is_terminal(s):
            return []
        moves = [f"{q},{r}" for (q, r) in _cells() if (q, r) not in s.board]
        if s.pie and s.ply == 1:  # second player's first turn
            moves.append("swap")
        moves.append("pass")  # passing is always legal
        return moves

    def apply_move(self, s: StarwebState, move: str, rng=None) -> StarwebState:
        if self.is_terminal(s):
            raise ValueError("game over")
        mover = s.to_move

        if move == "swap":
            if not (s.pie and s.ply == 1):
                raise ValueError("swap not available")
            (cell, _), = list(s.board.items())
            return StarwebState(
                board={cell: mover}, to_move=1 - mover, passes=0,
                ply=s.ply + 1, last=cell, pie=s.pie,
            )

        if move == "pass":
            ns = StarwebState(
                board=dict(s.board), to_move=1 - mover, passes=s.passes + 1,
                ply=s.ply + 1, last=None, pie=s.pie,
            )
            self._maybe_finish(ns, force=(ns.passes >= 2))
            return ns

        cell = _cell(move)
        if cell not in _cell_set() or cell in s.board:
            raise ValueError(f"illegal move {move!r}")
        board = dict(s.board)
        board[cell] = mover
        ns = StarwebState(
            board=board, to_move=1 - mover, passes=0,
            ply=s.ply + 1, last=cell, pie=s.pie,
        )
        # Hard safety net: a full board also ends the game.
        self._maybe_finish(ns, force=(len(board) >= len(_cells())))
        return ns

    def _maybe_finish(self, ns: StarwebState, force: bool = False):
        if not force:
            return
        b = _score(ns.board, BLACK)
        w = _score(ns.board, WHITE)
        # Drawless: a tie goes to the player who placed the SECOND stone (WHITE).
        ns.winner = BLACK if b > w else WHITE
        ns.over = True

    def is_terminal(self, s: StarwebState) -> bool:
        return s.over

    def returns(self, s: StarwebState) -> list[float]:
        if s.winner == BLACK:
            return [1.0, -1.0]
        if s.winner == WHITE:
            return [-1.0, 1.0]
        return [0.0, 0.0]  # only before termination

    def serialize(self, s: StarwebState) -> dict:
        return {
            "board": {f"{q},{r}": p for (q, r), p in s.board.items()},
            "to_move": s.to_move,
            "passes": s.passes,
            "ply": s.ply,
            "last": (f"{s.last[0]},{s.last[1]}" if s.last is not None else None),
            "winner": s.winner,
            "over": s.over,
            "pie": s.pie,
        }

    def deserialize(self, d: dict) -> StarwebState:
        last = d.get("last")
        return StarwebState(
            board={_cell(k): v for k, v in d["board"].items()},
            to_move=d["to_move"],
            passes=d.get("passes", 0),
            ply=d.get("ply", len(d["board"])),
            last=(_cell(last) if last else None),
            winner=d.get("winner"),
            over=d.get("over", False),
            pie=d.get("pie", True),
        )

    def describe_move(self, s: StarwebState, move: str) -> str:
        if move == "swap":
            return "swap (pie)"
        if move == "pass":
            return "pass"
        cell = _cell(move)
        return f"{move}*" if cell in _stars() else move

    def render(self, s: StarwebState, perspective=None) -> dict:
        import math

        stars = _stars()
        rad = 0.58
        cells = []
        for (q, r) in _cells():
            cx = math.sqrt(3) * (q + r / 2.0)
            cy = 1.5 * r
            pts = [[round(cx + rad * math.cos(math.radians(60 * k + 30)), 3),
                    round(cy + rad * math.sin(math.radians(60 * k + 30)), 3)]
                   for k in range(6)]
            cells.append({"id": f"{q},{r}", "points": pts})

        # Tint the star cells so they stand out (a soft gold).
        tints = {f"{q},{r}": "#7a6a35" for (q, r) in stars}

        pieces = [
            {"cell": f"{q},{r}", "owner": p, "label": ""}
            for (q, r), p in s.board.items()
        ]

        highlights = []
        if s.last is not None:
            highlights.append({"cell": f"{s.last[0]},{s.last[1]}", "kind": "last-move"})

        names = {BLACK: "Black", WHITE: "White"}
        b = _score(s.board, BLACK)
        w = _score(s.board, WHITE)
        if s.over:
            caption = f"{names[s.winner]} wins — Black {b}, White {w}"
        else:
            caption = f"{names[s.to_move]} to move — Black {b}, White {w}"

        return {
            "board": {"type": "polygons", "cells": cells, "tints": tints},
            "pieces": pieces,
            "highlights": highlights,
            "caption": caption,
        }
