"""Chess with Different Armies (Ralph Betza, ~1996) -- a Recognized Chess Variant.

Standard 8x8 chess in every rule *except* that the two players may field
**different armies** of pieces.  The Kings and Pawns are always the orthodox
FIDE King and Pawn; each side's other six pieces come from one of four balanced,
equal-strength armies designed by Betza:

  * **The Fabulous FIDEs** -- the orthodox army (Rook, kNight, Bishop, Queen).
  * **The Colorbound Clobberers** -- a Bishop-themed army of colourbound pieces:
    Bede (BD), Waffle (WA), FAD (Ferz+Alfil+Dabbaba) and Cardinal (=Archbishop, NB).
  * **The Remarkable Rookies** -- an orthogonal army: Short Rook (R4), Woody Rook
    (WD), Half-Duck (Ferz+Dabbaba+threeleaper, HFD) and Chancellor (RN).
  * **The Nutty Knights** -- a Knight-themed army whose pieces move *differently
    forwards and backwards* (like the Pawn): Charging Rook, Fibnif, Charging
    Knight and Colonel.

Piece movement, army rosters, promotion and the special colourbound-castling
rule are transcribed from Betza's own page (with the exact Betza notation stored
in the interactive-diagram setup there):
    https://www.chessvariants.com/unequal.dir/cwda.html

Built on the shared chess-like core (``agp.chesslike``).  The four Nutty-Knights
pieces are forward/backward asymmetric, so their move geometry depends on the
owner's colour; those (and the range-limited Short Rook) are generated by the
custom hooks below, exactly as ``grand_acedrex`` does for its compound pieces.
White = player 0 (advances toward higher rows).  See ``rules.md``.
"""

from __future__ import annotations

from dataclasses import dataclass, field

from agp.chesslike import (
    ChessLike, CState, StandardPawn, PromotionRules, Castling,
    ORTHO, DIAG, ALL8, KNIGHT, WHITE, BLACK,
)

# --------------------------------------------------------------------------- #
# Movement atoms (offset lists).
# --------------------------------------------------------------------------- #
FERZ = list(DIAG)                                          # (±1,±1)
WAZIR = list(ORTHO)                                        # (±1,0),(0,±1)
ALFIL = [(2, 2), (2, -2), (-2, 2), (-2, -2)]              # (±2,±2) leap
DABBABA = [(2, 0), (-2, 0), (0, 2), (0, -2)]              # (±2,0),(0,±2) leap
THREELEAPER = [(3, 0), (-3, 0), (0, 3), (0, -3)]         # (±3,0),(0,±3) leap ("H")
VN = [(1, 2), (-1, 2), (1, -2), (-1, -2)]                 # vertical-narrow knight

# --------------------------------------------------------------------------- #
# Army rosters.  Back-rank layout files a..h = columns 0..7; kings always on the
# e-file (column 4).  Letters are DISTINCT per piece type across all armies (the
# PIECES table is their union).  Standard R/N/B/Q keep the chess glyphs.
# --------------------------------------------------------------------------- #
#   Bede D  Waffle W  FAD F  Cardinal A  |  ShortRook S  Woody O  HalfDuck H
#   Chancellor M  |  ChargingRook G  Fibnif I  ChargingKnight J  Colonel C
ROSTERS = {
    "fide":       ["R", "N", "B", "Q", "K", "B", "N", "R"],
    "clobberers": ["D", "W", "F", "A", "K", "F", "W", "D"],
    "rookies":    ["S", "O", "H", "M", "K", "H", "O", "S"],
    "knights":    ["G", "I", "J", "C", "K", "J", "I", "G"],
}
# Promotion targets each army contributes, strongest-first (queen-square piece
# first).  A promoted Pawn may become "any kind of piece that was in either army
# at the start of the game" (Betza) -- i.e. the union of the two chosen rosters.
PROMO_ORDER = {
    "fide":       ["Q", "R", "B", "N"],
    "clobberers": ["A", "D", "F", "W"],
    "rookies":    ["M", "S", "H", "O"],
    "knights":    ["C", "G", "J", "I"],
}
ARMY_NAMES = {
    "fide": "Fabulous FIDEs",
    "clobberers": "Colorbound Clobberers",
    "rookies": "Remarkable Rookies",
    "knights": "Nutty Knights",
}
PIECE_NAMES = {
    "K": "King", "P": "Pawn", "Q": "Queen", "R": "Rook", "B": "Bishop", "N": "Knight",
    "D": "Bede", "W": "Waffle", "F": "FAD", "A": "Cardinal",
    "S": "Short Rook", "O": "Woody Rook", "H": "Half-Duck", "M": "Chancellor",
    "G": "Charging Rook", "I": "Fibnif", "J": "Charging Knight", "C": "Colonel",
}

# The four pieces whose geometry is direction-dependent (Nutty Knights) or
# range-limited (Short Rook) and so is generated by the custom hooks.
CUSTOM = frozenset({"S", "G", "J", "C"})
# Colourbound corner pieces trigger the special queenside castling (Bede only).
COLORBOUND = frozenset({"D"})


@dataclass
class CwdaState(CState):
    white_army: str = "fide"
    black_army: str = "clobberers"
    promo_targets: tuple = ()


# --------------------------------------------------------------------------- #
# Promotion: to any piece of either army chosen at the start of THIS game.
# --------------------------------------------------------------------------- #
class ArmyPromotion(PromotionRules):
    def options(self, core, state, frm, to):
        pl = state.board[frm][0]
        last = (to[1] == core.HEIGHT - 1 and pl == WHITE) or (to[1] == 0 and pl == BLACK)
        if not last:
            return [None]
        targets = getattr(state, "promo_targets", None) or ("Q", "R", "B", "N")
        return list(targets)

    def safety_piece(self) -> str:
        return "Q"     # a strong over-approximation for king-safety probing


# --------------------------------------------------------------------------- #
# Castling: the normal king patterns, but when the queenside (a-file) corner
# piece is COLOURBOUND the king goes THREE squares (to b1/b8) and the corner
# piece hops over it to c1/c8 (Betza; "castleFlip", not optional).
# --------------------------------------------------------------------------- #
class CwdaCastling(Castling):
    ROOK_HOME = {(7, 0): "K", (0, 0): "Q", (7, 7): "k", (0, 7): "q"}
    KING_HOME = {(4, 0): WHITE, (4, 7): BLACK}
    BY_COLOR = {WHITE: ("K", "Q"), BLACK: ("k", "q")}

    def initial_rights(self) -> frozenset:
        return frozenset("KQkq")

    def moves(self, core, state):
        player = state.to_move
        enemy = 1 - player
        board = state.board
        if core.in_check(board, player):
            return
        row = 0 if player == WHITE else 7
        king_sq = (4, row)
        if board.get(king_sq) != (player, "K"):
            return
        ks, qs = self.BY_COLOR[player]

        def path_safe(cells):
            return not any(core.attacked(board, c, r, enemy) for (c, r) in cells)

        # Kingside: king e->g (2 squares), corner h->f.  Empties f,g.
        if ks in state.castling:
            occ = board.get((7, row))
            if occ is not None and occ[0] == player:
                if all(sq not in board for sq in [(5, row), (6, row)]):
                    if path_safe([(4, row), (5, row), (6, row)]):
                        yield king_sq, (6, row)

        # Queenside: empties b,c,d.  Standard = king e->c (2); colourbound corner
        # = king e->b (3) with the corner hopping to c.
        if qs in state.castling:
            occ = board.get((0, row))
            if occ is not None and occ[0] == player:
                if all(sq not in board for sq in [(1, row), (2, row), (3, row)]):
                    if occ[1] in COLORBOUND:
                        if path_safe([(4, row), (3, row), (2, row), (1, row)]):
                            yield king_sq, (1, row)
                    else:
                        if path_safe([(4, row), (3, row), (2, row)]):
                            yield king_sq, (2, row)

    def rook_move(self, frm, to, player):
        row = 0 if player == WHITE else 7
        if frm != (4, row):
            return None
        d = to[0] - frm[0]
        if d == 2:                     # kingside: corner h -> f
            return (7, row), (5, row)
        if d == -2:                    # queenside standard: corner a -> d
            return (0, row), (3, row)
        if d == -3:                    # queenside colourbound flip: corner a -> c
            return (0, row), (2, row)
        return None

    def update_rights(self, rights, frm, to, board):
        rights = set(rights)
        pl, t = board[frm]
        if t == "K" and frm in self.KING_HOME:
            rights -= set(self.BY_COLOR[pl])
        if frm in self.ROOK_HOME:
            rights.discard(self.ROOK_HOME[frm])
        if to in self.ROOK_HOME:                 # a corner piece captured at home
            rights.discard(self.ROOK_HOME[to])
        return frozenset(rights)


# --------------------------------------------------------------------------- #
# The game.
# --------------------------------------------------------------------------- #
class Cwda(ChessLike):
    uid = "cwda"
    name = "Chess with Different Armies"

    WIDTH = HEIGHT = 8
    PLY_CAP = 600
    PIECESET = "chess"

    # Union of all four armies' pieces.  The simple pieces carry their real
    # (slides, leaps); the direction-dependent / range-limited CUSTOM pieces get
    # an empty entry and are supplied by the custom hooks below.
    PIECES = {
        # --- FIDEs / royalty ---
        "R": (ORTHO, []), "N": ([], KNIGHT), "B": (DIAG, []), "Q": (ALL8, []),
        "K": ([], ALL8),
        # --- Clobberers ---
        "D": (DIAG, DABBABA),                       # Bede   = Bishop + Dabbaba
        "W": ([], WAZIR + ALFIL),                   # Waffle = Wazir + Alfil
        "F": ([], FERZ + ALFIL + DABBABA),          # FAD    = Ferz + Alfil + Dabbaba
        "A": (DIAG, KNIGHT),                        # Cardinal = Archbishop (B+N)
        # --- Rookies ---
        "O": ([], WAZIR + DABBABA),                 # Woody Rook = Wazir + Dabbaba
        "H": ([], FERZ + DABBABA + THREELEAPER),    # Half-Duck  = F + D + threeleaper
        "M": (ORTHO, KNIGHT),                       # Chancellor = Rook + Knight
        # "S" Short Rook (R4)  -> custom (range-limited slider)
        "S": ([], []),
        # --- Nutty Knights (direction-dependent) -> custom ---
        "I": ([], VN + FERZ),                       # Fibnif = (vertical-narrow N) + Ferz (symmetric)
        "G": ([], []),                              # Charging Rook
        "J": ([], []),                              # Charging Knight
        "C": ([], []),                              # Colonel
    }
    # Everything except the lone king and the chess minors (B/N) counts as mating
    # material; B/N keep the orthodox lone-minor draw handling in the base class.
    HEAVY = ("P", "R", "Q", "D", "W", "F", "A", "S", "O", "H", "M", "G", "I", "J", "C")
    # Cardinal derives to the Archbishop image and Chancellor to the Chancellor
    # image automatically; pin them explicitly for clarity.  All other fairy
    # pieces have no dedicated glyph and render as their letter (see rules.md).
    ICONS = {"A": "archbishop", "M": "chancellor"}

    PAWN = StandardPawn(white_start=1, black_start=6)
    PROMOTION = ArmyPromotion()
    CASTLING = CwdaCastling()

    # ---- direction-dependent / range-limited geometry ----------------------
    def _custom_geometry(self, t, player):
        """Return (slides, leaps) for a CUSTOM piece ``t`` owned by ``player``.

        ``slides`` = list of (dc, dr, max_range) blocked rays; ``leaps`` = list
        of (dc, dr) jumps.  ``f`` = the forward direction (+1 White, -1 Black)."""
        f = 1 if player == WHITE else -1
        if t == "S":                                   # Short Rook = R4
            return [(dc, dr, 4) for (dc, dr) in ORTHO], []
        if t == "G":                                   # Charging Rook: fsR + bW + bF
            slides = [(0, f, 8), (1, 0, 8), (-1, 0, 8)]         # forward + sideways rook
            leaps = [(0, -f), (1, -f), (-1, -f)]               # king backwards
            return slides, leaps
        if t == "J":                                   # Charging Knight: fhN + bsW + bF
            leaps = [(1, 2 * f), (-1, 2 * f), (2, f), (-2, f),   # four forward knight moves
                     (0, -f), (1, 0), (-1, 0),                   # backward + sideways wazir
                     (1, -f), (-1, -f)]                          # backward ferz
            return [], leaps
        if t == "C":                                   # Colonel: fsR + fhN + bW + F
            slides = [(0, f, 8), (1, 0, 8), (-1, 0, 8)]         # forward + sideways rook
            leaps = [(1, 2 * f), (-1, 2 * f), (2, f), (-2, f),   # four forward knight moves
                     (0, -f),                                    # backward wazir
                     (1, 1), (1, -1), (-1, 1), (-1, -1)]         # ferz (all diagonals)
            return slides, leaps
        return [], []

    def _custom_targets(self, board, c, r, player, t):
        """Yield every destination cell for a CUSTOM piece of ``player`` at (c, r)."""
        slides, leaps = self._custom_geometry(t, player)
        for dc, dr in leaps:
            tc, tr = c + dc, r + dr
            if self.on(tc, tr):
                occ = board.get((tc, tr))
                if occ is None or occ[0] != player:
                    yield (tc, tr)
        for dc, dr, rng in slides:
            cc, rr = c + dc, r + dr
            steps = 1
            while self.on(cc, rr) and steps <= rng:
                occ = board.get((cc, rr))
                if occ is None:
                    yield (cc, rr)
                else:
                    if occ[0] != player:
                        yield (cc, rr)
                    break
                cc += dc
                rr += dr
                steps += 1

    # ---- attacks (add the custom pieces) -----------------------------------
    def attacked(self, board, c, r, by) -> bool:
        if super().attacked(board, c, r, by):
            return True
        for (ac, ar), (pl, t) in board.items():
            if pl != by or t not in CUSTOM:
                continue
            if (c, r) in self._custom_targets(board, ac, ar, by, t):
                return True
        return False

    # ---- move generation (add the custom pieces) ---------------------------
    def _pseudo(self, state):
        yield from super()._pseudo(state)
        board, player = state.board, state.to_move
        for (c, r), (pl, t) in list(board.items()):
            if pl != player or t not in CUSTOM:
                continue
            for to in self._custom_targets(board, c, r, player, t):
                yield (c, r), to

    # ---- setup / state ------------------------------------------------------
    def _build_board(self, white_army: str, black_army: str) -> dict:
        wr, br = ROSTERS[white_army], ROSTERS[black_army]
        b = {}
        for c in range(8):
            b[(c, 0)] = (WHITE, wr[c])
            b[(c, 1)] = (WHITE, "P")
            b[(c, 6)] = (BLACK, "P")
            b[(c, 7)] = (BLACK, br[c])
        return b

    def _promo_targets(self, white_army: str, black_army: str) -> tuple:
        out = []
        for army in (white_army, black_army):
            for L in PROMO_ORDER[army]:
                if L not in out:
                    out.append(L)
        return tuple(out)

    def setup_board(self) -> dict:
        # Only used if someone calls the base initial_state; the real setup is in
        # initial_state below, which honours the army options.
        return self._build_board("fide", "clobberers")

    def initial_state(self, options=None, rng=None):
        o = options or {}
        wa = o.get("white_army", "fide")
        ba = o.get("black_army", "clobberers")
        if wa not in ROSTERS:
            wa = "fide"
        if ba not in ROSTERS:
            ba = "clobberers"
        board = self._build_board(wa, ba)
        rights = self.CASTLING.initial_rights()
        st = CwdaState(board=board, to_move=WHITE, castling=rights, ep=None,
                       white_army=wa, black_army=ba,
                       promo_targets=self._promo_targets(wa, ba))
        st.reps = {self._poskey_state(st): 1}
        return st

    def apply_move(self, state, move, rng=None):
        ns = super().apply_move(state, move, rng)
        return CwdaState(
            board=ns.board, to_move=ns.to_move, castling=ns.castling, ep=ns.ep,
            halfmove=ns.halfmove, ply=ns.ply, reps=ns.reps,
            white_army=getattr(state, "white_army", "fide"),
            black_army=getattr(state, "black_army", "clobberers"),
            promo_targets=getattr(state, "promo_targets", ()),
        )

    # ---- insufficient material ---------------------------------------------
    # The base handling (bare kings, lone minor, opposite-colour bishops) is
    # correct: fairy pieces are all HEAVY, so any of them present plays on and
    # the ply cap guarantees termination.

    # ---- (de)serialize ------------------------------------------------------
    def serialize(self, state) -> dict:
        d = super().serialize(state)
        d["white_army"] = getattr(state, "white_army", "fide")
        d["black_army"] = getattr(state, "black_army", "clobberers")
        d["promo_targets"] = list(getattr(state, "promo_targets", ()))
        return d

    def deserialize(self, d: dict):
        base = super().deserialize(d)
        return CwdaState(
            board=base.board, to_move=base.to_move, castling=base.castling,
            ep=base.ep, halfmove=base.halfmove, ply=base.ply, reps=base.reps,
            white_army=d.get("white_army", "fide"),
            black_army=d.get("black_army", "clobberers"),
            promo_targets=tuple(d.get("promo_targets", ())),
        )

    # ---- presentation -------------------------------------------------------
    def render(self, state, perspective=None) -> dict:
        spec = super().render(state, perspective)
        spec["choiceNames"] = dict(PIECE_NAMES)
        wa = getattr(state, "white_army", "fide")
        ba = getattr(state, "black_army", "clobberers")
        spec["caption"] = (f"{spec['caption']}  —  White: {ARMY_NAMES[wa]}"
                           f" vs Black: {ARMY_NAMES[ba]}")
        return spec
