#!/usr/bin/env python3
"""Differential harness: this package vs. the AbstractPlay `gameslib` oracle.

MANUAL / ONE-TIME -- this is NOT part of the test suite (it needs node + a
checkout of https://github.com/AbstractPlay/gameslib, which is MIT-licensed and
used here purely as a rule-enforcing oracle; no code from it was copied).

Usage:
    AP_GAMESLIB=/path/to/gameslib python3 _diff_ap.py --games 300 --seed 1

It writes a small TypeScript driver (`taiji_oracle.ts`) into the gameslib
checkout, runs it under ts-node as a line-oriented JSON co-process, and plays
random games in LOCKSTEP through both implementations, for every
(board size x scoring type) combination.  At **every** ply it compares:

  * the SET of legal (light-cell, dark-cell) pairs, in our coordinates
    (never raw move strings) -- both orientations of every domino,
  * the full board (which square holds which COLOUR),
  * the side to move,
  * both scores,
  * terminality and the winner.

The oracle's `moves()` list is additionally filtered through the oracle's own
`validateMove()` and the two are compared, because in wave 13 another gameslib
game (`manalath.ts`) was found to over-report in `moves()`.

Winner comparison uses our ``tie: "draw"`` option, which is AbstractPlay's
reading of an equal score.  Our DEFAULT is the designer's published tie-break
("In case of a tie, the 'Dark' player wins" -- TAIJI_EN.pdf), and the harness
checks at every terminal that the two options differ **only** when the scores
are exactly equal.

Coordinate mapping (verified on every run, see ``check_mapping``): AbstractPlay
names cells `a1`..`i9` via `coords2algebraic(x, y, size) = letter(x) +
(size - y)` with y counted from the TOP; we use `"c,r"` with c = file - 'a'
and r = rank - 1 (row 0 at the bottom).  The check is STRUCTURAL -- it asks the
oracle for its own name of every (x, y) and compares against our formula for
all size^2 cells -- because Taiji's board and rules are fully symmetric under
the dihedral group, so a mirrored mapping would be behaviourally undetectable
and a purely gameplay-based check would be vacuous.
"""

from __future__ import annotations

import argparse
import dataclasses
import json
import os
import random
import subprocess
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[2]))
from agp.loader import load_from_dir  # noqa: E402

HERE = Path(__file__).resolve().parent

DRIVER = r'''// AUTO-GENERATED by engine/games/taiji/_diff_ap.py -- do not edit.
// Line-oriented JSON oracle driver for AbstractPlay's Taiji implementation.
import * as readline from "readline";
import { TaijiGame } from "./src/games/taiji";

let g = new TaijiGame();

// AP cell name -> our "c,r" (row 0 at the BOTTOM).
function toId(cell: string): string {
    const [x, y] = TaijiGame.algebraic2coords(cell, g.boardSize);
    return `${x},${g.boardSize - 1 - y}`;
}

function snapshot() {
    const raw = g.moves();
    const valid: string[] = [];
    for (const m of raw) {
        const r = g.validateMove(m);
        if (r.valid && r.complete === 1) { valid.push(m); }
    }
    const pairs = valid.map(m => {
        const [light, dark] = m.split(",");
        return [toId(light), toId(dark)];
    });
    pairs.sort();
    const board: [string, number][] =
        [...g.board.entries()].map(e => [toId(e[0]), e[1]] as [string, number]);
    board.sort();
    return {
        moves: pairs,
        nRaw: raw.length,
        nValid: valid.length,
        board,
        toMove: g.currplayer,
        gameover: g.gameover,
        winner: [...g.winner],
        scores: [g.getPlayerScore(1), g.getPlayerScore(2)],
        size: g.boardSize,
    };
}

// The oracle's own name for every (col, row-from-top) -- used to prove the
// coordinate mapping instead of assuming it.
function names() {
    const out: string[][] = [];
    for (let y = 0; y < g.boardSize; y++) {
        const row: string[] = [];
        for (let x = 0; x < g.boardSize; x++) {
            row.push(TaijiGame.coords2algebraic(x, y, g.boardSize));
        }
        out.push(row);
    }
    return out;
}

const rl = readline.createInterface({ input: process.stdin });
rl.on("line", (line: string) => {
    line = line.trim();
    if (line.length === 0) { return; }
    const req = JSON.parse(line);
    try {
        if (req.cmd === "reset") { g = new TaijiGame(undefined, req.variants); }
        else if (req.cmd === "move") { g.move(req.m); }
        else if (req.cmd === "names") {
            process.stdout.write(JSON.stringify({ ok: true, names: names(),
                                                  size: g.boardSize }) + "\n");
            return;
        }
        else if (req.cmd === "quit") { process.exit(0); }
        process.stdout.write(JSON.stringify({ ok: true, ...snapshot() }) + "\n");
    } catch (e) {
        process.stdout.write(JSON.stringify({ ok: false, error: (e as Error).message }) + "\n");
    }
});
'''


class Oracle:
    def __init__(self, root: Path):
        (root / "taiji_oracle.ts").write_text(DRIVER)
        self.p = subprocess.Popen(
            ["npx", "ts-node", "--transpileOnly",
             "--compilerOptions", '{"module":"commonjs"}', "taiji_oracle.ts"],
            cwd=str(root), stdin=subprocess.PIPE, stdout=subprocess.PIPE, text=True)

    def send(self, **req) -> dict:
        self.p.stdin.write(json.dumps(req) + "\n")
        self.p.stdin.flush()
        line = self.p.stdout.readline()
        if not line:
            raise RuntimeError("oracle died")
        d = json.loads(line)
        if not d.get("ok"):
            raise RuntimeError("oracle error: " + d.get("error", "?"))
        return d

    def close(self):
        try:
            self.p.stdin.write('{"cmd":"quit"}\n')
            self.p.stdin.flush()
        except Exception:
            pass
        self.p.wait(timeout=10)


# (our options, AP variants, human label)
CONFIGS = [
    ({"size": 9, "groups": 2}, [], "9x9 / 2 groups (default)"),
    ({"size": 9, "groups": 1}, ["onegroup"], "9x9 / 1 group"),
    ({"size": 9, "groups": 3}, ["threegroups"], "9x9 / 3 groups"),
    ({"size": 7, "groups": 1}, ["7x7", "onegroup"], "7x7 / 1 group"),
    ({"size": 7, "groups": 2}, ["7x7"], "7x7 / 2 groups"),
    ({"size": 11, "groups": 3}, ["11x11", "threegroups"], "11x11 / 3 groups"),
    ({"size": 11, "groups": 2}, ["11x11"], "11x11 / 2 groups"),
]


def check_mapping(M, orc, size):
    """Prove the coordinate conversion instead of assuming it.

    Taiji is symmetric under every board symmetry, so a mirrored mapping would
    pass a gameplay-only differential vacuously.  Compare the oracle's OWN name
    for each (x, y) against ours, cell by cell."""
    d = orc.send(cmd="names")
    assert d["size"] == size, (d["size"], size)
    seen = set()
    for y, row in enumerate(d["names"]):
        for x, ap in enumerate(row):
            ours = M.cell_name(size, M._idx(size, x, size - 1 - y))
            assert ours == ap, f"({x},{y}): AP {ap} != ours {ours}"
            seen.add(ap)
    assert len(seen) == size * size, "AP names are not distinct"
    print(f"  coordinate mapping OK on all {size * size} cells "
          f"(AP a1 == our 0,0 bottom-left; AP {d['names'][0][0]} == our 0,{size - 1})")


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--games", type=int, default=100,
                    help="random games PER configuration")
    ap.add_argument("--seed", type=int, default=1)
    ap.add_argument("--gameslib", default=os.environ.get("AP_GAMESLIB", ""))
    args = ap.parse_args()
    if not args.gameslib:
        sys.exit("set AP_GAMESLIB (or --gameslib) to a gameslib checkout")

    _man, g = load_from_dir(HERE)
    M = sys.modules[type(g).__module__]
    orc = Oracle(Path(args.gameslib))
    rng = random.Random(args.seed)
    total_pos = total_mm = total_plies = 0
    raw_vs_valid = 0
    results = {"light": 0, "dark": 0, "tie": 0}

    try:
        for opts, variants, label in CONFIGS:
            print(f"== {label} ==")
            size = opts["size"]
            orc.send(cmd="reset", variants=variants)
            check_mapping(M, orc, size)
            positions = mismatches = 0
            for gi in range(args.games):
                # AbstractPlay calls an equal score a draw; our DEFAULT is the
                # rulebook's "Dark wins ties".  Compare on the draw reading and
                # cross-check the official one at every terminal.
                s = g.initial_state(options={**opts, "tie": "draw"})
                d = orc.send(cmd="reset", variants=variants)
                while True:
                    positions += 1
                    ours = sorted(tuple(m.split(">")) for m in g.legal_moves(s))
                    theirs = sorted(tuple(p) for p in d["moves"])
                    ob = {M.cell_id(size, i): v + 1
                          for i, v in enumerate(s.board) if v != M.EMPTY}
                    probs = []
                    if d["nRaw"] != d["nValid"]:
                        raw_vs_valid += 1
                        probs.append(f"oracle moves() over-reports: "
                                     f"{d['nRaw']} raw vs {d['nValid']} validated")
                    if ours != theirs:
                        so, st = set(ours), set(theirs)
                        probs.append(f"moves: only-ours {sorted(so - st)[:6]} "
                                     f"only-AP {sorted(st - so)[:6]}")
                    if ob != dict(d["board"]):
                        probs.append(f"board: {ob} vs {dict(d['board'])}")
                    if s.to_move + 1 != d["toMove"]:
                        probs.append(f"to move: {s.to_move + 1} vs {d['toMove']}")
                    if list(g.scores(s)) != d["scores"]:
                        probs.append(f"scores: {g.scores(s)} vs {d['scores']}")
                    if g.is_terminal(s) != d["gameover"]:
                        probs.append(f"gameover: {g.is_terminal(s)} vs {d['gameover']}")
                    if g.is_terminal(s):
                        r = g.returns(s)
                        win = {(1.0, -1.0): [1], (-1.0, 1.0): [2],
                               (0.0, 0.0): [1, 2]}[tuple(r)]
                        if win != d["winner"]:
                            probs.append(f"winner: {win} vs {d['winner']}")
                        # the official tie-break: identical unless tied
                        off = g.returns(dataclasses.replace(s, tie="dark"))
                        lt, dk = g.scores(s)
                        want = [-1.0, 1.0] if lt == dk else r
                        if off != want:
                            probs.append(f"official tie-break: {off} != {want}")
                    if probs:
                        mismatches += 1
                        print(f"MISMATCH [{label}] game {gi}: " + "; ".join(probs),
                              file=sys.stderr)
                        print("  our board:", ob, file=sys.stderr)
                        break
                    if g.is_terminal(s):
                        lt, dk = g.scores(s)
                        results["light" if lt > dk else "dark" if dk > lt else "tie"] += 1
                        break
                    m = rng.choice(g.legal_moves(s))
                    a, b = m.split(">")
                    ac = M.parse_cell(size, a)
                    bc = M.parse_cell(size, b)
                    d = orc.send(cmd="move",
                                 m=f"{M.cell_name(size, ac)},{M.cell_name(size, bc)}")
                    s = g.apply_move(s, m)
                    total_plies += 1
            print(f"  {args.games} games, {positions} positions, "
                  f"{mismatches} mismatches")
            total_pos += positions
            total_mm += mismatches
    finally:
        orc.close()

    n = sum(results.values())
    print(f"TOTAL positions={total_pos} plies={total_plies} mismatches={total_mm} "
          f"oracle-moves()-over-reports={raw_vs_valid}")
    print(f"random-game results (light/dark/tie): {results} "
          f"tie rate = {results['tie'] / max(n, 1):.3%}")
    return 1 if total_mm else 0


if __name__ == "__main__":
    sys.exit(main())
