#!/usr/bin/env python3
"""Differential harness: this package vs. the AbstractPlay `gameslib` oracle.

MANUAL / ONE-TIME — this is NOT part of the test suite (it needs node + a
checkout of https://github.com/AbstractPlay/gameslib, which is MIT-licensed and
used here purely as a rule-enforcing oracle; no code from it was copied).

Usage:
    AP_GAMESLIB=/path/to/gameslib python3 _diff_ap.py --games 300 --seed 1

It writes a small TypeScript driver (`fendo_oracle.ts`) into the gameslib
checkout, runs it under ts-node as a line-oriented JSON co-process, and plays
random games in LOCKSTEP through both implementations.  At **every** ply it
compares, in a coordinate system it converts explicitly:

  * the set of legal *entry* cells (stock drops),
  * the set of legal (from, to, fence-side) triples,
  * whether "pass" is the only option,
  * the piece placement, the stock counts, the side to move,
  * the full fence set,
  * the area partition (open / closed / empty),
  * terminality, both scores and the winner.

Coordinate mapping (verified on every run, see ``check_mapping``): AbstractPlay uses algebraic
`a1`..`g7` on a 7x7 board; we use `"c,r"` with c = file - 'a' (0..6) and
r = rank - 1 (0..6, increasing north).  AP compass sides N/E/S/W agree with ours
(N = +r).
"""

from __future__ import annotations

import argparse
import json
import os
import random
import subprocess
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[2]))
from agp.loader import load_from_dir  # noqa: E402

HERE = Path(__file__).resolve().parent

DRIVER = r'''// AUTO-GENERATED by engine/games/fendo/_diff_ap.py -- do not edit.
// Line-oriented JSON oracle driver for AbstractPlay's Fendo implementation.
import * as readline from "readline";
import { FendoGame } from "./src/games/fendo";

function toId(cell: string): string {
    const c = cell.charCodeAt(0) - 97;
    const r = parseInt(cell.slice(1), 10) - 1;
    return `${c},${r}`;
}

let g = new FendoGame();

function areasInfo() {
    const a = g.getAreas();
    const f = (lst: Set<string>[]) => lst.map(s => [...s].map(toId).sort())
        .sort((x, y) => x.join("|") < y.join("|") ? -1 : 1);
    return { open: f(a.open), closed: f(a.closed), empty: f(a.empty) };
}

function snapshot() {
    const entries: string[] = [];
    const fenceMoves: [string, string, string][] = [];
    let canPass = false;
    for (const m of g.moves()) {
        if (m === "pass") { canPass = true; continue; }
        const mm = /^([a-g][1-7])(?:-([a-g][1-7]))?([NESW])$/.exec(m);
        if (mm === null) {
            if (/^[a-g][1-7]$/.test(m)) { entries.push(toId(m)); continue; }
            throw new Error("unparsed move: " + m);
        }
        const from = mm[1];
        const to = mm[2] === undefined ? from : mm[2];
        fenceMoves.push([toId(from), toId(to), mm[3]]);
    }
    const board: [string, number][] =
        [...g.board.entries()].map(e => [toId(e[0]), e[1]] as [string, number]);
    board.sort();
    entries.sort();
    fenceMoves.sort();
    return {
        board,
        stock: [...g.pieces],
        toMove: g.currplayer,
        fences: g.fences.map(p => [toId(p[0]), toId(p[1])].sort()).sort(),
        entries,
        fenceMoves,
        canPass,
        gameover: g.gameover,
        winner: [...g.winner],
        scores: [g.getPlayerScore(1), g.getPlayerScore(2)],
        areas: areasInfo(),
    };
}

const rl = readline.createInterface({ input: process.stdin });
rl.on("line", (line: string) => {
    line = line.trim();
    if (line.length === 0) { return; }
    const req = JSON.parse(line);
    try {
        if (req.cmd === "reset") { g = new FendoGame(); }
        else if (req.cmd === "move") { g.move(req.m); }
        else if (req.cmd === "quit") { process.exit(0); }
        process.stdout.write(JSON.stringify({ ok: true, ...snapshot() }) + "\n");
    } catch (e) {
        process.stdout.write(JSON.stringify({ ok: false, error: (e as Error).message }) + "\n");
    }
});
'''

SIZE = 7


def alg(cid: str) -> str:
    c, r = (int(x) for x in cid.split(","))
    return f"{chr(ord('a') + c)}{r + 1}"


class Oracle:
    def __init__(self, root: Path):
        (root / "fendo_oracle.ts").write_text(DRIVER)
        self.p = subprocess.Popen(
            ["npx", "ts-node", "--transpileOnly",
             "--compilerOptions", '{"module":"commonjs"}', "fendo_oracle.ts"],
            cwd=str(root), stdin=subprocess.PIPE, stdout=subprocess.PIPE, text=True)

    def send(self, **req) -> dict:
        self.p.stdin.write(json.dumps(req) + "\n")
        self.p.stdin.flush()
        line = self.p.stdout.readline()
        if not line:
            raise RuntimeError("oracle died")
        d = json.loads(line)
        if not d.get("ok"):
            raise RuntimeError("oracle error: " + d.get("error", "?"))
        return d

    def close(self):
        try:
            self.p.stdin.write('{"cmd":"quit"}\n')
            self.p.stdin.flush()
        except Exception:
            pass
        self.p.wait(timeout=10)


def ours(g, s):
    """Normalise our legal move list into oracle-comparable sets."""
    entries, fences, can_pass = set(), set(), False
    for m in g.legal_moves(s):
        if m == "pass":
            can_pass = True
        elif m.startswith("P@"):
            entries.add(m[2:])
        else:
            path, _, ch = m.partition("=")
            d = ch[len("FENCE_"):]
            frm, to = path.split(">")     # always two cells; frm == to = stay put
            fences.add((frm, to, d))
    return entries, fences, can_pass


def to_ap(m: str) -> str:
    if m == "pass":
        return "pass"
    if m.startswith("P@"):
        return alg(m[2:])
    path, _, ch = m.partition("=")
    d = ch[len("FENCE_"):]
    frm, to = path.split(">")
    # We always emit a two-cell path; AbstractPlay writes the stay-put move as a
    # bare cell + side ("a4N") and rejects "a4-a4N", so collapse it here.
    if frm == to:
        return f"{alg(frm)}{d}"
    return f"{alg(frm)}-{alg(to)}{d}"


def areas_of(G, s):
    out = {"open": [], "closed": [], "empty": []}
    for cells, owners in G.areas(s.board, s.fences):
        names = sorted(f"{i % SIZE},{i // SIZE}" for i in cells)
        out[("empty", "closed", "open")[min(len(owners), 2)]].append(names)
    for k in out:
        out[k].sort(key=lambda lst: "|".join(lst))
    return out


def check_mapping(g, s, orc):
    """Guard against a vacuous differential: assert the coordinate conversion
    actually agrees on a hand-checked, asymmetric fact."""
    d = orc.send(cmd="reset")
    assert dict(d["board"]) == {"0,3": 1, "6,3": 2}, d["board"]
    ob = {f"{i % SIZE},{i // SIZE}": v + 1 for i, v in enumerate(s.board) if v >= 0}
    assert ob == {"0,3": 1, "6,3": 2}, ob
    # a4 (0,3) fencing NORTH separates (0,3) from (0,4); pick that move in both
    # and confirm the resulting fence edge is the same pair of cells.
    d = orc.send(cmd="move", m="a4N")
    assert d["fences"] == [["0,3", "0,4"]], d["fences"]
    s2 = g.apply_move(s, "0,3>0,3=FENCE_N")
    assert sorted(s2.fences) == [("h", 0, 3)], sorted(s2.fences)
    print("coordinate mapping OK: AP a4/a5 fence == our ('h',0,3); "
          "AP a4==our 0,3, AP g4==our 6,3, AP N == our +r")
    orc.send(cmd="reset")


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--games", type=int, default=200)
    ap.add_argument("--seed", type=int, default=1)
    ap.add_argument("--gameslib", default=os.environ.get("AP_GAMESLIB", ""))
    ap.add_argument("--no-check-mapping", action="store_true",
                    help="skip the coordinate-mapping guard (don't)")
    args = ap.parse_args()
    if not args.gameslib:
        sys.exit("set AP_GAMESLIB (or --gameslib) to a gameslib checkout")

    _man, g = load_from_dir(HERE)
    G = type(g)
    orc = Oracle(Path(args.gameslib))
    rng = random.Random(args.seed)
    positions = mismatches = 0
    plies_total = 0
    passes = 0
    results = {"0": 0, "1": 0, "draw": 0}

    try:
        s0 = g.initial_state()
        # ALWAYS on by default: without it a systematically mirrored coordinate
        # conversion would make both sides agree with each other about the wrong
        # board and the whole differential would pass vacuously.
        if not args.no_check_mapping:
            check_mapping(g, s0, orc)
        for gi in range(args.games):
            s = g.initial_state()
            d = orc.send(cmd="reset")
            while True:
                positions += 1
                # --- compare everything ---
                oe, of, opass = ours(g, s)
                ae = set(d["entries"])
                af = {tuple(t) for t in d["fenceMoves"]}
                ob = {f"{i % SIZE},{i // SIZE}": v + 1
                      for i, v in enumerate(s.board) if v >= 0}
                ofences = sorted(tuple(sorted(
                    (f"{c},{r}", f"{c},{r + 1}") if k == "h"
                    else (f"{c},{r}", f"{c + 1},{r}")))
                    for k, c, r in s.fences)
                afences = sorted(tuple(p) for p in d["fences"])
                probs = []
                if oe != ae:
                    probs.append(f"entries: only-ours {sorted(oe - ae)} "
                                 f"only-AP {sorted(ae - oe)}")
                if of != af:
                    probs.append(f"fence moves: only-ours {sorted(of - af)} "
                                 f"only-AP {sorted(af - of)}")
                if opass != d["canPass"]:
                    probs.append(f"pass: ours={opass} AP={d['canPass']}")
                if ob != dict(d["board"]):
                    probs.append(f"board: {ob} vs {dict(d['board'])}")
                if list(s.stock) != d["stock"]:
                    probs.append(f"stock: {s.stock} vs {d['stock']}")
                if s.to_move + 1 != d["toMove"]:
                    probs.append(f"to move: {s.to_move + 1} vs {d['toMove']}")
                if ofences != afences:
                    probs.append(f"fences: {ofences} vs {afences}")
                if areas_of(G, s) != d["areas"]:
                    probs.append(f"areas: {areas_of(G, s)} vs {d['areas']}")
                if g.is_terminal(s) != d["gameover"]:
                    probs.append(f"gameover: {g.is_terminal(s)} vs {d['gameover']}")
                if list(G.scores(s)) != d["scores"]:
                    probs.append(f"scores: {G.scores(s)} vs {d['scores']}")
                if g.is_terminal(s):
                    r = g.returns(s)
                    win = {(1.0, -1.0): [1], (-1.0, 1.0): [2],
                           (0.0, 0.0): [1, 2]}[tuple(r)]
                    if win != d["winner"]:
                        probs.append(f"winner: {win} vs {d['winner']}")
                if probs:
                    mismatches += 1
                    print(f"MISMATCH game {gi} ply {plies_total}: "
                          + "; ".join(probs), file=sys.stderr)
                    print("  our fences:", sorted(s.fences), file=sys.stderr)
                    print("  our board :", ob, file=sys.stderr)
                    break
                if g.is_terminal(s):
                    a, b = G.scores(s)
                    results["0" if a > b else "1" if b > a else "draw"] += 1
                    break
                m = rng.choice(g.legal_moves(s))
                if m == "pass":
                    passes += 1
                d = orc.send(cmd="move", m=to_ap(m))
                s = g.apply_move(s, m)
                plies_total += 1
            if (gi + 1) % 25 == 0:
                print(f"  {gi + 1} games, {positions} positions, "
                      f"{mismatches} mismatches", file=sys.stderr)
    finally:
        orc.close()

    print(f"games={args.games} positions={positions} plies={plies_total} "
          f"passes={passes} mismatches={mismatches} results={results}")
    return 1 if mismatches else 0


if __name__ == "__main__":
    sys.exit(main())
