"""Macadamia Shogi -- H. G. Muller's factor-two shrink of the historic
Maka Dai Dai Shogi: a 13x13 large-shogi variant, 48 pieces a side of 26 types
(11 more via promotion), DROP-LESS, won by capturing ALL enemy royals.

Authoritative source (implementation-grade, followed exactly, overrides all
briefs): https://www.chessvariants.com/rules/macadamia-shogi  (H. G. Muller,
2015).  Its interactive-diagram config gives the exact per-piece Betza moves,
the exact initial squares and the promoted forms; the Rules prose defines
PROMOTION BY CAPTURE, the Lion / Wolf(Lion Dog) / Emperor mechanics and the win
condition.  The variant is directly played by HaChu 0.21 (``variant
macadamia-shogi``), used as a differential oracle for setup + movegen (see
selftest.py / the dev harness).

Modelled on games/nutty_shogi and games/chu_shogi (drop-less, no-check,
royal-capture ShogiLike subclasses with a full Lion engine).  Key facts:

* **Board 13x13**, files a-m (col 0-12), ranks 1-13 (row 0-12).  Player 0 =
  Sente (Black) at the bottom, advancing +row.  DROP-LESS.
* **PROMOTION BY CAPTURE (the crux).**  There is NO promotion zone.  A piece may
  promote only at the end of a turn in which it CAPTURED something.  Each type
  has ONE fixed promoted form.  Promotion is OPTIONAL, EXCEPT it is MANDATORY
  when the captured piece was itself already promoted.  Special override: when a
  non-royal piece captures a Priest/Saint it becomes a **Saint**, and when it
  captures a Pirate/Ghost it becomes a **Ghost** -- forced, even if it was
  already promoted (so the Saint & Ghost virtually never leave play).  Royals
  (King, Elephant and their promotions) never become Saint/Ghost; Queen & Castle
  never promote at all.
* **Win as event.**  Royal pieces are the King, the Emperor (promoted King) and
  the Prince (promoted Drunk Elephant -- a second King).  The game ends the
  instant a side has NO royal left.  Movegen is pseudo-legal.
* **Repetition / draws:** fourfold repetition of (position + side to move) or a
  hard ply cap -> an honest draw.  CVP's intent-based perpetual-check /
  perpetual-chase loss rules are a documented simplification (see rules.md).

Internal letters == the CVP interactive-diagram ids:
  P pawn, I snake, C copper, S silver, G gold, T tiger, X phoenix, O kirin,
  N lion, Y pirate, Z priest, E elephant, K king, L lance, F dragon,
  A guardian, M wrestler, U left-chariot, V right-chariot, B bishop, R rook,
  J capricorner, H hook-mover, W wolf, D castle, Q queen.
A promoted piece keeps its base letter with the square flagged in ``promoted``;
its moves come from PROMO_MOVE[letter] (the Saint/Ghost capture-override instead
changes the letter to Z/Y with the promoted flag set).
"""

from __future__ import annotations

import math
from dataclasses import dataclass

from agp.shogilike import ShogiLike, SState, BLACK, WHITE, cell

# ---------------------------------------------------------------- directions
# All in Black's forward frame: forward = +row (toward the enemy).
F, B = (0, 1), (0, -1)
WL, WR = (-1, 0), (1, 0)
FL, FR = (-1, 1), (1, 1)
BL, BR = (-1, -1), (1, -1)
ORTHO = [F, B, WL, WR]
DIAG = [FL, FR, BL, BR]
ALL8 = ORTHO + DIAG
GOLD = [F, B, WL, WR, FL, FR]
BOX2 = [(dc, dr) for dc in range(-2, 3) for dr in range(-2, 3) if (dc, dr) != (0, 0)]
ALFIL = [(2, 2), (-2, 2), (2, -2), (-2, -2)]
DABBABA = [(2, 0), (-2, 0), (0, 2), (0, -2)]

# ------------------------------------------------------------ movement tables
# letter -> (slides, leaps, ranged);  ranged = [((dc, dr), max_steps), ...]
# (bounded, blockable rides).  Special pieces (Lion, Wolf, Capricorner, Hook
# Mover, Berserker, Ghost, Saint, Emperor) are NOT in these tables -- they are
# generated by ``_kind``-dispatched code.
BASE_MOVE = {
    "P": ([], [F], []),                                       # fW    pawn
    "I": ([], [F, B], []),                                    # vW    snake
    "C": ([], [F, B, FL, FR], []),                            # vWfF  copper
    "S": ([], [FL, FR, BL, BR, F], []),                       # FfW   silver
    "G": ([], GOLD, []),                                      # WfF   gold
    "T": ([], [FL, FR, BL, BR, WL, WR, B], []),               # FsbW  tiger
    "X": ([], [F, B, WL, WR] + ALFIL, []),                    # WA    phoenix
    "O": ([], DIAG + DABBABA, []),                            # FD    kirin
    "Y": ([], [FL, FR, BL, BR, WR], []),                      # lbfFrW pirate (4 diag + right step)
    "Z": ([], [FL, FR, BL, BR, WL], []),                      # rbfFlW priest (4 diag + left step)
    "E": ([], [FL, FR, BL, BR, F, WL, WR], []),               # FfsW  drunk elephant
    "K": ([], ALL8, []),                                      # K     king
    "L": ([F], [], []),                                       # fR    lance
    "F": ([], [], [(FL, 2), (FR, 2), (BL, 2), (BR, 2)]),      # F2    dragon
    "A": ([], [FL, FR], [(F, 3), (B, 3), (WL, 3), (WR, 3)]),  # W3fF  guardian
    "M": ([], [WL, WR], [(FL, 3), (FR, 3), (BL, 3), (BR, 3)]),  # F3sW  wrestler
    "U": ([F, FL, BR], [B], []),                              # fRbWflbrB  left chariot
    "V": ([F, FR, BL], [B], []),                              # fRbWfrblB  right chariot
    "B": (DIAG, [], []),                                      # B     bishop
    "R": (ORTHO, [], []),                                     # R     rook
    "D": (ORTHO, DIAG, []),                                   # RF    castle (dragon-king)
    "Q": (ALL8, [], []),                                      # Q     queen
}
PROMO_MOVE = {
    "P": ([], GOLD, []),                                      # -> Gold
    "I": ([F, B], [], []),                                    # -> Sliding Snake (vR)
    "C": ([F, B, FL, FR], [], []),                            # -> Running Copper (vRfB)
    "S": ([FL, FR, BL, BR, F], [], []),                       # -> Running Silver (BfR)
    "G": ([F, B, WL, WR, FL, FR], [], []),                    # -> Running Gold (RfB)
    "T": ([FL, FR, BL, BR, B, WL, WR], [], []),               # -> Running Tiger (BbsR)
    "X": ([F, B], [], [(WL, 2), (WR, 2), (FL, 3), (FR, 3), (BL, 3), (BR, 3)]),  # Golden Bird vRsW2F3
    "O": ([WL, WR], [], [(F, 2), (B, 2), (FL, 3), (FR, 3), (BL, 3), (BR, 3)]),  # Unicorn sRvW2F3
    "E": ([], ALL8, []),                                      # -> King (Prince, royal)
    # Everything that "promotes to Gold": L F A M U V B R J H W -> Gold.
    "L": ([], GOLD, []), "F": ([], GOLD, []), "A": ([], GOLD, []),
    "M": ([], GOLD, []), "U": ([], GOLD, []), "V": ([], GOLD, []),
    "B": ([], GOLD, []), "R": ([], GOLD, []), "J": ([], GOLD, []),
    "H": ([], GOLD, []), "W": ([], GOLD, []),
    # N->Berserker, Y->Ghost, Z->Saint, K->Emperor : special (see _kind).
}
# 24 promotable base types (Queen Q and Castle D never promote).
CAN_PROMOTE = frozenset(BASE_MOVE) - {"Q", "D"}
# Royal-for-promotion pieces never turn into Saint/Ghost (they keep their own
# royal promotion): King -> Emperor, Elephant -> King(Prince).
ROYAL_PROMO = frozenset(["K", "E"])

# Rough material values (heuristic only).  A present royal is not scored.
VALS = {"P": 1, "I": 2, "C": 3, "S": 3, "G": 5, "T": 4, "X": 5, "O": 5,
        "N": 22, "Y": 6, "Z": 6, "E": 6, "L": 3, "FF": 3, "F": 3, "A": 5,
        "M": 5, "U": 6, "V": 6, "B": 6, "R": 8, "J": 12, "H": 12, "W": 20,
        "D": 10, "Q": 14, "K": 0}
PVALS = {"P": 5, "I": 6, "C": 7, "S": 7, "G": 8, "T": 8, "X": 16, "O": 16,
         "N": 30, "Y": 34, "Z": 34, "E": 0, "L": 5, "F": 5, "A": 5, "M": 5,
         "U": 5, "V": 5, "B": 5, "R": 5, "J": 5, "H": 5, "W": 5, "K": 0}


@dataclass
class MacState(SState):
    winner: object = None      # seat whose opponent lost all royals
    key: str = ""              # cached repetition key (recomputed, not serialized)


class MacadamiaShogi(ShogiLike):
    # uid comes from the manifest; do not hardcode it here.
    name = "Macadamia Shogi"

    WIDTH = HEIGHT = 13
    ZONE = 0                                   # no promotion zone (promote by capture)
    PLY_CAP = 600
    LABELS = {
        "I": "Sn", "C": "Co", "T": "Ti", "X": "Ph", "O": "Ky", "N": "Ln",
        "Y": "Pi", "Z": "Pr", "E": "El", "F": "Dr", "A": "Gd", "M": "Wr",
        "U": "lC", "V": "rC", "J": "Cp", "H": "Hk", "W": "Wf", "D": "Ca",
        "+P": "+G", "+I": "SS", "+C": "rC", "+S": "rS", "+G": "rG", "+T": "rT",
        "+X": "GB", "+O": "Un", "+N": "Bk", "+Y": "Gh", "+Z": "St", "+E": "Pc",
        "+K": "Em", "+L": "+G", "+F": "+G", "+A": "+G", "+M": "+G", "+U": "+G",
        "+V": "+G", "+B": "+G", "+R": "+G", "+J": "+G", "+H": "+G", "+W": "+G",
    }

    def __init__(self):
        # No check rule (win = royals gone), no drops, no Lion-trade recapture
        # test.  attacked_squares() (selftest only) is computed forward.
        pass

    # ---- kind dispatch -----------------------------------------------------
    def _kind(self, letter, promoted):
        if not promoted:
            return {"N": "LION", "W": "WOLF", "J": "CAPRICORN",
                    "H": "HOOKMOVER"}.get(letter)
        return {"N": "BERSERKER", "Y": "GHOST", "Z": "SAINT",
                "K": "EMPEROR"}.get(letter)

    def _is_royal(self, letter, promoted):
        return letter == "K" or (letter == "E" and promoted)

    # ---- primitive generators ----------------------------------------------
    def _slides(self, board, f, pl, dirs):
        fs = f"{f[0]},{f[1]}"
        for (dc, dr) in dirs:
            cc = (f[0] + dc, f[1] + dr)
            while self.on(*cc):
                occ = board.get(cc)
                if occ is None:
                    yield f"{fs}>{cc[0]},{cc[1]}"
                else:
                    if occ[0] != pl:
                        yield f"{fs}>{cc[0]},{cc[1]}"
                    break
                cc = (cc[0] + dc, cc[1] + dr)

    def _ranged(self, board, f, pl, ranged):
        fs = f"{f[0]},{f[1]}"
        for (dc, dr), n in ranged:
            cc = f
            for _ in range(n):
                cc = (cc[0] + dc, cc[1] + dr)
                if not self.on(*cc):
                    break
                occ = board.get(cc)
                if occ is None:
                    yield f"{fs}>{cc[0]},{cc[1]}"
                else:
                    if occ[0] != pl:
                        yield f"{fs}>{cc[0]},{cc[1]}"
                    break

    def _leaps(self, board, f, pl, leaps, fwd):
        fs = f"{f[0]},{f[1]}"
        for (dc, dr) in leaps:
            to = (f[0] + dc, f[1] + dr * fwd)
            if not self.on(*to):
                continue
            occ = board.get(to)
            if occ is not None and occ[0] == pl:
                continue
            yield f"{fs}>{to[0]},{to[1]}"

    def _plain_moves(self, board, f, pl, letter, promd, fwd):
        slides, leaps, ranged = (PROMO_MOVE if promd else BASE_MOVE)[letter]
        # The move tables are written in Black's forward frame.  Gote (White) is
        # a full 180-degree ROTATION of Sente (matching the setup, which rotates,
        # and CVP's ``symmetry=rotate``), so BOTH the row AND the column of every
        # direction flip for White (fwd = -1).  For left-right symmetric pieces
        # negating the column is a no-op; it only matters for the chiral pieces
        # (Priest/Pirate lateral step, Left/Right Chariot diagonals), which would
        # otherwise be mirror-imaged instead of rotated.
        yield from self._leaps(board, f, pl, [(dc * fwd, dr * fwd) for (dc, dr) in leaps], 1)
        yield from self._slides(board, f, pl, [(dc * fwd, dr * fwd) for (dc, dr) in slides])
        yield from self._ranged(board, f, pl, [((dc * fwd, dr * fwd), n) for (dc, dr), n in ranged])

    def _lion_moves(self, board, f, pl, steps, box):
        """Double-mover Lion (same encoding as chu/nutty): ``f>t`` (adjacent step
        or dist-2 jump), ``f>m>f`` (igui / pass) and ``f>m>t`` (double capture /
        hit-and-run)."""
        fs = f"{f[0]},{f[1]}"
        for (dc, dr) in box:
            t = (f[0] + dc, f[1] + dr)
            if not self.on(*t):
                continue
            occ = board.get(t)
            if occ is not None and occ[0] == pl:
                continue
            yield f"{fs}>{t[0]},{t[1]}"
        for (dc, dr) in steps:
            m = (f[0] + dc, f[1] + dr)
            if not self.on(*m):
                continue
            occ_m = board.get(m)
            ms = f"{m[0]},{m[1]}"
            if occ_m is None:
                yield f"{fs}>{ms}>{fs}"                       # pass
                continue
            if occ_m[0] == pl:
                continue
            yield f"{fs}>{ms}>{fs}"                           # igui
            for (dc2, dr2) in steps:
                t = (m[0] + dc2, m[1] + dr2)
                if not self.on(*t) or t == f:
                    continue
                occ_t = board.get(t)
                if occ_t is not None and occ_t[0] == pl:
                    continue
                yield f"{fs}>{ms}>{t[0]},{t[1]}"             # double / hit-run

    def _wolf_moves(self, board, f, pl):
        """Triple-mover Lion Dog (Wolf): up to 3 king-steps along ONE ray, may
        jump, may annihilate up to 3 pieces along that ray, may return to start
        (pass).  Encoded as an explicit path ``f>[annihilated..]>final`` (a
        landing square that may itself be a capture); ``f>f`` is the pass,
        ``f>m>f`` an igui."""
        fs = f"{f[0]},{f[1]}"
        pass_ok = False
        for (dc, dr) in ALL8:
            s1 = (f[0] + dc, f[1] + dr)
            s2 = (f[0] + 2 * dc, f[1] + 2 * dr)
            s3 = (f[0] + 3 * dc, f[1] + 3 * dr)
            o1 = board.get(s1) if self.on(*s1) else "OFF"
            o2 = board.get(s2) if self.on(*s2) else "OFF"
            o3 = board.get(s3) if self.on(*s3) else "OFF"
            e1 = o1 not in (None, "OFF") and o1[0] != pl
            e2 = o2 not in (None, "OFF") and o2[0] != pl
            e3 = o3 not in (None, "OFF") and o3[0] != pl
            s1s = None if o1 == "OFF" else f"{s1[0]},{s1[1]}"
            s2s = None if o2 == "OFF" else f"{s2[0]},{s2[1]}"
            s3s = None if o3 == "OFF" else f"{s3[0]},{s3[1]}"
            # -- step 1 --
            if o1 != "OFF":
                if e1:
                    yield f"{fs}>{s1s}"                        # capture s1
                elif o1 is None:
                    yield f"{fs}>{s1s}"                        # quiet step
                    pass_ok = True
                    if e2:
                        yield f"{fs}>{s2s}>{s1s}"              # 2-out-1-in: annihilate s2, land s1
            # -- step 2 (jump over s1, whatever it is) --
            if o2 != "OFF" and (o2 is None or e2):
                yield f"{fs}>{s2s}"                            # plain jump to s2
                if e1:
                    yield f"{fs}>{s1s}>{s2s}"                  # annihilate s1, land s2
            # -- igui: annihilate adjacent enemy, stay put --
            if e1:
                yield f"{fs}>{s1s}>{fs}"
            # -- step 3 (jump over s1,s2) --
            if o3 != "OFF" and (o3 is None or e3):
                yield f"{fs}>{s3s}"                            # plain
                if e1:
                    yield f"{fs}>{s1s}>{s3s}"                  # annihilate s1
                if e2:
                    yield f"{fs}>{s2s}>{s3s}"                  # annihilate s2
                if e1 and e2:
                    yield f"{fs}>{s1s}>{s2s}>{s3s}"            # annihilate both
        if pass_ok:
            yield f"{fs}>{fs}"                                 # pure pass

    def _bent(self, board, f, pl, dirset):
        """Hook Mover (dirset=ORTHO) / Capricorner (dirset=DIAG): a rider that
        may make at most one 90-degree turn, at an EMPTY square it passes, then
        continue.  No jumping.  Returns net ``f>t`` moves (a set of targets)."""
        fs = f"{f[0]},{f[1]}"
        targets = set()
        for d1 in dirset:
            opp1 = (-d1[0], -d1[1])
            p = (f[0] + d1[0], f[1] + d1[1])
            while self.on(*p):
                occ = board.get(p)
                if occ is None:
                    targets.add(p)
                    # may turn here (perpendicular directions only)
                    for d2 in dirset:
                        if d2 == d1 or d2 == opp1:
                            continue
                        q = (p[0] + d2[0], p[1] + d2[1])
                        while self.on(*q):
                            o2 = board.get(q)
                            if o2 is None:
                                targets.add(q)
                            elif o2[0] != pl:
                                targets.add(q)
                                break
                            else:
                                break
                            q = (q[0] + d2[0], q[1] + d2[1])
                elif occ[0] != pl:
                    targets.add(p)
                    break
                else:
                    break
                p = (p[0] + d1[0], p[1] + d1[1])
        targets.discard(f)
        for t in targets:
            yield f"{fs}>{t[0]},{t[1]}"

    def _emperor_moves(self, board, f, pl):
        """Universal Leaper: move to (or capture on) ANY square of the board."""
        fs = f"{f[0]},{f[1]}"
        for c in range(self.WIDTH):
            for r in range(self.HEIGHT):
                if (c, r) == f:
                    continue
                occ = board.get((c, r))
                if occ is not None and occ[0] == pl:
                    continue
                yield f"{fs}>{c},{r}"

    def _piece_moves(self, state, f, pl, letter, promd, fwd):
        board = state.board
        k = self._kind(letter, promd)
        if k is None:
            yield from self._plain_moves(board, f, pl, letter, promd, fwd)
        elif k == "LION":
            yield from self._lion_moves(board, f, pl, ALL8, BOX2)
        elif k == "BERSERKER":
            yield from self._lion_moves(board, f, pl, ALL8, BOX2)
            yield from self._ranged(board, f, pl, [(d, 3) for d in ALL8])
        elif k == "GHOST":
            yield from self._lion_moves(board, f, pl, ALL8, BOX2)
            yield from self._slides(board, f, pl, ALL8)
        elif k == "WOLF":
            yield from self._wolf_moves(board, f, pl)
        elif k == "SAINT":
            yield from self._wolf_moves(board, f, pl)
            yield from self._slides(board, f, pl, ALL8)
        elif k == "CAPRICORN":
            yield from self._bent(board, f, pl, DIAG)
        elif k == "HOOKMOVER":
            yield from self._bent(board, f, pl, ORTHO)
        elif k == "EMPEROR":
            yield from self._emperor_moves(board, f, pl)

    # ---- capture analysis --------------------------------------------------
    def _captures(self, board, cells, pl):
        """List of captured (sq, letter, was_promoted) enemy pieces for a move
        path ``cells`` (origin, [annihilated..], final).  A final square equal to
        the origin (pass/igui) never counts as a landing capture."""
        f = cells[0]
        final = cells[-1]
        out = []
        for m in cells[1:-1]:
            occ = board.get(m)
            if occ is not None and occ[0] != pl:
                out.append((m, occ[1]))
        if final != f:
            occ = board.get(final)
            if occ is not None and occ[0] != pl:
                out.append((final, occ[1]))
        return out

    def _promo_target(self, letter, promd, captured, promoted_set, final):
        """Return (new_letter, forced) for a CAPTURING move, or (None, ...) when
        the piece cannot / need not promote.  ``forced`` True means the promotion
        is mandatory (no un-promoted alternative)."""
        if not captured:
            return None, False
        royal = self._is_royal(letter, promd)
        # -- Saint/Ghost capture override (non-royal only) --
        if not royal and letter != "E":
            saints = [sq for (sq, L) in captured if L == "Z"]
            ghosts = [sq for (sq, L) in captured if L == "Y"]
            if saints or ghosts:
                if saints and ghosts:
                    # capture both -> the one on the destination square (Lion),
                    # else the farthest (Wolf); we approximate with "farthest
                    # from origin", overridden by the landing square if it is one
                    # of them.  Rare; documented in rules.md.
                    pick_z = final in saints
                    pick_y = final in ghosts
                    if pick_z:
                        return "Z", True
                    if pick_y:
                        return "Y", True
                    return "Z", True
                return ("Z" if saints else "Y"), True
        # -- royal promotion (King->Emperor, Elephant->Prince) --
        if letter in ROYAL_PROMO and not promd:
            mand = any(c in promoted_set for (c, _L) in captured)
            return "ROYAL", mand
        # -- normal fixed-form promotion --
        if promd or letter not in CAN_PROMOTE:
            return None, False
        mand = any(c in promoted_set for (c, _L) in captured)
        return "SELF", mand

    # ---- move generation (with de-dup + capture promotion) -----------------
    def _moves(self, state):
        board, pl = state.board, state.to_move
        fwd = self._fwd(pl)
        pset = state.promoted
        seen = set()
        for sq, (p, letter) in list(board.items()):
            if p != pl:
                continue
            promd = sq in pset
            for m in self._piece_moves(state, sq, pl, letter, promd, fwd):
                if m in seen:
                    continue
                seen.add(m)
                cells = [cell(c) for c in m.split(">")]
                captured = self._captures(board, cells, pl)
                target, forced = self._promo_target(letter, promd, captured,
                                                     pset, cells[-1])
                if target is None:
                    yield m
                    continue
                pm = m + "=+"
                if forced:
                    if pm not in seen:
                        seen.add(pm)
                        yield pm
                else:
                    yield m
                    if pm not in seen:
                        seen.add(pm)
                        yield pm

    # ---- Game interface ----------------------------------------------------
    def setup_board(self):
        b = {}
        # Sente (Black) placement in 0-based (col, row); Gote = 180-deg rotation.
        # Squares transcribed VERBATIM from the CVP interactive-diagram config
        # (files a-m = col 0-12; config rank r -> row r-1).
        place = {}

        def putf(letter, cells):
            for (c, r) in cells:
                place[(c, r)] = letter                       # r is 0-based row
        putf("P", [(c, 3) for c in range(13)])               # rank 4
        putf("I", [(3, 4), (9, 4)])                          # d5, j5
        putf("C", [(2, 0), (10, 0)])                         # c1, k1
        putf("S", [(3, 0), (9, 0)])                          # d1, j1
        putf("G", [(4, 0), (8, 0)])                          # e1, i1
        putf("T", [(5, 1), (7, 1)])                          # f2, h2
        putf("X", [(11, 0)])                                 # l1
        putf("O", [(1, 0)])                                  # b1
        putf("N", [(3, 1)])                                  # d2
        putf("Y", [(7, 0)])                                  # h1
        putf("Z", [(5, 0)])                                  # f1
        putf("E", [(6, 1)])                                  # g2
        putf("K", [(6, 0)])                                  # g1
        putf("L", [(0, 0), (12, 0)])                         # a1, m1
        putf("F", [(1, 1), (11, 1)])                         # b2, l2
        putf("A", [(10, 2)])                                 # k3
        putf("M", [(2, 2)])                                  # c3
        putf("U", [(1, 2)])                                  # b3
        putf("V", [(11, 2)])                                 # l3
        putf("B", [(3, 2), (9, 2)])                          # d3, j3
        putf("R", [(0, 2), (12, 2)])                         # a3, m3
        putf("J", [(5, 2)])                                  # f3
        putf("H", [(7, 2)])                                  # h3
        putf("W", [(9, 1)])                                  # j2
        putf("D", [(4, 2), (8, 2)])                          # e3, i3
        putf("Q", [(6, 2)])                                  # g3
        for (c, r), L in place.items():
            b[(c, r)] = (BLACK, L)
            b[(12 - c, 12 - r)] = (WHITE, L)
        return b, set()

    def initial_state(self, options=None, rng=None):
        board, promoted = self.setup_board()
        st = MacState(board=board, promoted=frozenset(promoted),
                      hands={BLACK: {}, WHITE: {}}, to_move=BLACK)
        st.key = self._poskey(st)
        st.reps = {st.key: 1}
        return st

    def legal_moves(self, state):
        if state.winner is not None or self._draw(state):
            return []
        return list(self._moves(state))

    def _draw(self, state) -> bool:
        if state.winner is not None:
            return False
        return state.ply >= self.PLY_CAP or state.reps.get(state.key, 0) >= 4

    def is_terminal(self, state) -> bool:
        if state.winner is not None or self._draw(state):
            return True
        return next(self._moves(state), None) is None

    def returns(self, state):
        if state.winner is not None:
            return [1.0, -1.0] if state.winner == BLACK else [-1.0, 1.0]
        if self._draw(state):
            return [0.0, 0.0]
        # no legal move: the side to move loses
        return [-1.0, 1.0] if state.to_move == BLACK else [1.0, -1.0]

    def apply_move(self, state, move, rng=None):
        promote = move.endswith("=+")
        if promote:
            move = move[:-2]
        cells = [cell(p) for p in move.split(">")]
        f = cells[0]
        final = cells[-1]
        pl, letter = state.board[f]
        was_prom = f in state.promoted
        b = dict(state.board)
        prom = set(state.promoted)

        captured = self._captures(state.board, cells, pl)
        b.pop(f, None)
        prom.discard(f)
        for (sq, _L) in captured:
            b.pop(sq, None)
            prom.discard(sq)

        new_letter, new_prom = letter, was_prom
        if promote:
            target, _forced = self._promo_target(letter, was_prom, captured,
                                                  state.promoted, final)
            if target == "SELF" or target == "ROYAL":
                new_prom = True
            elif target in ("Z", "Y"):
                new_letter, new_prom = target, True
        b[final] = (pl, new_letter)
        prom.discard(final)
        if new_prom:
            prom.add(final)

        # ---- win as event: a side with no royal left loses -------------------
        winner = state.winner
        b_roy = any(p == BLACK and self._is_royal(t, sq in prom)
                    for sq, (p, t) in b.items())
        w_roy = any(p == WHITE and self._is_royal(t, sq in prom)
                    for sq, (p, t) in b.items())
        if not b_roy:
            winner = WHITE
        elif not w_roy:
            winner = BLACK

        st = MacState(board=b, promoted=frozenset(prom),
                      hands={BLACK: {}, WHITE: {}}, to_move=1 - pl,
                      ply=state.ply + 1, reps=dict(state.reps), winner=winner)
        st.key = self._poskey(st)
        st.reps[st.key] = st.reps.get(st.key, 0) + 1
        return st

    # ---- attacks (forward, for the selftest -- NOT used by the live rules) --
    def attacked_squares(self, state, by):
        probe = MacState(board=dict(state.board), promoted=frozenset(state.promoted),
                         hands={BLACK: {}, WHITE: {}}, to_move=by)
        probe.key = ""
        probe.reps = {}
        enemy = 1 - by
        victims = {sq for sq, (p, t) in state.board.items() if p == enemy}
        out = set()
        for m in self._moves(probe):
            nb = self.apply_move(probe, m).board
            for sq in victims:
                if nb.get(sq) != state.board[sq]:
                    out.add(sq)
        return out

    def attacked(self, state, sq, by):
        return sq in self.attacked_squares(state, by)

    # ---- keys / (de)serialise ----------------------------------------------
    def _poskey(self, state) -> str:
        parts = []
        for r in range(self.HEIGHT):
            for c in range(self.WIDTH):
                occ = state.board.get((c, r))
                if occ is None:
                    parts.append(".")
                else:
                    tag = "+" if (c, r) in state.promoted else ""
                    parts.append("bw"[occ[0]] + tag + occ[1])
        return "|".join(parts) + f"#{state.to_move}"

    def serialize(self, state) -> dict:
        d = super().serialize(state)
        d["winner"] = state.winner
        return d

    def deserialize(self, d) -> MacState:
        base = super().deserialize(d)
        st = MacState(board=base.board, promoted=base.promoted, hands=base.hands,
                      to_move=base.to_move, ply=base.ply, reps=base.reps,
                      winner=d.get("winner"))
        st.key = self._poskey(st)
        return st

    # ---- bot heuristic -----------------------------------------------------
    def heuristic(self, state):
        bal = 0.0
        for sq, (p, t) in state.board.items():
            v = (PVALS if sq in state.promoted else VALS).get(t, 4.0)
            bal += v if p == BLACK else -v
        score = math.tanh(bal / 60.0)
        return [score, -score]

    # ---- presentation ------------------------------------------------------
    def describe_move(self, state, move) -> str:
        promote = move.endswith("=+")
        raw = move[:-2] if promote else move
        parts = raw.split(">")
        f = cell(parts[0])
        _, t = state.board.get(f, (None, "?"))
        tag = self._label(t, f in state.promoted)
        cells = [cell(p) for p in parts]
        caps = self._captures(state.board, cells, state.to_move)
        sep = "x" if caps else "-"
        dest = parts[-1]
        if len(parts) >= 3 and cells[-1] == f:
            return f"{tag}{parts[0]}x!{parts[1]}"             # igui
        return f"{tag}{parts[0]}{sep}{dest}" + ("+" if promote else "")

    def render(self, state, perspective=None) -> dict:
        pieces = [
            {"cell": f"{c},{r}", "owner": p,
             "label": self._label(t, (c, r) in state.promoted)}
            for (c, r), (p, t) in state.board.items()
        ]
        names = {BLACK: "Sente (Black)", WHITE: "Gote (White)"}
        if state.winner is not None:
            caption = f"{names[state.winner]} wins — all enemy royals captured"
        elif self.is_terminal(state):
            ret = self.returns(state)
            caption = "Draw" if ret == [0.0, 0.0] else f"{names[0 if ret[0] > 0 else 1]} wins"
        else:
            caption = f"{names[state.to_move]} to move"
        return {
            "board": {"type": "square", "width": self.WIDTH, "height": self.HEIGHT},
            "pieces": pieces,
            "highlights": [],
            "caption": caption,
        }
