#!/usr/bin/env python3
"""Differential test of Push Fight against Maks Verver's reference implementation.

MANUAL / ONE-TIME (not part of the pure-stdlib selftest): needs `node` and the
`html/src/{board,moves,perms}.js` sources from github.com/maksverver/pushfight --
the code that was actually used to solve the game completely.

    d=/tmp/pfjs && mkdir -p $d
    for f in board moves perms; do curl -sL -o $d/$f.js \\
      https://raw.githubusercontent.com/maksverver/pushfight/master/html/src/$f.js; done
    python3 _diff_reference.py --write-harness $d      # emits $d/harness.mjs
    PUSHFIGHT_JS=$d python3 _diff_reference.py [games]

At every turn-start position of a random game it compares, against the reference:

  1. the COMPLETE SET OF LEGAL TURNS (each turn = 0-2 moves plus the mandatory
     push, in the reference's own "c2-d2,d1-e1" notation), which exercises move
     generation, push legality, the rails, the anchor, and the completeness AND
     soundness of our per-ply decomposition of a turn; and
  2. the RESOLVED POSITION after each of those turns plus which colour lost a
     piece -- so where every shoved piece lands, where the anchor ends up and
     who the loser is are checked, not merely which turns are legal.

The harness is driven with an ALGEBRAIC piece list, deliberately NOT with our
26-character permutation string: a harness that handed the oracle our own field
ordering would be inheriting board geometry from the thing it is testing. The
only shared assumption here is standard chess-style square names.
"""
from __future__ import annotations

import json
import os
import random
import subprocess
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[2]))
from agp.loader import load_from_dir                                   # noqa: E402

HARNESS_JS = r"""// Generated by _diff_reference.py --write-harness. Drop next to Maks Verver's
// html/src/{board,moves,perms}.js and run `node harness.mjs` with one JSON
// request per line on stdin: {"pieces": [["d2","O"], ...], "player": 0|1}.
// Replies with one JSON object per line: {turn: {pos, lost}}.
import {
  makePiece, PieceType, RED_PLAYER, BLUE_PLAYER, FIELD_COUNT,
  getPieceType, getPlayerColor, FIELD_ROW, FIELD_COL,
} from './board.js';
import {
  generateMoves, generatePushes, applyMoves, executeMoves, parseField, formatTurn,
} from './moves.js';

const CH = {
  o: [RED_PLAYER, PieceType.MOVER], O: [RED_PLAYER, PieceType.PUSHER],
  P: [RED_PLAYER, PieceType.ANCHOR],
  x: [BLUE_PLAYER, PieceType.MOVER], X: [BLUE_PLAYER, PieceType.PUSHER],
  Y: [BLUE_PLAYER, PieceType.ANCHOR],
};
const REV = {'0,1': 'o', '0,2': 'O', '0,3': 'P', '1,1': 'x', '1,2': 'X', '1,3': 'Y'};

function build(spec) {
  const pieces = new Array(FIELD_COUNT).fill(0);
  for (const [sq, ch] of spec) {
    const i = parseField(sq);
    if (i < 0) throw new Error('bad square ' + sq);
    const [color, type] = CH[ch];
    pieces[i] = makePiece(color, type);
  }
  return pieces;
}
const fmtField = (i) =>
  String.fromCharCode(97 + FIELD_COL[i]) + String(4 - FIELD_ROW[i]);

function dump(pieces) {
  const out = [];
  for (let i = 0; i < pieces.length; ++i) {
    if (pieces[i] !== 0) {
      out.push(fmtField(i) +
        REV[getPlayerColor(pieces[i]) + ',' + getPieceType(pieces[i])]);
    }
  }
  return out.sort().join(' ');
}

function allTurns(pieces, player) {
  const out = new Map();
  const walk = (p, path) => {
    for (const [i, j] of generatePushes(p, player)) {
      const key = formatTurn([...path, [i, j]]);
      if (out.has(key)) continue;
      const np = [...p];
      const lost = executeMoves(np, [i, j]);   // returns the FALLEN piece's colour
      out.set(key, {pos: dump(np), lost});
    }
    if (path.length >= 2) return;
    for (const [i, j] of generateMoves(p, player)) {
      walk(applyMoves(p, [i, j]), [...path, [i, j]]);
    }
  };
  walk(pieces, []);
  return Object.fromEntries(out);
}

let buf = '';
process.stdin.setEncoding('utf8');
process.stdin.on('data', (d) => { buf += d; });
process.stdin.on('end', () => {
  const out = [];
  for (const line of buf.split('\n').filter((l) => l.trim())) {
    const req = JSON.parse(line);
    out.push(JSON.stringify(allTurns(build(req.pieces), req.player)));
  }
  process.stdout.write(out.join('\n') + '\n');
});
"""


def dump_state(mod, s):
    """Board as the reference's own text: sorted 'd2O e3x ...'."""
    out = []
    for cell, (owner, kind) in s.board.items():
        if kind == mod.MOVER:
            ch = "o" if owner == 0 else "x"
        elif cell == s.anchor:
            ch = "P" if owner == 0 else "Y"
        else:
            ch = "O" if owner == 0 else "X"
        out.append(mod.alg(cell) + ch)
    return " ".join(sorted(out))


def turn_map(g, mod, s):
    """turn string -> (resolved board dump, colour that lost a piece or -1)."""
    out = {}

    def walk(st, path):
        for mv in g.legal_moves(st):
            src, dst = mv.split(">")
            leg = f"{mod.alg(src)}-{mod.alg(dst)}"
            nxt = g.apply_move(st, mv)
            if dst in st.board:                       # a push closes the turn
                lost = -1 if nxt.winner is None else 1 - nxt.winner
                out[",".join(path + [leg])] = (dump_state(mod, nxt), lost)
            else:
                walk(nxt, path + [leg])

    walk(s, [])
    return out


def main():
    argv = sys.argv[1:]
    if argv and argv[0] == "--write-harness":
        dest = Path(argv[1] if len(argv) > 1 else ".")
        if dest.is_dir():
            dest = dest / "harness.mjs"
        dest.write_text(HARNESS_JS)
        print(f"wrote {dest}")
        return 0

    js = Path(os.environ.get("PUSHFIGHT_JS", "."))
    harness = js / "harness.mjs"
    if not harness.exists():
        sys.exit(f"{harness} missing -- run `{sys.argv[0]} --write-harness {js}` "
                 "and put board.js/moves.js/perms.js there (see the module docstring)")

    n_games = int(argv[0]) if argv else 12
    seed = int(argv[1]) if len(argv) > 1 else 20260729
    pkg = Path(__file__).resolve().parent
    man, g = load_from_dir(pkg)
    mod = sys.modules[type(g).__module__]

    probes, mine = [], []
    rng = random.Random(seed)
    for i in range(n_games):
        s = g.initial_state(options={"setup": "standard" if i % 2 else "free"})
        while not g.is_terminal(s):
            if not g._placing(s) and s.moves_used == 0:
                probes.append({"pieces": [[t[:2], t[2]] for t in
                                          dump_state(mod, s).split()],
                               "player": s.to_move})
                mine.append(turn_map(g, mod, s))
            s = g.apply_move(s, rng.choice(g.legal_moves(s)))

    inp = "\n".join(json.dumps(p) for p in probes) + "\n"
    res = subprocess.run(["node", str(harness)], input=inp, capture_output=True,
                         text=True, cwd=str(js))
    if res.returncode:
        sys.exit(f"harness failed: {res.stderr}")
    lines = [l for l in res.stdout.split("\n") if l.strip()]
    assert len(lines) == len(probes), (len(lines), len(probes))

    bad = turns = 0
    for ours, line in zip(mine, lines):
        theirs = json.loads(line)
        if set(ours) != set(theirs):
            bad += 1
            print("TURN-SET MISMATCH"
                  f"\n  only ours:   {sorted(set(ours) - set(theirs))[:8]}"
                  f"\n  only theirs: {sorted(set(theirs) - set(ours))[:8]}")
            continue
        for t, (position, lost) in ours.items():
            turns += 1
            if position != theirs[t]["pos"] or lost != theirs[t]["lost"]:
                bad += 1
                if bad <= 8:
                    print(f"RESOLUTION MISMATCH turn={t}"
                          f"\n  ours   {position} lost={lost}"
                          f"\n  theirs {theirs[t]['pos']} lost={theirs[t]['lost']}")
    print(f"{len(probes)} positions, {turns} legal turns compared "
          f"(legality + resolution), {bad} mismatches")
    return 1 if bad else 0


if __name__ == "__main__":
    sys.exit(main())
