"""Wellisch's Three-Handed Hexagonal Chess (Siegmund Wellisch, Vienna 1912).

Primary source: Siegmund Wellisch, "Das Dreischach", *Wiener Schach-Zeitung*
XV. Jahrgang 1912, Nr. 21/24, S. 322-330.  Everything here follows that
article; the four points it leaves open are named interpretations documented in
`rules.md`.

Deliberately STANDALONE -- it does not build on `agp.hexchesslike`, whose seam
assumes two seats, one royal per side and a terminal checkmate.  All three are
false here: three seats, a *non-terminal* checkmate (a mated king may be freed
by the third player), army takeover on king capture, and Wellisch's own scored
three-way payoff table.

Geometry (axial, pointy-top, hexhex of side 6 = 91 cells):
    q increases to the RIGHT, r increases DOWNWARD, |q|,|r|,|q+r| <= 5.
Wellisch's own coordinates map in as  q = N - 6,  r = 5 - L  with letters
a..l (11 rows, NO "j") and numbers 1..11.
"""

from __future__ import annotations

from dataclasses import dataclass, replace
from typing import Optional

from agp.game import Game

# --------------------------------------------------------------------------
# board geometry
# --------------------------------------------------------------------------

RADIUS = 5                                    # hexagon of side 6 -> 91 cells
CELLS = tuple((q, r) for q in range(-RADIUS, RADIUS + 1)
              for r in range(-RADIUS, RADIUS + 1) if abs(q + r) <= RADIUS)
CELLSET = frozenset(CELLS)

# The six edge-adjacent ("orthogonal") directions -- rook, king and pawn steps.
ORTHO = ((1, 0), (-1, 0), (0, 1), (0, -1), (1, -1), (-1, 1))
# The six hex-DIAGONAL directions: one "Sprung" to the nearest cell of the SAME
# colour.  This is Wellisch's knight move (a Fers), and half of the queen's.
DIAG = ((1, 1), (-1, -1), (2, -1), (-2, 1), (1, -2), (-1, 2))

# Wellisch's three cell colours: (L + N) mod 3 in his coordinates, which is
# (q - r + 2) mod 3 in ours.  1 = yellow ("weiss"), 2 = black, 0 = red.
# Diagonal steps preserve it, so a knight is colour-bound and each player needs
# three of them.
def cell_colour(q: int, r: int) -> int:
    return (q - r + 2) % 3


def on_board(c) -> bool:
    return c in CELLSET


# Wellisch's own square names, used for the move log: letters a..l with NO "j".
LETTERS = "abcdefghikl"


def cell_name(c) -> str:
    """(q, r) -> Wellisch's own coordinate, e.g. (-2, 5) -> 'a4'."""
    q, r = c
    return f"{LETTERS[RADIUS - r]}{q + RADIUS + 1}"


def cell_id(c) -> str:
    return f"{c[0]},{c[1]}"


def parse_cell(s: str):
    q, r = s.split(",")
    return (int(q), int(r))


def rot120(c):
    """The 120 deg rotation of the board about its centre.  It maps
    White -> Black -> Red -> White (armies, home edges and pawn directions)."""
    q, r = c
    return (-q - r, q)


# ---- precomputed neighbour / ray tables -----------------------------------

NB_O = {c: tuple((c[0] + d[0], c[1] + d[1]) for d in ORTHO
                 if (c[0] + d[0], c[1] + d[1]) in CELLSET) for c in CELLS}
NB_D = {c: tuple((c[0] + d[0], c[1] + d[1]) for d in DIAG
                 if (c[0] + d[0], c[1] + d[1]) in CELLSET) for c in CELLS}


def _ray(c, d):
    out = []
    x = (c[0] + d[0], c[1] + d[1])
    while x in CELLSET:
        out.append(x)
        x = (x[0] + d[0], x[1] + d[1])
    return tuple(out)


RAYS = {c: tuple(r for r in (_ray(c, d) for d in ORTHO) if r) for c in CELLS}

# --------------------------------------------------------------------------
# seats
# --------------------------------------------------------------------------
# Seat 0 = Weiss (White, bottom edge r = +5)
# Seat 1 = Rot   (Red,   upper-right edge q = +5)
# Seat 2 = Schwarz (Black, upper-left edge q + r = -5)
# Wellisch's move order is Weiss -> Rot -> Schwarz, i.e. simply 0, 1, 2.

WHITE, RED, BLACK = 0, 1, 2
SEAT_NAMES = ("White", "Red", "Black")
SEAT_GERMAN = ("Weiss", "Rot", "Schwarz")
SEAT_WHERE = ("bottom", "upper right", "upper left")

# Each seat's forward direction is a hexagon VERTEX direction, so there is no
# straight-ahead orthogonal step: a pawn steps -- and captures -- in EITHER of
# two forward directions 120 deg apart.
FORWARD = {
    WHITE: ((0, -1), (1, -1)),
    RED:   ((-1, 1), (-1, 0)),
    BLACK: ((1, 0), (0, 1)),
}


def is_promo_cell(home: int, c) -> bool:
    """The promotion row is the free hexagon edge OPPOSITE the army's home edge."""
    q, r = c
    if home == WHITE:
        return r == -RADIUS
    if home == RED:
        return q == -RADIUS
    return q + r == RADIUS


# ---- the starting array, from Wellisch 1912 p.327 + Fig. 5 ----------------
# Transcribed independently for each seat (NOT generated by rotation, so the
# 120 deg-symmetry selftest stays a real check).  Verified against the woodcut,
# Pritchard's ECV diagram, CECV p.334 and the Ludii .lud -- all agree on all
# 45 men.  The Oxford Companion / German Wikipedia diagram does NOT (it mirrors
# the Red and Black armies); see rules.md.

ARRAY = {
    WHITE: {                                   # Wellisch rows a, b, c
        "K": [(-2, 5)],                        # a4
        "Q": [(-3, 5)],                        # a3
        "R": [(-4, 5), (-1, 5)],               # a2 a5
        "N": [(-5, 5), (0, 5), (-2, 4)],       # a1 a6 b4
        "P": [(-5, 4), (-4, 4), (-3, 4), (-1, 4), (0, 4), (1, 4),   # b1 b2 b3 b5 b6 b7
              (-2, 3), (-1, 3)],                                    # c4 c5
    },
    BLACK: {                                   # Wellisch rows L-N = 4, 3, 2
        "K": [(-3, -2)],                       # h3
        "Q": [(-2, -3)],                       # i4
        "R": [(-4, -1), (-1, -4)],             # g2 k5
        "N": [(-5, 0), (0, -5), (-2, -2)],     # f1 l6 h4
        "P": [(-5, 1), (-4, 0), (-3, -1), (-1, -3), (0, -4), (1, -5),  # e1 f2 g3 i5 k6 l7
              (-2, -1), (-1, -2)],                                     # g4 h5
    },
    RED: {                                     # Wellisch rows N = 11, 10, 9
        "K": [(5, -3)],                        # i11
        "Q": [(5, -2)],                        # h11
        "R": [(5, -4), (5, -1)],               # g11 k11
        "N": [(5, -5), (5, 0), (4, -2)],       # f11 l11 h10
        "P": [(4, -5), (4, -4), (4, -3), (4, -1), (4, 0), (4, 1),   # e10 f10 g10 i10 k10 l10
              (3, -2), (3, -1)],                                    # g9 h9
    },
}

# Castling: the king SWAPS PLACES with a rook ("under the usual rules of
# two-handed chess").  Each home row reads N R Q K R N from the player's left,
# so one rook is adjacent to the king (a one-cell swap) and the other is two
# cells away with the queen in between.
CASTLE = {
    WHITE: {"king": (-2, 5),
            "rooks": {(-1, 5): (), (-4, 5): ((-3, 5),)}},
    RED:   {"king": (5, -3),
            "rooks": {(5, -4): (), (5, -1): ((5, -2),)}},
    BLACK: {"king": (-3, -2),
            "rooks": {(-4, -1): (), (-1, -4): ((-2, -3),)}},
}

# Reverse pawn-attack table: which (cell, army) a pawn would have to stand on
# to attack `c`.  Check detection is a separate code path from move generation,
# so this table is built independently of FORWARD's forward use.
PAWN_FROM = {}
for _c in CELLS:
    _src = []
    for _h in (WHITE, RED, BLACK):
        for _f in FORWARD[_h]:
            _x = (_c[0] - _f[0], _c[1] - _f[1])
            if _x in CELLSET:
                _src.append((_x, _h))
    PAWN_FROM[_c] = tuple(_src)

# --------------------------------------------------------------------------
# termination constants  (Wellisch gives none -- see rules.md, interpretation 4)
# --------------------------------------------------------------------------

# Plies with no capture, no pawn move and no promotion before the game is a
# draw.  150 plies = 50 turns each, the three-player analogue of chess's
# fifty-move rule.
NOPROGRESS = 150
REPETITION = 3                                 # threefold repetition -> draw

# Hard backstop, DERIVED from the game's own bound and never expected to bite:
# a pawn advance is monotone (<= 10 rows x 24 pawns), captures <= 44, delayed
# promotions <= 24, so there are at most ~310 progress events; between any two
# of them at most NOPROGRESS plies may pass, giving < 47,000 plies.
PLY_CAP = 47000


# --------------------------------------------------------------------------
# state
# --------------------------------------------------------------------------

@dataclass(frozen=True)
class WState:
    board: dict                 # (q, r) -> (owner, letter, home_army)
    turn: int
    alive: tuple                # (bool, bool, bool)
    out: tuple                  # seats in ELIMINATION ORDER (first out first)
    pool: tuple                 # per ARMY: tuple of letters of pieces it has LOST
    castling: tuple             # sorted tuple of (seat, rook_cell) still available
    halfmove: int = 0
    ply: int = 0
    reps: dict = None
    over: bool = False
    reason: str = ""
    last: tuple = None          # (frm, to) of the previous move, for highlights


PIECE_VALUE = {"Q": 9, "R": 5, "N": 3, "P": 1, "K": 0}
PROMOTABLE = ("Q", "R", "N")


class WellischChess(Game):
    """Wellisch's Dreischach, 1912 -- the first hexagonal chess ever published."""

    name = "Wellisch's Three-Handed Hexagonal Chess"

    @property
    def num_players(self) -> int:
        return 3

    # ---- setup ------------------------------------------------------------

    def initial_state(self, options: Optional[dict] = None, rng=None) -> WState:
        board = {}
        for seat, men in ARRAY.items():
            for letter, cells in men.items():
                for c in cells:
                    board[c] = (seat, letter, seat)
        castling = tuple(sorted((p, rc) for p in (WHITE, RED, BLACK)
                                for rc in CASTLE[p]["rooks"]))
        s = WState(board=board, turn=WHITE, alive=(True, True, True), out=(),
                   pool=((), (), ()), castling=castling, reps={})
        return replace(s, reps={self._key(s): 1})

    # ---- attack / check ---------------------------------------------------

    @staticmethod
    def _attacked(board: dict, cell, by: frozenset) -> bool:
        """Is `cell` attacked by a man owned by any player in `by`?"""
        for ray in RAYS[cell]:
            for i, c in enumerate(ray):
                pc = board.get(c)
                if pc is None:
                    continue
                o, l, _ = pc
                if o in by and (l == "R" or l == "Q" or (l == "K" and i == 0)):
                    return True
                break
        for c in NB_D[cell]:
            pc = board.get(c)
            if pc is not None and pc[0] in by and (pc[1] == "N" or pc[1] == "Q"):
                return True
        for c, home in PAWN_FROM[cell]:
            pc = board.get(c)
            if pc is not None and pc[0] in by and pc[1] == "P" and pc[2] == home:
                return True
        return False

    @staticmethod
    def _king_cell(board: dict, p: int):
        """A player commands exactly one king -- his own (a captured king is
        removed from the board and its owner eliminated)."""
        for c, (o, l, _h) in board.items():
            if l == "K" and o == p:
                return c
        return None

    def _in_check(self, board: dict, alive, p: int) -> bool:
        k = self._king_cell(board, p)
        if k is None:
            return False
        others = frozenset(x for x in range(3) if alive[x] and x != p)
        return self._attacked(board, k, others)

    # ---- king-capture legality -------------------------------------------
    #
    # Wellisch: a king may be captured only while checkmate stands against it,
    # and the third player may lift the mate instead.  So "player p is MATED"
    # is a property of the CURRENT position: p is in check and has no legal
    # move.  That definition is mildly self-referential -- p's escapes could in
    # principle include capturing some OTHER mated king -- so we start by
    # assuming every checked player is mated (the most permissive move sets)
    # and iterate to a fixed point.
    #
    # The step is ANTI-monotone (a LARGER `capt` gives every player MORE
    # escapes, hence a SMALLER mated set), so the iteration need not decrease:
    # it can settle into a 2-cycle.  A constructed position where it does:
    # two players are in check ONLY from each other's men and each one's ONLY
    # legal move is to capture the other's king (which transfers that army and
    # so lifts his own check).  Assume both mated -> both have an escape ->
    # neither is mated -> neither may take a king -> both are mated again.
    # Neither mate stands on its own, so on a cycle we take the INTERSECTION of
    # the two alternating sets: a king may be captured only when its mate does
    # not itself depend on a king capture.  That also bounds the loop.

    def _mated(self, board: dict, alive, pool, castling) -> frozenset:
        checked = frozenset(p for p in range(3)
                            if alive[p] and self._in_check(board, alive, p))
        if not checked:
            return frozenset()
        capt = checked
        seen = set()
        while True:
            nxt = frozenset(p for p in checked
                            if not self._has_legal(board, alive, p, capt - {p},
                                                   pool, castling))
            if nxt == capt:
                return nxt
            if nxt in seen:                       # 2-cycle: mutual dependency
                return nxt & capt
            seen.add(capt)
            capt = nxt

    # ---- move generation --------------------------------------------------

    @staticmethod
    def _target_ok(board: dict, t, p: int, capt: frozenset) -> bool:
        pc = board.get(t)
        if pc is None:
            return True
        if pc[0] == p:
            return False
        if pc[1] == "K":
            return pc[0] in capt                # only a MATED king may be taken
        return True

    def _pseudo(self, board: dict, p: int, capt: frozenset, pool, castling):
        """All moves for `p` before the own-king-safety filter.  Each is
        (frm, to, promo_letter_or_None, is_castle)."""
        out = []
        for c, (o, l, h) in board.items():
            if o != p:
                continue
            if l == "P":
                promos = tuple(x for x in PROMOTABLE if x in pool[h])
                for f in FORWARD[h]:
                    t = (c[0] + f[0], c[1] + f[1])
                    if t not in CELLSET or not self._target_ok(board, t, p, capt):
                        continue
                    if is_promo_cell(h, t):
                        # Promotion is to a piece the army has ALREADY LOST.
                        for x in promos:
                            out.append((c, t, x, False))
                        if not promos:          # delayed promotion: just step on
                            out.append((c, t, None, False))
                    else:
                        out.append((c, t, None, False))
                # Delayed promotion: a pawn already parked on the promotion row
                # promotes on a later turn, once a piece has become available.
                if is_promo_cell(h, c):
                    for x in promos:
                        out.append((c, c, x, False))
            elif l == "N":
                for t in NB_D[c]:
                    if self._target_ok(board, t, p, capt):
                        out.append((c, t, None, False))
            elif l == "R" or l == "Q":
                for ray in RAYS[c]:
                    for t in ray:
                        pc = board.get(t)
                        if pc is None:
                            out.append((c, t, None, False))
                            continue
                        if self._target_ok(board, t, p, capt):
                            out.append((c, t, None, False))
                        break
                if l == "Q":
                    for t in NB_D[c]:
                        if self._target_ok(board, t, p, capt):
                            out.append((c, t, None, False))
            elif l == "K":
                for t in NB_O[c]:
                    if self._target_ok(board, t, p, capt):
                        out.append((c, t, None, False))
                out.extend(self._castles(board, p, castling))
        return out

    def _castles(self, board: dict, p: int, castling):
        """King <-> rook swap.  Standard conditions: neither man has moved, the
        cells between are empty, and the king is not in, through, or into check
        (the destination is checked by the general legality filter)."""
        moves = []
        rights = [rc for (seat, rc) in castling if seat == p]
        if not rights:
            return moves
        kc = CASTLE[p]["king"]
        if board.get(kc) != (p, "K", p):
            return moves
        others = frozenset(x for x in range(3) if x != p)
        if self._attacked(board, kc, others):
            return moves                          # may not castle out of check
        for rc in rights:
            if board.get(rc) != (p, "R", p):
                continue
            between = CASTLE[p]["rooks"][rc]
            if any(x in board for x in between):
                continue
            # The king traverses `between` on its way to the rook's cell; every
            # cell it passes through must be safe.  Evaluated exactly, on a
            # board with the king and rook lifted.
            probe = dict(board)
            del probe[kc]
            del probe[rc]
            bad = False
            for x in between:
                probe[x] = (p, "K", p)
                if self._attacked(probe, x, others):
                    bad = True
                del probe[x]
                if bad:
                    break
            if not bad:
                moves.append((kc, rc, None, True))
        return moves

    def _do(self, board: dict, alive, pool, castling, mv):
        """Apply one move to the board-level state.  Returns
        (board, alive, pool, castling, captured_letter, eliminated_seat)."""
        frm, to, promo, castle = mv
        nb = dict(board)
        o, l, h = nb.pop(frm)
        if castle:
            ro, rl, rh = nb.pop(to)
            nb[to] = (o, l, h)                    # king takes the rook's cell
            nb[frm] = (ro, rl, rh)                # rook takes the king's cell
            victim = None
        else:
            victim = nb.get(to)
            nb[to] = (o, promo or l, h)
        captured = None
        eliminated = None
        npool = pool
        if victim is not None:
            vo, vl, vh = victim
            captured = vl
            if vl == "K":
                eliminated = vo
            elif vl in PROMOTABLE:
                # The physical man goes to the side of the board, where it stays
                # available as a promotion target for ITS OWN army.
                npool = tuple(tuple(sorted(x + (vl,))) if i == vh else x
                              for i, x in enumerate(npool))
        if promo is not None:
            npool = tuple(_remove_one(x, promo) if i == h else x
                          for i, x in enumerate(npool))
        nalive = alive
        if eliminated is not None:
            nalive = tuple(False if i == eliminated else a for i, a in enumerate(alive))
            # "All his remaining men pass to the player who CAPTURED the king"
            # -- who may or may not be the player who delivered the mate.  They
            # keep their original army (`home`), hence their direction of travel.
            for c, (po, pl, ph) in list(nb.items()):
                if po == eliminated:
                    nb[c] = (o, pl, ph)
        # Castling rights are only ever REMOVED -- a rook returning to its home
        # cell must never re-grant them.
        ncast = tuple((seat, rc) for (seat, rc) in castling
                      if frm != CASTLE[seat]["king"] and frm != rc and to != rc)
        return nb, nalive, npool, ncast, captured, eliminated

    def _legal(self, board: dict, alive, p: int, capt: frozenset, pool, castling,
               first_only: bool = False):
        """Pseudo-moves for `p` filtered by 'you may never leave your own king
        attacked -- by anyone'."""
        kc = self._king_cell(board, p)
        out = []
        for mv in self._pseudo(board, p, capt, pool, castling):
            nb, nalive, _np, _nc, _cap, _elim = self._do(board, alive, pool, castling, mv)
            k = mv[1] if (kc is not None and mv[0] == kc) else kc
            if k is not None:
                others = frozenset(x for x in range(3) if nalive[x] and x != p)
                if self._attacked(nb, k, others):
                    continue
            out.append(mv)
            if first_only:
                return out
        return out

    def _has_legal(self, board: dict, alive, p: int, capt: frozenset,
                   pool, castling) -> bool:
        return bool(self._legal(board, alive, p, capt, pool, castling, first_only=True))

    # ---- Game interface ---------------------------------------------------

    def current_player(self, s: WState) -> int:
        return s.turn

    def legal_moves(self, s: WState) -> list:
        if s.over:
            return []
        capt = self._mated(s.board, s.alive, s.pool, s.castling) - {s.turn}
        return sorted(self._encode(mv) for mv in
                      self._legal(s.board, s.alive, s.turn, capt, s.pool, s.castling))

    @staticmethod
    def _encode(mv) -> str:
        frm, to, promo, _castle = mv
        m = f"{cell_id(frm)}>{cell_id(to)}"
        return m + ("=" + promo if promo else "")

    def _decode(self, s: WState, move: str):
        text, _, promo = move.partition("=")
        a, _, b = text.partition(">")
        frm, to = parse_cell(a), parse_cell(b)
        pc = s.board.get(frm)
        castle = bool(pc and pc[1] == "K" and s.board.get(to) is not None
                      and s.board[to][0] == pc[0] and s.board[to][1] == "R")
        return (frm, to, promo or None, castle)

    def apply_move(self, s: WState, move: str, rng=None) -> WState:
        mv = self._decode(s, move)
        frm, to, promo, _castle = mv
        moved = s.board[frm]
        nb, nalive, npool, ncast, captured, eliminated = self._do(
            s.board, s.alive, s.pool, s.castling, mv)

        nout = s.out + (eliminated,) if eliminated is not None else s.out
        progress = (captured is not None) or moved[1] == "P" or promo is not None
        nhalf = 0 if progress else s.halfmove + 1
        nreps = {} if progress else dict(s.reps)
        nply = s.ply + 1

        alive_list = [p for p in range(3) if nalive[p]]
        over, reason, turn = False, "", s.turn

        # --- A DECISIVE RESULT OUTRANKS THE DRAW COUNTERS. -----------------
        # In THIS game the decisive event is king capture / last player
        # standing, NOT checkmate (a mate is not even terminal here).  It is
        # tested before the no-progress / repetition / ply-cap counters, so a
        # conquest on the 150th quiet ply is still a conquest.
        if len(alive_list) <= 1:
            over, reason = True, "conquest"
            turn = alive_list[0] if alive_list else s.turn
        else:
            mated = self._mated(nb, nalive, npool, ncast)
            nxt, stalemated = None, None
            for k in (1, 2, 3):
                cand = (s.turn + k) % 3
                if not nalive[cand]:
                    continue
                # A player with no legal move (checkmated, or stalemated) is
                # simply skipped -- he passes; nothing else is possible.
                if self._has_legal(nb, nalive, cand, mated - {cand}, npool, ncast):
                    nxt = cand
                    break
                # ... EXCEPT once only two players remain.  Wellisch p.329 hands
                # the surviving pair back to two-handed chess -- "spielen die
                # beiden anderen Teilnehmer ZU ZWEIT bis zum Schlusse der
                # Partie", and "Patt stellen" is named among the terms governed
                # by "dieselben sinngemaess angewendeten Vorschriften wie beim
                # Zweischach".  An ordinary stalemate is therefore a DRAW, not a
                # pass; `returns` then pays the "two finalists draw" row of his
                # own table (0 / 1.5 / 1.5).  A CHECKMATE still is not terminal
                # -- the king must actually be captured -- so only a player who
                # is NOT in check ends the game here.
                if len(alive_list) == 2 and not self._in_check(nb, nalive, cand):
                    stalemated = cand
                    break
            if stalemated is not None:
                over, reason, turn = True, "stalemate", stalemated
            elif nxt is None:
                over, reason = True, "no legal moves"
                turn = alive_list[0]
            else:
                turn = nxt

        ns = WState(board=nb, turn=turn, alive=nalive, out=nout, pool=npool,
                    castling=ncast, halfmove=nhalf, ply=nply, reps=nreps,
                    over=over, reason=reason, last=(frm, to))
        if not over:
            key = self._key(ns)
            n = nreps.get(key, 0) + 1
            nreps[key] = n
            if nhalf >= NOPROGRESS:
                ns = replace(ns, over=True, reason="no progress")
            elif n >= REPETITION:
                ns = replace(ns, over=True, reason="repetition")
            elif nply >= PLY_CAP:
                ns = replace(ns, over=True, reason="ply cap")
        return ns

    @staticmethod
    def _key(s: WState) -> str:
        men = ";".join(f"{c[0]},{c[1]}:{o}{l}{h}"
                       for c, (o, l, h) in sorted(s.board.items()))
        cast = ",".join(f"{p}/{rc[0]},{rc[1]}" for p, rc in s.castling)
        return f"{men}|{s.turn}|{cast}|{''.join('1' if a else '0' for a in s.alive)}"

    def is_terminal(self, s: WState) -> bool:
        return s.over

    def returns(self, s: WState) -> list:
        """Wellisch's own scoring table (p. 329): three points per game,
        distributed over the 1st eliminated / 2nd / survivor.

            no draw                 0    1     2
            the two finalists draw  0    1.5   1.5
            all three draw          1    1     1
        """
        if not s.over:
            return [0.0, 0.0, 0.0]
        pts = [0.0, 0.0, 0.0]
        if len(s.out) >= 2:                       # decided: 0 / 1 / 2
            pts[s.out[0]] = 0.0
            pts[s.out[1]] = 1.0
            for p in range(3):
                if p not in s.out:
                    pts[p] = 2.0
        elif len(s.out) == 1:                     # one out, the finalists drew
            pts[s.out[0]] = 0.0
            for p in range(3):
                if p != s.out[0]:
                    pts[p] = 1.5
        else:                                     # all three drew
            pts = [1.0, 1.0, 1.0]
        return pts

    # ---- bot eval ---------------------------------------------------------

    def heuristic(self, s: WState) -> list:
        """Material share, as a LIST of per-seat payoffs on the same 0..3 scale
        as `returns` (a bare float raises `TypeError: 'float' object is not
        subscriptable` in MCTS back-propagation -- see SPEC.md)."""
        mat = [0.0, 0.0, 0.0]
        for _c, (o, l, _h) in s.board.items():
            mat[o] += PIECE_VALUE[l]
        fixed = {}
        if len(s.out) >= 1:
            fixed[s.out[0]] = 0.0
        if len(s.out) >= 2:
            fixed[s.out[1]] = 1.0
        left = [p for p in range(3) if p not in fixed]
        budget = 3.0 - sum(fixed.values())
        total = sum(mat[p] for p in left)
        pts = [0.0, 0.0, 0.0]
        for p, v in fixed.items():
            pts[p] = v
        for p in left:
            pts[p] = budget * (mat[p] / total if total else 1.0 / len(left))
        return pts

    # ---- persistence ------------------------------------------------------

    def serialize(self, s: WState) -> dict:
        return {
            "board": {cell_id(c): [o, l, h] for c, (o, l, h) in sorted(s.board.items())},
            "turn": s.turn,
            "alive": list(s.alive),
            "out": list(s.out),
            "pool": [list(x) for x in s.pool],
            "castling": [[p, cell_id(rc)] for p, rc in s.castling],
            "halfmove": s.halfmove,
            "ply": s.ply,
            "reps": dict(s.reps or {}),
            "over": s.over,
            "reason": s.reason,
            "last": [cell_id(s.last[0]), cell_id(s.last[1])] if s.last else None,
        }

    def deserialize(self, d: dict) -> WState:
        board = {parse_cell(k): (v[0], v[1], v[2]) for k, v in d["board"].items()}
        return WState(
            board=board,
            turn=d["turn"],
            alive=tuple(bool(x) for x in d["alive"]),
            out=tuple(d["out"]),
            pool=tuple(tuple(x) for x in d["pool"]),
            castling=tuple(sorted((p, parse_cell(rc)) for p, rc in d["castling"])),
            halfmove=d["halfmove"],
            ply=d["ply"],
            reps=dict(d.get("reps") or {}),
            over=d["over"],
            reason=d.get("reason", ""),
            last=(parse_cell(d["last"][0]), parse_cell(d["last"][1])) if d.get("last") else None,
        )

    # ---- notation ---------------------------------------------------------

    def describe_move(self, s: WState, move: str) -> str:
        mv = self._decode(s, move)
        frm, to, promo, castle = mv
        pc = s.board.get(frm)
        if pc is None:
            return move
        _o, l, h = pc
        if castle:
            near = CASTLE[_o]["rooks"].get(to) == ()
            txt = "O-O" if near else "O-O-O"
        else:
            victim = s.board.get(to)
            if frm == to:                          # delayed promotion in place
                txt = f"{cell_name(to)}={promo}"
                return txt
            sep = "x" if victim else "-"
            piece = "" if l == "P" else l
            txt = f"{piece}{cell_name(frm)}{sep}{cell_name(to)}"
            if promo:
                txt += "=" + promo
        ns = self.apply_move(s, move)
        if ns.out != s.out:
            gone = ns.out[-1]
            txt += (f" (takes {SEAT_NAMES[gone]}'s King — {SEAT_NAMES[gone]} eliminated, "
                    f"army passes to {SEAT_NAMES[_o]})")
            return txt
        mated = self._mated(ns.board, ns.alive, ns.pool, ns.castling)
        checked = [p for p in range(3)
                   if ns.alive[p] and p != _o and self._in_check(ns.board, ns.alive, p)]
        if checked:
            marks = "".join(SEAT_NAMES[p][0] for p in sorted(checked))
            txt += "#" + marks if any(p in mated for p in checked) else "+" + marks
        return txt

    # ---- render -----------------------------------------------------------

    # Wellisch's board is three-coloured (yellow / black / red).  Muted so the
    # seat colours of the men stay legible on top.
    SHADES = {1: "#e2c88c", 2: "#7d6a55", 0: "#b98a63"}

    def render(self, s: WState, perspective: Optional[int] = None) -> dict:
        pieces = [{"cell": cell_id(c), "owner": o, "label": l}
                  for c, (o, l, _h) in sorted(s.board.items())]
        highlights = []
        if s.last:
            highlights = [{"cell": cell_id(s.last[0]), "kind": "last-move"},
                          {"cell": cell_id(s.last[1]), "kind": "last-move"}]
        tints = {cell_id(c): self.SHADES[cell_colour(*c)] for c in CELLS}
        return {
            "board": {"type": "hex", "shape": "hexagon", "size": RADIUS + 1,
                      # POINTY-TOP (the platform default): Wellisch's cells have
                      # their corners turned toward the players, so his lettered
                      # rows are horizontal.  He explicitly REJECTED the flat-top
                      # board (his Fig. 4) as having no well-defined last row.
                      "tints": tints},
            "pieces": pieces,
            "highlights": highlights,
            "caption": self._caption(s),
            "pieceset": "chess",
        }

    def _caption(self, s: WState) -> str:
        if s.over:
            pts = self.returns(s)
            order = sorted(range(3), key=lambda p: -pts[p])
            score = ", ".join(f"{SEAT_NAMES[p]} {pts[p]:g}" for p in order)
            return f"Game over ({s.reason}) — {score}"
        bits = [f"{SEAT_NAMES[s.turn]} ({SEAT_GERMAN[s.turn]}, "
                f"{SEAT_WHERE[s.turn]}) to move"]
        mated = self._mated(s.board, s.alive, s.pool, s.castling)
        for p in range(3):
            if not s.alive[p]:
                bits.append(f"{SEAT_NAMES[p]} eliminated")
            elif p in mated:
                bits.append(f"{SEAT_NAMES[p]} is checkmated — his king may be captured")
            elif self._in_check(s.board, s.alive, p):
                bits.append(f"{SEAT_NAMES[p]} in check")
        lost = [f"{SEAT_NAMES[p]}: {'/'.join(s.pool[p]) if s.pool[p] else '—'}"
                for p in range(3)]
        bits.append("promotion pool  " + "  ".join(lost))
        return " · ".join(bits)


def _remove_one(seq, letter):
    out = list(seq)
    out.remove(letter)
    return tuple(out)
