#!/usr/bin/env python3
"""Differential harness: this package vs. the AbstractPlay `gameslib` oracle.

MANUAL / ONE-TIME — this is NOT part of the test suite (it needs node + a
checkout of https://github.com/AbstractPlay/gameslib, which is MIT-licensed and
used here purely as a rule-enforcing oracle; no code from it was copied).

Usage:
    AP_GAMESLIB=/path/to/gameslib python3 _diff_ap.py --games 400 --seed 1

It writes a small TypeScript driver (`lielow_oracle.ts`) into the gameslib
checkout, runs it under ts-node as a line-oriented JSON co-process, and plays
random games in LOCKSTEP through both implementations.  At **every** ply it
compares, in a coordinate system it converts explicitly:

  * the set of legal moves as (from-cell, to-cell) pairs, where `to` is the
    literal string "off" for a stack that walks past the edge — *sets of cells,
    never raw move strings*, so the comparison survives either side changing its
    notation;
  * every stack: its square, its owner and its HEIGHT;
  * where each player's crown sits (this is the subtle rule — it only moves to a
    *unique* tallest stack, and otherwise stays where it was);
  * the side to move, terminality and the winner.

AbstractPlay's `moves()` is *not* guaranteed to be the legal-move list (in wave 13
`manalath.ts` was found over-reporting), so every oracle move is additionally run
through the oracle's own `validateMove` and any disagreement between the two is
reported.

Coordinate mapping (verified on every run by ``check_mapping``, which is
deliberately NOT behind a flag): AbstractPlay uses algebraic `a1`..`h8`; we use
`"c,r"` with c = file - 'a' (0..7) and r = rank - 1 (0..7, increasing north).
AP player 1 (which starts on rank 2 and moves first) is our seat 0.
"""

from __future__ import annotations

import argparse
import json
import os
import random
import subprocess
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[2]))
from agp.loader import load_from_dir  # noqa: E402

HERE = Path(__file__).resolve().parent

DRIVER = r'''// AUTO-GENERATED by engine/games/lielow/_diff_ap.py -- do not edit.
// Line-oriented JSON oracle driver for AbstractPlay's Lielow implementation.
import * as readline from "readline";
import { GameFactory } from "./src/games";

function toId(cell: string): string {
    const c = cell.charCodeAt(0) - 97;
    const r = parseInt(cell.slice(1), 10) - 1;
    return `${c},${r}`;
}

// eslint-disable-next-line @typescript-eslint/no-explicit-any
let g: any = GameFactory("lielow");

function parseMove(m: string): [string, string] {
    const [from, to] = m.split(/[-x]/);
    return [toId(from), to === "off" ? "off" : toId(to)];
}

function snapshot() {
    const raw: string[] = g.gameover ? [] : g.moves();
    const validated: string[] = raw.filter((m: string) => g.validateMove(m).valid);
    const board: [string, number, number][] =
        [...g.board.entries()].map((e: [string, [number, number]]) =>
            [toId(e[0]), e[1][0], e[1][1]] as [string, number, number]);
    board.sort();
    const kings = [...g.kingPos].map((k: string | undefined) =>
        k === undefined ? "none" : k === "dead" ? "dead" : toId(k));
    const norm = (lst: string[]) => {
        const out = lst.map(parseMove).map(p => p.join(">"));
        out.sort();
        return out;
    };
    return {
        board,
        kings,
        toMove: g.currplayer,
        moves: norm(validated),
        rawMoves: norm(raw),
        gameover: g.gameover,
        winner: [...g.winner],
    };
}

const rl = readline.createInterface({ input: process.stdin });
rl.on("line", (line: string) => {
    line = line.trim();
    if (line.length === 0) { return; }
    const req = JSON.parse(line);
    try {
        if (req.cmd === "reset") { g = GameFactory("lielow"); }
        else if (req.cmd === "move") { g.move(req.m); }
        else if (req.cmd === "quit") { process.exit(0); }
        process.stdout.write(JSON.stringify({ ok: true, ...snapshot() }) + "\n");
    } catch (e) {
        process.stdout.write(JSON.stringify({ ok: false, error: (e as Error).message }) + "\n");
    }
});
'''

SIZE = 8
NO_KING, DEAD = -1, -2


def alg(cid: str) -> str:
    c, r = (int(x) for x in cid.split(","))
    return f"{chr(ord('a') + c)}{r + 1}"


def parse_id(cid: str) -> int:
    c, r = (int(x) for x in cid.split(","))
    return r * SIZE + c


class Oracle:
    def __init__(self, root: Path):
        (root / "lielow_oracle.ts").write_text(DRIVER)
        self.p = subprocess.Popen(
            ["npx", "ts-node", "--transpileOnly",
             "--compilerOptions", '{"module":"commonjs"}', "lielow_oracle.ts"],
            cwd=str(root), stdin=subprocess.PIPE, stdout=subprocess.PIPE, text=True)

    def send(self, **req) -> dict:
        self.p.stdin.write(json.dumps(req) + "\n")
        self.p.stdin.flush()
        line = self.p.stdout.readline()
        if not line:
            raise RuntimeError("oracle died")
        d = json.loads(line)
        if not d.get("ok"):
            raise RuntimeError("oracle error: " + d.get("error", "?"))
        return d

    def close(self):
        try:
            self.p.stdin.write('{"cmd":"quit"}\n')
            self.p.stdin.flush()
        except Exception:
            pass
        self.p.wait(timeout=10)


def our_moves(g, s) -> list:
    """Our legal moves as sorted "from>to" ids.  Both sides already spell a
    walk-off as the literal "off", so this is a pure re-sort — the point is that
    the comparison is over CELL IDS, not over either side's move syntax."""
    out = []
    for m in g.legal_moves(s):
        frm, _, to = m.partition(">")
        assert to == "off" or to != frm, f"self-path move {m!r}"
        out.append(f"{frm}>{to}")
    return sorted(out)


def our_board(s) -> list:
    """[[cellid, ap_player, height], …] sorted — same shape the oracle emits."""
    out = []
    for i, v in enumerate(s.board):
        if v:
            out.append([f"{i % SIZE},{i // SIZE}", 1 if v > 0 else 2, abs(v)])
    return sorted(out)


def our_kings(s) -> list:
    out = []
    for k in s.king:
        out.append("none" if k == NO_KING else "dead" if k == DEAD
                   else f"{k % SIZE},{k // SIZE}")
    return out


def check_mapping(g, s, orc):
    """Guard against a vacuous differential: assert the coordinate conversion
    agrees on hand-checked, ASYMMETRIC facts, so a mirrored mapping cannot make
    both sides agree about the wrong board."""
    d = orc.send(cmd="reset")
    # AP player 1 starts on rank 2 (a2..h2) -- our seat 0 on row 1.
    assert d["board"] == sorted([[f"{c},1", 1, 1] for c in range(SIZE)]
                                + [[f"{c},6", 2, 1] for c in range(SIZE)]), d["board"]
    ours = our_board(s)
    assert ours == d["board"], (ours, d["board"])
    assert d["toMove"] == 1 and s.to_move == 0
    # Direction check: a2->a3 is NORTH (towards rank 8) for AP; ours is 0,1->0,2
    # (row increasing).  A flipped row axis would land on rank 1 instead.
    d = orc.send(cmd="move", m="a2-a3")
    assert ["0,2", 1, 2] in d["board"] and d["kings"][0] == "0,2", d
    s2 = g.apply_move(s, "0,1>0,2")
    assert our_board(s2) == d["board"], (our_board(s2), d["board"])
    assert our_kings(s2) == d["kings"], (our_kings(s2), d["kings"])
    print("coordinate mapping OK: AP a2 == our 0,1 (seat 0, rank 2, moves first); "
          "AP north == our +row; AP a2-a3 grows the stack to height 2 and crowns it")
    orc.send(cmd="reset")


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--games", type=int, default=400)
    ap.add_argument("--seed", type=int, default=1)
    ap.add_argument("--gameslib", default=os.environ.get("AP_GAMESLIB", ""))
    ap.add_argument("--capture-bias", type=float, default=0.5,
                    help="probability of preferring a capture when one exists. "
                         "UNIFORM random play almost never captures (it walks its "
                         "own stacks off the edge instead), so it barely exercises "
                         "the capture reset, the crown re-accession that follows a "
                         "capture, or the win-by-crown-capture itself.  Run both "
                         "0.0 and a positive value.")
    args = ap.parse_args()
    if not args.gameslib:
        sys.exit("set AP_GAMESLIB (or --gameslib) to a gameslib checkout")

    _man, g = load_from_dir(HERE)
    orc = Oracle(Path(args.gameslib))
    rng = random.Random(args.seed)
    positions = mismatches = plies = 0
    overreports = 0
    bearoffs = captures = 0
    results = {"0": 0, "1": 0, "draw": 0}
    ends = {"crown captured": 0, "walked off": 0}
    maxheight = 0

    try:
        s0 = g.initial_state()
        check_mapping(g, s0, orc)
        for gi in range(args.games):
            s = g.initial_state()
            d = orc.send(cmd="reset")
            while True:
                positions += 1
                probs = []
                om, am = our_moves(g, s), d["moves"]
                if om != am:
                    only_o = sorted(set(om) - set(am))
                    only_a = sorted(set(am) - set(om))
                    probs.append(f"moves: only-ours {only_o} only-AP {only_a}")
                if d["moves"] != d["rawMoves"]:
                    overreports += 1
                    probs.append("AP moves() disagrees with its own validateMove: "
                                 f"{sorted(set(d['rawMoves']) - set(d['moves']))}")
                ob = our_board(s)
                if ob != d["board"]:
                    probs.append(f"board: {ob} vs {d['board']}")
                if our_kings(s) != d["kings"]:
                    probs.append(f"crowns: {our_kings(s)} vs {d['kings']}")
                if s.to_move + 1 != d["toMove"]:
                    probs.append(f"to move: {s.to_move + 1} vs {d['toMove']}")
                if g.is_terminal(s) != d["gameover"]:
                    probs.append(f"gameover: {g.is_terminal(s)} vs {d['gameover']}")
                if g.is_terminal(s):
                    win = {0: [1], 1: [2], None: [1, 2]}[s.winner]
                    if win != d["winner"]:
                        probs.append(f"winner: {win} vs {d['winner']}")
                if probs:
                    mismatches += 1
                    print(f"MISMATCH game {gi} ply {s.ply}: " + "; ".join(probs),
                          file=sys.stderr)
                    break
                for _, _, h in ob:
                    maxheight = max(maxheight, h)
                if g.is_terminal(s):
                    results["draw" if s.winner is None else str(s.winner)] += 1
                    if s.winner is not None and s.last is not None:
                        ends["walked off" if s.last[0] == s.last[1]
                             else "crown captured"] += 1
                    break
                lm = g.legal_moves(s)
                if args.capture_bias > 0 and rng.random() < args.capture_bias:
                    caps = [x for x in lm
                            if x.partition(">")[2] != "off"
                            and s.board[parse_id(x.partition(">")[2])] != 0]
                    if caps:
                        lm = caps
                m = rng.choice(lm)
                frm, _, to = m.partition(">")
                if to == "off":
                    apm = f"{alg(frm)}-off"
                    bearoffs += 1
                else:
                    cap = s.board[parse_id(to)] != 0
                    apm = f"{alg(frm)}{'x' if cap else '-'}{alg(to)}"
                    captures += cap
                d = orc.send(cmd="move", m=apm)
                s = g.apply_move(s, m)
                plies += 1
            if (gi + 1) % 50 == 0:
                print(f"  {gi + 1} games, {positions} positions, "
                      f"{mismatches} mismatches", file=sys.stderr)
    finally:
        orc.close()

    print(f"games={args.games} positions={positions} plies={plies} "
          f"bearoffs={bearoffs} captures={captures} maxheight={maxheight} "
          f"ap_overreports={overreports} mismatches={mismatches} results={results} "
          f"ends={ends}")
    return 1 if mismatches else 0


if __name__ == "__main__":
    sys.exit(main())
