#!/usr/bin/env python3
"""Differential test: our Manalath vs the AbstractPlay `gameslib` oracle.

MANUAL / ONE-TIME TOOL — not part of the pure-stdlib test suite (it shells out
to node/ts-node).  `selftest.py` carries the frozen anchors this harness
produced.

AbstractPlay's `gameslib` (MIT, https://github.com/AbstractPlay/gameslib) ships a
rule-ENFORCING Manalath implementation at `src/games/manalath.ts`.  It is used
here as an ORACLE ONLY: we read it to settle rule questions and play lockstep
random games against it.  No code is copied.

Usage
-----
    export AP_GAMESLIB=/path/to/gameslib      # a checkout with node_modules
    python3 _diff_ap.py --games 200 --seed 777
    python3 _diff_ap.py --write-driver        # just dump the TS driver

What is compared, at EVERY ply of every game:
  * the LEGAL-MOVE SET (as covered (cell, colour) pairs -- never as move
    strings, whose notations differ), mapped through the verified
    algebraic <-> axial bijection;
  * whether the position is terminal;
  * the winner (seat 0 / seat 1 / draw).

Two deliberate deviations from the oracle, both documented in rules.md:

1.  gameslib's `moves()` has a transcription bug (`src/games/manalath.ts`, the
    `valid` filter): the "no group larger than 5" test is applied to player 1's
    groups but the player-2 term is a bare array (always truthy) instead of a
    `.length === 0` test.  So `moves()` over-reports: it lists placements that
    build an oversized BLUE ("black") group.  gameslib's own `validateMove()`
    and therefore `move()` reject those, so real play is unaffected.  We compare
    against `raw.filter(validateMove)` and separately COUNT the over-reports.

2.  On a pass, gameslib checks the double-pass draw BEFORE the end conditions;
    we check the end conditions first (the designer's rules say an end condition
    "may become effective" even on a pass).  The two orders are provably
    equivalent on reachable positions -- see rules.md -- and the differential
    has never separated them.
"""

from __future__ import annotations

import argparse
import json
import os
import re
import subprocess
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[2]))

from agp.loader import load_from_dir  # noqa: E402

HERE = Path(__file__).resolve().parent

DRIVER_NAME = "_agp_manalath_driver.ts"
DRIVER_TS = r"""
// AUTO-GENERATED by engine/games/manalath/_diff_ap.py -- safe to delete.
// Random-playout dump for the Manalath oracle. One JSON object per line:
//   line 1      {"graph": {cell: [neighbours...]}}
//   lines 2..N  {"plies": [...], "final": {...}}
import { GameFactory } from "./src/games";
import { HexTriGraph } from "./src/common/graphs";

const NGAMES = parseInt(process.argv[2] || "50", 10);
let seed = parseInt(process.argv[3] || "12345", 10) >>> 0;
function rnd(): number {           // xorshift32
    seed ^= seed << 13; seed >>>= 0;
    seed ^= seed >>> 17;
    seed ^= seed << 5;  seed >>>= 0;
    return seed / 4294967296;
}

const graph = new HexTriGraph(5, 9);
const gcells = graph.listCells() as string[];
const adj: Record<string, string[]> = {};
for (const c of gcells) { adj[c] = graph.neighbours(c).slice().sort(); }
console.log(JSON.stringify({ graph: adj }));

for (let i = 0; i < NGAMES; i++) {
    const g: any = GameFactory("manalath");
    const plies: any[] = [];
    let guard = 0;
    while (!g.gameover) {
        if (++guard > 200) { throw new Error("oracle did not terminate"); }
        const raw: string[] = g.moves();
        const valid = raw.filter((m: string) => m === "pass" || g.validateMove(m).valid);
        const board: Record<string, number> = {};
        for (const [k, v] of g.board.entries()) { board[k] = v; }
        const played = valid[Math.floor(rnd() * valid.length)];
        plies.push({ board, cp: g.currplayer, moves: valid, raw: raw.length, played });
        g.move(played);
    }
    const fboard: Record<string, number> = {};
    for (const [k, v] of g.board.entries()) { fboard[k] = v; }
    console.log(JSON.stringify({
        plies,
        final: { board: fboard, cp: g.currplayer, gameover: g.gameover, winner: g.winner },
    }));
}
"""

CASES_NAME = "_agp_manalath_cases.ts"
CASES_TS = r"""
// AUTO-GENERATED by engine/games/manalath/_diff_ap.py -- safe to delete.
// Constructed-position probes.  These settle the rule questions that random
// play answers only statistically; the expected verdicts are asserted (in our
// own coordinates) by selftest.py, which cites each case by letter.
//   HexTriGraph(5,9) names <-> our axial ids used below:
//     a1..a5 = (-4..0, 4)   e1..e9 = (-4..4, 0)   i1..i5 = (0..4, -4)
import { GameFactory } from "./src/games";

function mk(setup: [string, number][], cp: number): any {
    const g: any = GameFactory("manalath");
    for (const [c, p] of setup) { g.board.set(c, p); }
    g.currplayer = cp;
    return g;
}
const W = 1, B = 2;

function play(label: string, setup: [string, number][], cp: number, mv: string) {
    const g = mk(setup, cp);
    try {
        g.move(mv);
        console.log(`${label}: gameover=${g.gameover} winner=[${g.winner}]`);
    } catch (e) {
        console.log(`${label}: THREW ${(e as Error).message}`);
    }
}
function check(label: string, setup: [string, number][], cp: number, mvs: string[]) {
    const g = mk(setup, cp);
    console.log(`${label}: ` + mvs.map(m => `${m}=${g.validateMove(m).valid}`).join(" "));
}

// A) win on your own quint (3 + gap + 1 -> 5)                       -> [1]
play("A win-on-quint", [["e3",W],["e4",W],["e5",W],["e7",W]], W, "e6w");
// B) lose on your own quart                                          -> [2]
play("B lose-on-quart", [["e3",W],["e4",W],["e5",W]], W, "e6w");
// C1) building an ENEMY quart on your own turn is harmless           -> false
play("C1 enemy-quart-harmless", [["e3",B],["e4",B],["e5",B]], W, "e6b");
// C2) ... and fatal at the end of the enemy's own next turn          -> [1]
play("C2 enemy-quart-fatal", [["e3",B],["e4",B],["e5",B],["e6",B]], B, "i5w");
// D) the designer's worked example: a PRE-EXISTING friendly quart
//    outranks a freshly built friendly quint                         -> [2]
play("D pre-quart>new-quint", [["a1",W],["a2",W],["a3",W],["a4",W],["i1",W],["i2",W],["i3",W],["i5",W]], W, "i4w");
// E) a PRE-EXISTING friendly quint outranks a fresh friendly quart   -> [1]
play("E pre-quint>new-quart", [["a1",W],["a2",W],["a3",W],["a4",W],["a5",W],["i1",W],["i2",W],["i3",W]], W, "i4w");
// F) a friendly quart CAN be averted by absorbing it into a quint    -> [1]
play("F avert-quart", [["e3",W],["e4",W],["e5",W],["e6",W]], W, "e7w");
// G) the >5 cap is a LEGALITY rule and applies to BOTH colours   -> false true
check("G quint-cap", [["e3",W],["e4",W],["e5",W],["e6",W],["e7",W]], W, ["e8w","e8b"]);
// H) joining a 3-group and a 2-group would be 6 -> illegal       -> false true
check("H merge-6", [["e2",W],["e3",W],["e4",W],["e6",W],["e7",W]], W, ["e5w","e5b"]);
// I) joining a 3-group and a 1-group is exactly 5 -> legal        -> true true
check("I merge-5", [["e2",W],["e3",W],["e4",W],["e6",W]], W, ["e5w","e5b"]);
// J) BOTH pre-existing conditions at once (unreachable in real play):
//    the quart decides                                               -> [2]
play("J pre-quart+pre-quint", [["a1",W],["a2",W],["a3",W],["a4",W],["i1",W],["i2",W],["i3",W],["i4",W],["i5",W]], W, "e5b");
"""


# --------------------------------------------------------------------------- #
# Coordinate mapping.  gameslib names cells with HexTriGraph(5, 9) algebraic
# labels: rows 'a' (bottom, 5 cells) .. 'e' (middle, 9 cells) .. 'i' (top, 5).
# Our board is axial (q, r) over the hexhex of side 5 (max |coord| = 4).
#     r = 4 - rowIndex          rowIndex = ord(letter) - ord('a')
#     q = (number - 1) + max(-4, -4 - r)
# `verify_mapping` proves this is an adjacency-preserving bijection against the
# oracle's OWN graph dump, so the differential can never pass vacuously.
# --------------------------------------------------------------------------- #
_CELL_RE = re.compile(r"^([a-i])(\d+)$")


def ap2axial(name: str):
    m = _CELL_RE.match(name)
    if m is None:
        raise ValueError(f"not an AP cell name: {name!r}")
    r = 4 - (ord(m.group(1)) - ord("a"))
    q = (int(m.group(2)) - 1) + max(-4, -4 - r)
    return q, r


def _hexhex(n=4):
    return {(q, r) for q in range(-n, n + 1) for r in range(-n, n + 1)
            if abs(q) <= n and abs(r) <= n and abs(-q - r) <= n}


def _nb(c):
    q, r = c
    return {(q + 1, r), (q - 1, r), (q, r + 1), (q, r - 1),
            (q + 1, r - 1), (q - 1, r + 1)}


def verify_mapping(graph: dict) -> None:
    board = _hexhex()
    mapped = {c: ap2axial(c) for c in graph}
    if len(graph) != 61:
        raise AssertionError(f"oracle graph has {len(graph)} cells, expected 61")
    if set(mapped.values()) != board:
        raise AssertionError("algebraic->axial map is not a bijection onto hexhex-4")
    bad = [c for c, ns in graph.items()
           if {mapped[n] for n in ns} != (_nb(mapped[c]) & board)]
    if bad:
        raise AssertionError(f"algebraic->axial map breaks adjacency at {bad}")
    print(f"  mapping verified: 61 cells, bijection onto hexhex-4, "
          f"all {sum(len(v) for v in graph.values())//2} edges preserved")


def ap_move(m: str):
    """AP move string -> our move string."""
    if m == "pass":
        return "pass"
    cell, colour = m[:-1], m[-1]
    q, r = ap2axial(cell)
    return f"{'R' if colour == 'w' else 'B'}@{q},{r}"


# --------------------------------------------------------------------------- #
def run_driver(gameslib: Path, games: int, seed: int) -> list:
    drv = gameslib / DRIVER_NAME
    drv.write_text(DRIVER_TS)
    cmd = ["npx", "ts-node", "--transpileOnly",
           "--compilerOptions", '{"module":"commonjs"}',
           DRIVER_NAME, str(games), str(seed)]
    print(f"  running oracle: {' '.join(cmd)}  (cwd={gameslib})")
    out = subprocess.run(cmd, cwd=gameslib, capture_output=True, text=True)
    if out.returncode != 0:
        sys.stderr.write(out.stderr[-4000:])
        raise SystemExit("oracle driver failed")
    return [json.loads(l) for l in out.stdout.splitlines() if l.startswith("{")]


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--games", type=int, default=200)
    ap.add_argument("--seed", type=int, default=777)
    ap.add_argument("--gameslib", default=os.environ.get("AP_GAMESLIB"))
    ap.add_argument("--write-driver", action="store_true")
    ap.add_argument("--cases", action="store_true",
                    help="run the constructed-position probes instead of random games")
    ap.add_argument("--jsonl", help="read a previously captured dump instead of running node")
    args = ap.parse_args()

    if args.write_driver:
        target = Path(args.gameslib or ".") / DRIVER_NAME
        target.write_text(DRIVER_TS)
        (Path(args.gameslib or ".") / CASES_NAME).write_text(CASES_TS)
        print(f"wrote {target} and {CASES_NAME}")
        return 0

    if args.cases:
        if not args.gameslib:
            raise SystemExit("set AP_GAMESLIB (or pass --gameslib) to a gameslib checkout")
        gl = Path(args.gameslib)
        (gl / CASES_NAME).write_text(CASES_TS)
        out = subprocess.run(
            ["npx", "ts-node", "--transpileOnly", "--compilerOptions",
             '{"module":"commonjs"}', CASES_NAME],
            cwd=gl, capture_output=True, text=True)
        sys.stdout.write(out.stdout)
        sys.stderr.write(out.stderr[-2000:])
        return out.returncode

    if args.jsonl:
        records = [json.loads(l) for l in Path(args.jsonl).read_text().splitlines() if l.startswith("{")]
    else:
        if not args.gameslib:
            raise SystemExit("set AP_GAMESLIB (or pass --gameslib) to a gameslib checkout")
        records = run_driver(Path(args.gameslib), args.games, args.seed)

    if not records or "graph" not in records[0]:
        raise SystemExit("oracle produced no graph line -- refusing to report a vacuous pass")
    graph = records[0]["graph"]
    verify_mapping(graph)
    if len(records) < 2:
        raise SystemExit("oracle produced 0 games -- refusing to report a vacuous pass")

    _man, game = load_from_dir(HERE)

    n_pos = n_games = n_moves = 0
    over_reported = 0          # oracle moves() entries rejected by its own validateMove
    mismatches = []
    outcomes = {"seat0": 0, "seat1": 0, "draw": 0}
    passes = 0
    # how the decisive result arose, measured on OUR side
    causes = {"own-quint": 0, "own-quart": 0, "pre-quint": 0, "pre-quart": 0, "draw": 0}

    for rec in records[1:]:
        n_games += 1
        s = game.initial_state()
        for ply in rec["plies"]:
            n_pos += 1
            # --- board agreement -------------------------------------------
            ap_board = {ap2axial(k): (0 if v == 1 else 1) for k, v in ply["board"].items()}
            if s.board != ap_board:
                mismatches.append(("board", n_games, ply))
                break
            # --- side to move ----------------------------------------------
            if s.to_move != ply["cp"] - 1:
                mismatches.append(("to_move", n_games, ply))
                break
            # --- terminality -----------------------------------------------
            if game.is_terminal(s):
                mismatches.append(("terminal-early", n_games, ply))
                break
            # --- legal-move set --------------------------------------------
            ours = set(game.legal_moves(s))
            theirs = {ap_move(m) for m in ply["moves"]}
            if ours != theirs:
                mismatches.append(("moves", n_games, sorted(ours ^ theirs)[:8], ply["board"]))
                break
            n_moves += len(ours)
            over_reported += ply["raw"] - len(ply["moves"])
            mv = ap_move(ply["played"])
            if mv == "pass":
                passes += 1
            # --- classify the cause of a decisive move (our side) ----------
            before = s
            s = game.apply_move(s, mv)
            if s.over and s.winner is not None:
                mover = before.to_move
                placed = s.last
                grps = [g for g in _our_groups(game, s, mover)]
                cur = next((g for g in grps if placed is not None and placed in g), None)
                others = [g for g in grps if g is not cur]
                if any(len(g) == 4 for g in others):
                    causes["pre-quart"] += 1
                elif any(len(g) == 5 for g in others):
                    causes["pre-quint"] += 1
                elif cur is not None and len(cur) == 4:
                    causes["own-quart"] += 1
                elif cur is not None and len(cur) == 5:
                    causes["own-quint"] += 1
        else:
            # --- final position --------------------------------------------
            fin = rec["final"]
            ap_board = {ap2axial(k): (0 if v == 1 else 1) for k, v in fin["board"].items()}
            if s.board != ap_board:
                mismatches.append(("final-board", n_games, fin))
            if not game.is_terminal(s):
                mismatches.append(("not-terminal", n_games, fin))
            w = fin["winner"]
            ap_winner = None if len(w) != 1 else w[0] - 1
            if s.winner != ap_winner:
                mismatches.append(("winner", n_games, s.winner, ap_winner, fin))
            if s.winner is None:
                outcomes["draw"] += 1
                causes["draw"] += 1
            else:
                outcomes[f"seat{s.winner}"] += 1
            if game.legal_moves(s) != []:
                mismatches.append(("terminal-has-moves", n_games, fin))
            continue
        # (a break above lands here)

    print(f"\n  games                : {n_games}")
    print(f"  positions compared   : {n_pos}")
    print(f"  legal moves compared : {n_moves}")
    print(f"  passes seen          : {passes}")
    print(f"  oracle moves() over-reports (its own validateMove rejected): {over_reported}")
    print(f"  outcomes             : {outcomes}")
    print(f"  decisive causes      : {causes}")
    print(f"  MISMATCHES           : {len(mismatches)}")
    for m in mismatches[:10]:
        print("   ", m)
    return 1 if mismatches else 0


def _our_groups(game, s, colour):
    mod = sys.modules[type(game).__module__]
    return mod._groups(s.board, s.side, colour)


if __name__ == "__main__":
    raise SystemExit(main())
