"""Nutty Shogi -- H. G. Muller's "demagnified Tenjiku Shogi": a 13x13
large-shogi variant, 50 pieces a side of 25 types, DROP-LESS, won by CAPTURING
or BURNING the enemy King.

Authoritative source (implementation-grade, followed exactly, overrides all
briefs): https://www.chessvariants.com/rules/nutty-shogi  (H. G. Muller, last
revised by A. M. DeWitt). Its Interactive-Diagram Betza block gives the exact
per-piece move strings + the exact initial squares; its rules prose defines the
Fire-Demon burning, jumping-general rank rules, Lion/Griffon/Harpy, Tetrarchs
and Eagle/Unicorn special mechanics.

Modelled on games/chu_shogi and games/dai_shogi (drop-less, no-check,
king-capture ShogiLike subclasses with a full Lion engine). Key facts:

* **Board 13x13**, files a-m (col 0-12), ranks 1-13 (row 0-12). Player 0 =
  Sente (Black) at the bottom, advancing +row.
* **DROP-LESS** (no reserve / hand / '@' moves).
* **Win as event** -- the King is the sole royal and does NOT promote; the game
  ends the instant a King is captured OR burned by a Fire Demon (in either
  player's turn). Movegen is pseudo-legal (a side MAY leave its own King
  attacked); ``winner`` is stored when a King leaves the board. Stalemate (no
  legal move) loses (CVP ``stalemate=win``).
* **Promotion**: zone = far FOUR ranks. Optional at end of turn when a piece
  ENTERS the zone (start outside -> end inside) OR when it STARTS inside the
  zone AND captures. Each promotable type has ONE predefined promoted form.
  22 types promote; King, Fire Demon and Regent do not.
* **Repetition / draws**: fourfold repetition of (position + side to move) or a
  hard ply cap -> an honest draw. CVP's intent-based perpetual-check /
  perpetual-chase loss rules are a documented simplification (see rules.md).

25 piece types (internal letters == CVP diagram ids):
  P pawn, D dog, S silver, FL ferocious leopard, G gold, BT tiger,
  N knight (shogi ffN), KY kirin, PH phoenix, L lance, VM vertical mover,
  SS soldier, B bishop, R rook, DH crowned bishop, DK castle, LN lion,
  Q queen, BG jumping bishop, RG jumping rook, CS chariot, WB buffalo,
  VG regent, K king, FD fire demon.
"""

from __future__ import annotations

import math
from dataclasses import dataclass

from agp.shogilike import ShogiLike, SState, BLACK, WHITE, cell

# ---------------------------------------------------------------- directions
# All in Black's forward frame: forward = +row (toward the enemy).
F, B = (0, 1), (0, -1)
WL, WR = (-1, 0), (1, 0)
FL, FR = (-1, 1), (1, 1)
BL, BR = (-1, -1), (1, -1)
ORTHO = [F, B, WL, WR]
DIAG = [FL, FR, BL, BR]
ALL8 = ORTHO + DIAG
BOX2 = [(dc, dr) for dc in range(-2, 3) for dr in range(-2, 3) if (dc, dr) != (0, 0)]
# diagonal-lion (Harpy) reach: the 4 diagonal-adjacent squares + the 8 squares
# reachable by two ferz steps (the "even" distance-2 squares).
EVEN8 = [(2, 0), (-2, 0), (0, 2), (0, -2), (2, 2), (-2, 2), (2, -2), (-2, -2)]
DIAG_BOX = DIAG + EVEN8
# Tetrarchs: 6 "long" directions (skip square 1, then slide) + 2 sideways (2-3).
LONG = [F, B, FL, FR, BL, BR]
SIDE = [WL, WR]

# ------------------------------------------------------------ movement tables
# letter -> (slides, leaps, ranged); ranged = [((dc, dr), max_steps), ...]
# (bounded, blockable rides -- NOT jumps). Special pieces (Lion, jumping
# sliders, Regent, Fire Demon, Tetrarchs, Griffon, Harpy, Unicorn, Eagle) are
# NOT in these tables -- they are generated by ``_kind``-dispatched code.
BASE_MOVE = {
    "P": ([], [F], []),                                       # fW
    "D": ([], [BL, BR, F], []),                               # bFfW  (dog)
    "S": ([], [FL, FR, BL, BR, F], []),                       # FfW   (silver)
    "FL": ([], [FL, FR, BL, BR, F, B], []),                   # FvW   (leopard)
    "G": ([], [F, B, WL, WR, FL, FR], []),                    # WfF   (gold)
    "BT": ([], [FL, FR, BL, BR, WL, WR, B], []),              # FsbW  (tiger)
    "N": ([], [(-1, 2), (1, 2)], []),                         # ffN   (shogi knight)
    "KY": ([], [FL, FR, BL, BR, (0, 2), (0, -2), (2, 0), (-2, 0)], []),  # FD (kirin)
    "PH": ([], [F, B, WL, WR, (2, 2), (-2, 2), (2, -2), (-2, -2)], []),  # WA (phoenix)
    "L": ([F], [], []),                                       # fR    (lance)
    "VM": ([F, B], [WL, WR], []),                             # sWvR  (vertical mover)
    "SS": ([WL, WR], [B], [(F, 2)]),                          # bWsRfW2 (soldier)
    "B": (DIAG, [], []),                                      # B
    "R": (ORTHO, [], []),                                     # R
    "DH": (DIAG, ORTHO, []),                                  # BW    (crowned bishop)
    "DK": (ORTHO, DIAG, []),                                  # RF    (castle)
    "Q": (ALL8, [], []),                                      # Q
    "CS": (DIAG + [F, B], [], [(WL, 2), (WR, 2)]),            # BvRsW2 (chariot)
    "WB": (DIAG + [WL, WR], [], [(F, 2), (B, 2)]),            # BsRvW2 (buffalo)
    "K": ([], ALL8, []),                                      # K
}
PROMO_MOVE = {
    "P": ([], [F, B, WL, WR, FL, FR], []),                    # -> Gold (WfF)
    "D": ([BL, BR, F], [], []),                               # -> Greyhound (fRbB)
    "S": ([F, B], [WL, WR], []),                              # -> Vertical Mover
    "FL": (DIAG, [], []),                                     # -> Bishop
    "G": (ORTHO, [], []),                                     # -> Rook
    "BT": ([F, B], [FL, FR, BL, BR, WL, WR], []),             # -> Stag (FsWvR)
    "N": ([WL, WR], [B], [(F, 2)]),                           # -> Soldier
    "PH": (ALL8, [], []),                                     # -> Queen
    "L": ([FL, FR, F, B], [], []),                            # -> White Horse (fBvR)
    "VM": (DIAG + [F, B], [], []),                            # -> Narrow Queen (BvR)
    "SS": (DIAG + [WL, WR], [], [(F, 2), (B, 2)]),            # -> Buffalo
    "B": (DIAG, ORTHO, []),                                   # -> Crowned Bishop (BW)
    "R": (ORTHO, DIAG, []),                                   # -> Castle (RF)
    # KY->Lion, LN->Griffon, Q->Harpy, BG->Regent, RG->Jumping Queen,
    # CS->Tetrarchs, WB->Fire Demon, DH->Unicorn, DK->Eagle : all special.
}
# 22 promotable base types (King, Fire Demon FD, Regent VG never promote).
CAN_PROMOTE = frozenset(
    ["P", "D", "S", "FL", "G", "BT", "N", "KY", "PH", "L", "VM", "SS",
     "B", "R", "DH", "DK", "LN", "Q", "BG", "RG", "CS", "WB"])

# Rough material values (heuristic only; both Kings always present -> K excluded).
VALS = {"P": 1, "D": 2, "N": 2, "L": 3, "S": 3, "BT": 4, "FL": 4, "SS": 4,
        "G": 5, "KY": 5, "PH": 5, "VM": 5, "B": 6, "CS": 6, "R": 8, "WB": 8,
        "DH": 9, "DK": 10, "BG": 12, "RG": 13, "Q": 14, "VG": 15, "LN": 22,
        "FD": 30, "K": 0}
PVALS = {"P": 5, "D": 5, "N": 4, "L": 7, "S": 5, "BT": 6, "FL": 6, "SS": 8,
         "G": 8, "KY": 22, "PH": 14, "VM": 9, "B": 9, "CS": 20, "R": 10,
         "WB": 30, "DH": 16, "DK": 16, "BG": 15, "RG": 20, "Q": 24, "LN": 30}

# Black's setup, rows 0-4 (White = the 180-degree rotation). Extracted VERBATIM
# from the CVP interactive-diagram Betza block's initial squares (a1=col0..
# m1=col12; rank r -> row r-1). Cross-checked vs the rank-by-rank prose (which
# AGREES except it swaps chariot/buffalo on d2/k2 -- an apparent prose typo; the
# executable diagram config places chariot d2, buffalo k2, and the scout brief
# agrees). See rules.md.
ROW0 = ["L", "N", "FL", "S", "G", "BT", "K", "BT", "G", "S", "FL", "N", "L"]
ROW1 = {0: "VM", 2: "KY", 3: "CS", 5: "LN", 6: "FD", 7: "Q", 9: "PH",
        10: "WB", 12: "VM"}
ROW2 = ["SS", "B", "R", "DH", "DK", "BG", "RG", "VG", "DK", "DH", "R", "B", "SS"]
DOGS = (3, 9)                                                # d5, j5 (row 4)


@dataclass
class NuttyState(SState):
    winner: object = None      # seat that removed the opponent's King
    key: str = ""              # cached repetition key (recomputed, not serialized)


class NuttyShogi(ShogiLike):
    # uid comes from the manifest; do not hardcode it here.
    name = "Nutty Shogi"

    WIDTH = HEIGHT = 13
    ZONE = 4
    PLY_CAP = 600
    LABELS = {
        "D": "Dg", "FL": "FL", "BT": "Ti", "N": "Kn", "KY": "Ky", "PH": "Ph",
        "VM": "VM", "SS": "So", "DH": "CB", "DK": "Ca", "LN": "Ln", "BG": "jB",
        "RG": "jR", "CS": "Ch", "WB": "Bu", "VG": "Rg", "FD": "FD",
        "+P": "+G", "+D": "Gh", "+S": "+V", "+FL": "+B", "+G": "+R", "+BT": "St",
        "+N": "So+", "+KY": "Ln", "+PH": "Q", "+L": "WH", "+VM": "NQ",
        "+SS": "Bu", "+B": "CB", "+R": "Ca", "+DH": "Un", "+DK": "Ea",
        "+LN": "Gr", "+Q": "Hp", "+BG": "Rg", "+RG": "jQ", "+CS": "Te",
        "+WB": "FD",
    }

    def __init__(self):
        # No reverse-attack maps: Nutty has no check rule (win = King off the
        # board) and no Lion-trading recapture test. attacked() (for the
        # selftest) is computed forward from the same move generator.
        pass

    # ---- kind dispatch -----------------------------------------------------
    def _kind(self, letter, promoted):
        """Return the special-generator tag for this (letter, promoted), or
        None for a table-driven 'plain' piece."""
        if not promoted:
            return {"LN": "LION", "BG": "JBISHOP", "RG": "JROOK",
                    "VG": "REGENT", "FD": "FIREDEMON"}.get(letter)
        return {"KY": "LION", "LN": "GRIFFON", "Q": "HARPY", "WB": "FIREDEMON",
                "BG": "REGENT", "RG": "JQUEEN", "CS": "TETRARCHS",
                "DH": "UNICORN", "DK": "EAGLE"}.get(letter)

    def _jrank(self, letter, promoted):
        """Jumping-general rank: what a jumper may jump OVER (strictly lower)."""
        if letter == "K":
            return 4
        if letter == "RG" and promoted:
            return 3                      # Jumping Queen
        if letter == "VG" or (letter == "BG" and promoted):
            return 2                      # Regent
        if letter in ("BG", "RG") and not promoted:
            return 1                      # Jumping Rook / Jumping Bishop
        return 0

    def _is_fire_demon(self, letter, promoted):
        return letter == "FD" or (letter == "WB" and promoted)

    # ---- primitive generators ----------------------------------------------
    def _slides(self, board, f, pl, dirs, fwd):
        fs = f"{f[0]},{f[1]}"
        for (dc, dr) in dirs:
            d = (dc, dr * fwd)
            cc = (f[0] + d[0], f[1] + d[1])
            while self.on(*cc):
                occ = board.get(cc)
                if occ is None:
                    yield f"{fs}>{cc[0]},{cc[1]}"
                else:
                    if occ[0] != pl:
                        yield f"{fs}>{cc[0]},{cc[1]}"
                    break
                cc = (cc[0] + d[0], cc[1] + d[1])

    def _plain_moves(self, board, f, pl, letter, promd, fwd):
        slides, leaps, ranged = (PROMO_MOVE if promd else BASE_MOVE)[letter]
        fs = f"{f[0]},{f[1]}"
        for (dc, dr) in leaps:
            to = (f[0] + dc, f[1] + dr * fwd)
            if not self.on(*to):
                continue
            occ = board.get(to)
            if occ is not None and occ[0] == pl:
                continue
            yield f"{fs}>{to[0]},{to[1]}"
        for (dc, dr), n in ranged:
            d = (dc, dr * fwd)
            cc = f
            for _ in range(n):
                cc = (cc[0] + d[0], cc[1] + d[1])
                if not self.on(*cc):
                    break
                occ = board.get(cc)
                if occ is None:
                    yield f"{fs}>{cc[0]},{cc[1]}"
                else:
                    if occ[0] != pl:
                        yield f"{fs}>{cc[0]},{cc[1]}"
                    break
        yield from self._slides(board, f, pl, slides, fwd)

    def _jump_slides(self, board, promoted, f, pl, dirs, mover_rank):
        """A slider that, when capturing, may jump over any number of pieces of
        STRICTLY lower jumping-rank; it may capture any piece regardless of rank
        (the destination need not be jumped over). Non-captures are normal
        slides (blocked by the first piece)."""
        fs = f"{f[0]},{f[1]}"
        for (dc, dr) in dirs:                                 # dirs are symmetric
            cc = (f[0] + dc, f[1] + dr)
            passed = 0
            while self.on(*cc):
                occ = board.get(cc)
                if occ is None:
                    if passed == 0:
                        yield f"{fs}>{cc[0]},{cc[1]}"         # normal slide
                else:
                    if occ[0] != pl:
                        yield f"{fs}>{cc[0]},{cc[1]}"         # capture (maybe over pieces)
                    if self._jrank(occ[1], cc in promoted) < mover_rank:
                        passed += 1                          # jump over lower rank
                    else:
                        break                                # cannot pass this piece
                cc = (cc[0] + dc, cc[1] + dr)

    def _area_targets(self, board, f, pl, max_steps):
        """King-walk of up to ``max_steps`` steps through EMPTY squares,
        stopping at the first capture (no jumping). Returns the set of reachable
        destination squares (an empty square or an enemy). Excludes the origin."""
        reached = set()
        frontier = {f}
        visited = {f}
        for _ in range(max_steps):
            nxt = set()
            for sq in frontier:
                for (dc, dr) in ALL8:
                    t = (sq[0] + dc, sq[1] + dr)
                    if not self.on(*t):
                        continue
                    occ = board.get(t)
                    if occ is None:
                        if t not in visited:
                            visited.add(t)
                            nxt.add(t)
                            reached.add(t)
                    elif occ[0] != pl:
                        reached.add(t)                       # capture -> stop here
            frontier = nxt
        reached.discard(f)
        return reached

    def _tetrarchs(self, board, f, pl):
        """Slider that SKIPS the (ignored, unaffected) first square in every
        direction: unlimited in the 6 long directions, squares 2-3 only
        sideways; plus igui (capture an adjacent enemy without moving)."""
        fs = f"{f[0]},{f[1]}"
        for (dc, dr) in LONG:                                # symmetric set
            cc = (f[0] + 2 * dc, f[1] + 2 * dr)
            while self.on(*cc):
                occ = board.get(cc)
                if occ is None:
                    yield f"{fs}>{cc[0]},{cc[1]}"
                else:
                    if occ[0] != pl:
                        yield f"{fs}>{cc[0]},{cc[1]}"
                    break
                cc = (cc[0] + dc, cc[1] + dr)
        for (dc, dr) in SIDE:
            for k in (2, 3):
                cc = (f[0] + k * dc, f[1] + k * dr)
                if not self.on(*cc):
                    break
                occ = board.get(cc)
                if occ is None:
                    yield f"{fs}>{cc[0]},{cc[1]}"
                else:
                    if occ[0] != pl:
                        yield f"{fs}>{cc[0]},{cc[1]}"
                    break
        for (dc, dr) in ALL8:                                # igui
            t = (f[0] + dc, f[1] + dr)
            if not self.on(*t):
                continue
            occ = board.get(t)
            if occ is not None and occ[0] != pl:
                yield f"{fs}>{t[0]},{t[1]}>{fs}"

    def _power_moves(self, board, f, pl, dirs, fwd):
        """Lion 'sting' power along each given ray: single step, direct 2-leap
        (jump), igui (capture-in-place), out-and-back pass, and double move --
        each leg staying on the same ray."""
        fs = f"{f[0]},{f[1]}"
        for (dc, dr) in dirs:
            d = (dc, dr * fwd)
            m = (f[0] + d[0], f[1] + d[1])
            if not self.on(*m):
                continue
            occ_m = board.get(m)
            ms = f"{m[0]},{m[1]}"
            if occ_m is None:
                yield f"{fs}>{ms}>{ms}"                       # single step
                yield f"{fs}>{ms}>{fs}"                       # pass
            elif occ_m[0] != pl:
                yield f"{fs}>{ms}>{ms}"                       # capture-step
                yield f"{fs}>{ms}>{fs}"                       # igui
            j = (f[0] + 2 * d[0], f[1] + 2 * d[1])
            if not self.on(*j):
                continue
            occ_j = board.get(j)
            js = f"{j[0]},{j[1]}"
            if occ_j is None or occ_j[0] != pl:
                yield f"{fs}>{js}"                            # direct 2-leap
            if occ_m is not None and occ_m[0] != pl and (occ_j is None or occ_j[0] != pl):
                yield f"{fs}>{ms}>{js}"                       # double move

    def _lion_moves(self, board, f, pl, steps, box):
        """Generic (possibly direction-restricted) Lion: up to two king steps
        per turn (changing direction), first step may jump. Encodings:
          ``f>t``      adjacent step (dist 1) or direct 2-leap (dist 2, jumps),
          ``f>m>f``    igui (m enemy) or out-and-back pass (m empty),
          ``f>m>t``    double capture / hit-and-run (m enemy, t != m,f).
        (Adjacent steps use the 2-cell form so they de-duplicate against a
        companion slider's first square in Griffon / Harpy.)"""
        fs = f"{f[0]},{f[1]}"
        for (dc, dr) in box:
            t = (f[0] + dc, f[1] + dr)
            if not self.on(*t):
                continue
            occ = board.get(t)
            if occ is not None and occ[0] == pl:
                continue
            yield f"{fs}>{t[0]},{t[1]}"
        for (dc, dr) in steps:
            m = (f[0] + dc, f[1] + dr)
            if not self.on(*m):
                continue
            occ_m = board.get(m)
            ms = f"{m[0]},{m[1]}"
            if occ_m is None:
                yield f"{fs}>{ms}>{fs}"                       # pass
                continue
            if occ_m[0] == pl:
                continue
            yield f"{fs}>{ms}>{fs}"                           # igui
            for (dc2, dr2) in steps:
                t = (m[0] + dc2, m[1] + dr2)
                if not self.on(*t) or t == f:
                    continue
                occ_t = board.get(t)
                if occ_t is not None and occ_t[0] == pl:
                    continue
                yield f"{fs}>{ms}>{t[0]},{t[1]}"             # double / hit-run

    def _piece_moves(self, state, f, pl, letter, promd, fwd):
        board = state.board
        k = self._kind(letter, promd)
        if k is None:
            yield from self._plain_moves(board, f, pl, letter, promd, fwd)
        elif k == "LION":
            yield from self._lion_moves(board, f, pl, ALL8, BOX2)
        elif k == "GRIFFON":
            yield from self._lion_moves(board, f, pl, ALL8, BOX2)
            yield from self._slides(board, f, pl, DIAG, fwd)
        elif k == "HARPY":
            yield from self._slides(board, f, pl, ALL8, fwd)
            yield from self._lion_moves(board, f, pl, DIAG, DIAG_BOX)
        elif k == "FIREDEMON":
            yield from self._slides(board, f, pl, DIAG + [WL, WR], fwd)
            fs = f"{f[0]},{f[1]}"
            for t in self._area_targets(board, f, pl, 3):
                yield f"{fs}>{t[0]},{t[1]}"
        elif k == "REGENT":
            yield from self._jump_slides(board, state.promoted, f, pl, DIAG, 2)
            fs = f"{f[0]},{f[1]}"
            for t in self._area_targets(board, f, pl, 3):
                yield f"{fs}>{t[0]},{t[1]}"
        elif k == "JBISHOP":
            yield from self._jump_slides(board, state.promoted, f, pl, DIAG, 1)
        elif k == "JROOK":
            yield from self._jump_slides(board, state.promoted, f, pl, ORTHO, 1)
        elif k == "JQUEEN":
            yield from self._jump_slides(board, state.promoted, f, pl, ALL8, 3)
        elif k == "TETRARCHS":
            yield from self._tetrarchs(board, f, pl)
        elif k == "UNICORN":
            yield from self._slides(board, f, pl, DIAG + [B, WL, WR], fwd)
            yield from self._power_moves(board, f, pl, [F], fwd)
        elif k == "EAGLE":
            yield from self._slides(board, f, pl, ORTHO + [BL, BR], fwd)
            yield from self._power_moves(board, f, pl, [FL, FR], fwd)

    # ---- move generation (with de-dup + central promotion) -----------------
    def _moves(self, state):
        board, pl = state.board, state.to_move
        fwd = self._fwd(pl)
        seen = set()
        for sq, (p, letter) in list(board.items()):
            if p != pl:
                continue
            promd = sq in state.promoted
            fz = self.in_zone(pl, sq[1])
            promotable = (not promd) and (letter in CAN_PROMOTE)
            for m in self._piece_moves(state, sq, pl, letter, promd, fwd):
                if m in seen:
                    continue
                seen.add(m)
                yield m
                if not promotable:
                    continue
                cells = [cell(c) for c in m.split(">")]
                final = cells[-1]
                if len(cells) == 2:
                    occ = board.get(cells[1])
                    cap = occ is not None and occ[0] != pl
                else:
                    om = board.get(cells[1])
                    cap = om is not None and om[0] != pl
                    if not cap and cells[2] not in (cells[1], sq):
                        ot = board.get(cells[2])
                        cap = ot is not None and ot[0] != pl
                tz = self.in_zone(pl, final[1])
                if (tz and not fz) or (fz and cap):
                    pm = m + "=+"
                    if pm not in seen:
                        seen.add(pm)
                        yield pm

    # ---- Game interface ----------------------------------------------------
    def setup_board(self):
        b = {}
        for c, t in enumerate(ROW0):
            b[(c, 0)] = (BLACK, t)
        for c, t in ROW1.items():
            b[(c, 1)] = (BLACK, t)
        for c, t in enumerate(ROW2):
            b[(c, 2)] = (BLACK, t)
        for c in range(self.WIDTH):
            b[(c, 3)] = (BLACK, "P")
        for c in DOGS:
            b[(c, 4)] = (BLACK, "D")
        for (c, r), (p, t) in list(b.items()):
            b[(self.WIDTH - 1 - c, self.HEIGHT - 1 - r)] = (WHITE, t)
        return b, set()

    def initial_state(self, options=None, rng=None):
        board, promoted = self.setup_board()
        st = NuttyState(board=board, promoted=frozenset(promoted),
                        hands={BLACK: {}, WHITE: {}}, to_move=BLACK)
        st.key = self._poskey(st)
        st.reps = {st.key: 1}
        return st

    def legal_moves(self, state):
        if state.winner is not None or self._draw(state):
            return []
        return list(self._moves(state))

    def _draw(self, state) -> bool:
        if state.winner is not None:
            return False
        return state.ply >= self.PLY_CAP or state.reps.get(state.key, 0) >= 4

    def is_terminal(self, state) -> bool:
        if state.winner is not None or self._draw(state):
            return True
        return next(self._moves(state), None) is None

    def returns(self, state):
        if state.winner is not None:
            return [1.0, -1.0] if state.winner == BLACK else [-1.0, 1.0]
        if self._draw(state):
            return [0.0, 0.0]
        return [-1.0, 1.0] if state.to_move == BLACK else [1.0, -1.0]

    def apply_move(self, state, move, rng=None):
        promote = move.endswith("=+")
        if promote:
            move = move[:-2]
        cells = [cell(p) for p in move.split(">")]
        f = cells[0]
        b = dict(state.board)
        prom = set(state.promoted)
        pl, letter = b.pop(f)
        was_prom = f in state.promoted
        prom.discard(f)
        enemy = 1 - pl

        if len(cells) == 2:
            final = cells[1]
            if b.pop(final, None) is not None:
                prom.discard(final)
        else:
            m, final = cells[1], cells[2]
            if b.pop(m, None) is not None:
                prom.discard(m)
            if final != m and final != f:
                if b.pop(final, None) is not None:
                    prom.discard(final)
        b[final] = (pl, letter)
        prom.discard(final)
        if promote or was_prom:
            prom.add(final)

        # ---- Fire effects ----------------------------------------------------
        # Passive burn (priority): if the mover LANDS next to a surviving enemy
        # Fire Demon, the mover is destroyed before it can do anything else.
        burned = False
        for (dc, dr) in ALL8:
            nb = (final[0] + dc, final[1] + dr)
            occ = b.get(nb)
            if occ is not None and occ[0] == enemy and self._is_fire_demon(occ[1], nb in prom):
                burned = True
                break
        if burned:
            b.pop(final, None)
            prom.discard(final)
        elif self._is_fire_demon(letter, final in prom):
            # Active burn: the (surviving) Fire Demon torches every enemy on its
            # eight neighbours.
            for (dc, dr) in ALL8:
                nb = (final[0] + dc, final[1] + dr)
                occ = b.get(nb)
                if occ is not None and occ[0] == enemy:
                    b.pop(nb, None)
                    prom.discard(nb)

        # ---- win as event: a King left the board ----------------------------
        winner = state.winner
        has_bk = any(p == BLACK and t == "K" for (p, t) in b.values())
        has_wk = any(p == WHITE and t == "K" for (p, t) in b.values())
        if not has_bk:
            winner = WHITE
        elif not has_wk:
            winner = BLACK

        st = NuttyState(board=b, promoted=frozenset(prom),
                        hands={BLACK: {}, WHITE: {}}, to_move=enemy,
                        ply=state.ply + 1, reps=dict(state.reps), winner=winner)
        st.key = self._poskey(st)
        st.reps[st.key] = st.reps.get(st.key, 0) + 1
        return st

    # ---- attacks (forward, for the selftest -- NOT used by the live rules) --
    def attacked_squares(self, state, by):
        """Set of opponent-occupied squares that side ``by`` can remove this
        turn (capture OR burn), computed FORWARD from the same move generator
        so it can never disagree with movegen."""
        probe = NuttyState(board=dict(state.board), promoted=frozenset(state.promoted),
                           hands={BLACK: {}, WHITE: {}}, to_move=by)
        probe.key = ""
        probe.reps = {}
        enemy = 1 - by
        victims = {sq for sq, (p, t) in state.board.items() if p == enemy}
        out = set()
        for m in self._moves(probe):
            nb = self.apply_move(probe, m).board
            for sq in victims:
                # the enemy piece is gone if the square is now empty (burnt) or
                # holds a different piece (captured by a piece landing on it).
                if nb.get(sq) != state.board[sq]:
                    out.add(sq)
        return out

    def attacked(self, state, sq, by):
        return sq in self.attacked_squares(state, by)

    # ---- keys / (de)serialise ----------------------------------------------
    def _poskey(self, state) -> str:
        parts = []
        for r in range(self.HEIGHT):
            for c in range(self.WIDTH):
                occ = state.board.get((c, r))
                if occ is None:
                    parts.append(".")
                else:
                    tag = "+" if (c, r) in state.promoted else ""
                    parts.append("bw"[occ[0]] + tag + occ[1])
        return "|".join(parts) + f"#{state.to_move}"

    def serialize(self, state) -> dict:
        d = super().serialize(state)
        d["winner"] = state.winner
        return d

    def deserialize(self, d) -> NuttyState:
        base = super().deserialize(d)
        st = NuttyState(board=base.board, promoted=base.promoted, hands=base.hands,
                        to_move=base.to_move, ply=base.ply, reps=base.reps,
                        winner=d.get("winner"))
        st.key = self._poskey(st)
        return st

    # ---- bot heuristic -----------------------------------------------------
    def heuristic(self, state):
        bal = 0.0
        for sq, (p, t) in state.board.items():
            v = (PVALS if sq in state.promoted else VALS).get(t, 4.0)
            bal += v if p == BLACK else -v
        score = math.tanh(bal / 45.0)
        return [score, -score]

    # ---- presentation ------------------------------------------------------
    def describe_move(self, state, move) -> str:
        promote = move.endswith("=+")
        raw = move[:-2] if promote else move
        parts = raw.split(">")
        f = cell(parts[0])
        _, t = state.board.get(f, (None, "?"))
        tag = self._label(t, f in state.promoted)
        if len(parts) == 3:
            m, tt = cell(parts[1]), cell(parts[2])
            if tt == f:
                if m in state.board:
                    return f"{tag}{parts[0]}x!{parts[1]}"     # igui
                return f"{tag}{parts[0]} pass"
            s1 = "x" if m in state.board else "-"
            s2 = "x" if tt in state.board else "-"
            return f"{tag}{parts[0]}{s1}{parts[1]}{s2}{parts[2]}"
        sep = "x" if cell(parts[1]) in state.board else "-"
        return f"{tag}{parts[0]}{sep}{parts[1]}" + ("+" if promote else "")

    def render(self, state, perspective=None) -> dict:
        pieces = [
            {"cell": f"{c},{r}", "owner": p,
             "label": self._label(t, (c, r) in state.promoted)}
            for (c, r), (p, t) in state.board.items()
        ]
        names = {BLACK: "Sente (Black)", WHITE: "Gote (White)"}
        if state.winner is not None:
            caption = f"{names[state.winner]} wins — enemy King captured or burned"
        elif self.is_terminal(state):
            ret = self.returns(state)
            caption = "Draw" if ret == [0.0, 0.0] else f"{names[0 if ret[0] > 0 else 1]} wins"
        else:
            caption = f"{names[state.to_move]} to move"
        return {
            "board": {"type": "square", "width": self.WIDTH, "height": self.HEIGHT},
            "pieces": pieces,
            "highlights": [],
            "caption": caption,
        }
